### ISSUE TITLE
[🐛 Bug]: element.scrollIntoView() throws "Request failed with status 500 due to move target out of bounds: move target out of bounds"

### ISSUE THREAD

**Issue by spencerlavallesonos** [webdriverio/webdriverio#11866]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

18.17.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
N/A, not configured from initial wdio wizard.
```

### What happened?

When using `element.scrollIntoView()` the error/ warning "Request failed with status 500 due to move target out of bounds: move target out of bounds" is thrown even if the `scrollIntoView()` is executed successfully

### What is your expected behavior?

If a move target is in boundary (is currently on the screen and visible), scrolling to it shouldn't throw an error that the target is out of bounds. 
In this example Sonos.com's main "Shop" button on the top navigation-bar. 

### How to reproduce the bug.

Clone [this repo](https://github.com/spencerlavallesonos/wdio-bug-scrollIntoView), follow the readme, see the output. 

### Relevant log output

```typescript
npm run wdio

> wdio
> wdio run ./wdio.conf.js


Execution of 1 workers started at 2023-12-13T23:48:54.651Z

[0-0] RUNNING in chrome - file:///test/specs/wdiobug.test.js
[0-0] Will trigger "Request failed with status 500"
[0-0] 2023-12-13T23:49:09.006Z ERROR webdriver: Request failed with status 500 due to move target out of bounds: move target out of bounds
[0-0]   (Session info: chrome=120.0.6099.71)
[0-0] PASSED in chrome - file:///test/specs/wdiobug.test.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 120.0.6099.71 mac #0-0] Running: chrome (v120.0.6099.71) on mac
[chrome 120.0.6099.71 mac #0-0] Session ID: 6a5c6510f6bd7785d1caf445b04e4656
[chrome 120.0.6099.71 mac #0-0]
[chrome 120.0.6099.71 mac #0-0] » file:///test/specs/wdiobug.test.js
[chrome 120.0.6099.71 mac #0-0] WDIO Bug
[chrome 120.0.6099.71 mac #0-0]    ✓ element.scrollIntoView() still sending status 500
[chrome 120.0.6099.71 mac #0-0]
[chrome 120.0.6099.71 mac #0-0] 1 passing (14.7s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:17
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment]
This seems like an error in the logs and not an error in the test

**Comment by udarrr** [comment]
It's because actions will be taking x,y from origin regarding w3c documentation not from arguments {x: deltaX, y: delta:Y}

Let (x, y) be the result of [trying](https://www.w3.org/TR/webdriver2/#dfn-try) to [get coordinates relative to an origin](https://www.w3.org/TR/webdriver2/#dfn-get-coordinates-relative-to-an-origin) with source, x offset, y offset, origin, browsing context, and actions options.

If x is less than 0 or greater than the width of the viewport in [CSS pixels](https://www.w3.org/TR/webdriver2/#dfn-css-pixels), then return [error](https://www.w3.org/TR/webdriver2/#dfn-error) with error code [move target out of bounds](https://www.w3.org/TR/webdriver2/#dfn-move-target-out-of-bounds).

If y is less than 0 or greater than the height of the viewport in [CSS pixels](https://www.w3.org/TR/webdriver2/#dfn-css-pixels), then return [error](https://www.w3.org/TR/webdriver2/#dfn-error) with error code [move target out of bounds](https://www.w3.org/TR/webdriver2/#dfn-move-target-out-of-bounds).

i've tried my assumption and it's working the same but without error without calculations x,y, just

```
browser.action('wheel').scroll({ origin: this }).perform();
```

**Comment by udarrr** [comment]
here is reproduceable an example https://github.com/udarrr/moveToExample

**Comment by erwinheitzman** [comment]
@udarrr thanks, I have already put my name on the issue to look into it when I can

**Comment by WillBrock** [comment]
I'm noticing this issue as well while I'm updating to v8.

I may take a look at some point after I fix some other things.

**Comment by erwinheitzman** [comment]
I actually am unable to reproduce this with the examples given, @WillBrock do you have a simple reproducible example for this?

**Comment by spencerlavallesonos** [comment]
@erwinheitzman You're unable to reproduce the bug even with the repo I linked in my initial issue summary? I just cloned, ran `npm install` then `npm run wdio` and was able to confirm it's still happening.

**Comment by erwinheitzman** [comment]
@spencerlavallesonos no I cannot. I took your example and ran it with the latest version which runs fine. Also you forgot some `await`'s in your example (url, expect) which could be the cause.

**Comment by erwinheitzman** [comment]
@spencerlavallesonos you're right, I didn't check the logs.

I'll refer back to my answer here: https://github.com/webdriverio/webdriverio/issues/11866#issuecomment-1854885055

Logs are logs, they are meant for debugging purposes only like in any other piece of software.
Something went wrong yes, and WebdriverIO handled it correctly.

**Comment by spencerlavallesonos** [comment]
@erwinheitzman If something is wrong with logs, shouldn't that be addressed? The issue I'm reporting is that these printouts are present when there's no evident issue interacting with the element. If this is the correct interaction, we should suppress the logs or fix the cause for the logs.

**Comment by nrstaber** [comment]
I am confused, in my tests I see this error, but then my tests pass. If there was an error in the log why are my tests passing?

**Comment by christian-bromann** [comment]
> in my tests I see this error

How do you see this error, mind providing a screenshot?

> If there was an error in the log why are my tests passing?

Because WebdriverIO tries different things to achieve what you are trying to do. It uses WebDriver's action API first to attempt scrolling the element into view. We do this as we believe it is the closes way to a user interaction. If we fail due to the error mentioned in the OP, we fall back to use the Web API for it which does the job but is not our preferred solution since no scroll events are fired.

Again, as long as these errors are in the log files only, it should be fine.

**Comment by nrstaber** [comment]
Here is the log and the next image is the spec reporter that shows the test has passed.
<img width="1365" alt=
<img width="869" alt="Screenshot 2024-02-12 at 1 52 55 PM" src="https://github.com/webdriverio/webdriverio/assets/5814826/ce8d2520-e009-4f13-8510-474594e93923">
"Screenshot 2024-02-12 at 1 51 27 PM" src="https://github.com/webdriverio/webdriverio/assets/5814826/5b979c0a-c684-4e50-93c7-bfe36ba9baa1">

**Comment by christian-bromann** [comment]
I see, yes, these error messages should be suppressed.

**Comment by erwinheitzman** [comment]
@christian-bromann these errors are only shown because when you do not specify a outputDir (which is the default) all the logs are shown in the terminal as the default logLevel is set to info iirc.

Setting the outputDir gets rid of the logs and thus the error.
I was thinking of updating our default settings to have a default outputDir to output to.

**Comment by christian-bromann** [comment]
@nrstaber can you verify that you don't have `outputDir` set in your WebdriverIO config?

**Comment by nrstaber** [comment]
I can verify that I don't have `outputDir` in my config.

**Comment by christian-bromann** [comment]
@nrstaber can you verify that you have `logLevel` set to `error`?

**Comment by nrstaber** [comment]
Yes, it is set to error.

**Comment by christian-bromann** [comment]
Gotcha. So yeah in this context the error message can be confusing but I don't really have an idea what would be a better approach. Any feedback would be appreciated.

**Comment by spencerlavallesonos** [comment]
I would think it should be suppressed as `logLevel: error` should indicate it only logs actionable errors. In this case, there's nothing actionable for the engineer working on tests that print out this message.

**Comment by erwinheitzman** [comment]
@spencerlavallesonos `logLevel; silent` already does that as well as setting the `outputDir`. You get an error when there is an actionable error. The logs just contain every command sent to the driver and more, the errors you see are an error thrown when sending the command to the driver, we catch it and resolve the situation so no action is needed. Say you take the example of making a mistake in the code, it will throw an error regardless of the logLevel as the logLevel applies to the driver logs and not the wdio logs.

I think we can certainly make improvements so let me list what I think are things we could work on.

Takeaways for us:
- I would like to set `outputDir` to a default value so that we do not pollute the terminal as well as prevent this kind of confusion in the future
- I think we should revisit the `logLevel` and it's influence at some point

My advice to you:
- I advice to already use the `outputDir` in your project

**Comment by spencerlavallesonos** [comment]
@erwinheitzman 
> You get an error when there is an actionable error.
> the errors you see are an error thrown when sending the command to the driver, we catch it and resolve the situation so no action is needed.

I agree with @christian-bromann that this 500 error shouldn't be included in `logLevel: error` regardless of `outputDir` being set because as stated above, the error isn't actionable.

**Comment by udarrr** [comment]
I'm wondering if there a chance to have an example with current implementation where it's working without the error at all.

current implementation is scroll({ duration: 0, x: deltaX, deltaY, origin: this }) why are we using x: deltaX and just deltaY it seems always failed correct me if i'm wrong.

**Comment by udarrr** [comment]
I'm wondering if there is a change to have an example where we can use current implementation without the error.

I'd suggest that we can't use x: deltaX, y: deltaY with origin:this simultaneously in scroll({ duration: 0, x: deltaX, y: deltaY, origin: this }) i believe it should be something like just deltaX, deltaY (more than 0 or equal 0 and integer) in scroll({ duration: 0, deltaX, deltaY, origin: this }), please correct me if i'm wrong.

**Comment by WillBrock** [comment]
This sounds similar to the no alert error that prints to the console. We don't set the outputDir when running tests locally because it makes sense to see everything in the console when things fail. 

We just updated to v8 and we see these errors in the console and multiple devs have reported it as errors when running their tests when it is not an error. In v7 this did not happen. It just clutters the console and makes things look like they fail but they pass.

I'm not sure the best approach but I think we should suppress them somehow.

**Comment by christian-bromann** [comment]
@WillBrock I pushed a release yesterday which included https://github.com/webdriverio/webdriverio/pull/12383 that should resolve the issue. I think we can close the issue.

**Comment by WillBrock** [comment]
Awesome, thanks!

**Comment by ivanovicuros** [comment]
After updating to the latest release the error still display in terminal.

**Comment by christian-bromann** [comment]
> After updating to the latest release the error still display in terminal.

Can you share a screenshot?

**Comment by ivanovicuros** [comment]
![Screenshot 2024-03-05 at 1 03 00 PM](https://github.com/webdriverio/webdriverio/assets/92966084/622f0eb4-8e96-42f9-938f-0a78b016269a)

**Comment by christian-bromann** [comment]
@ivanovicuros can you make sure to update all your WebdriverIO dependencies (make sure you nuke your package-lock.json and reinstall everything)? As mentioned above this should be fixed now. If you still see this after updating, mind providing a reproducible example?

**Comment by WillBrock** [comment]
@christian-bromann #12383 changes some of the hardcoded errors but not the `move target out of bounds` error so I don't think that will have any affect on this error. I only see that error referenced in a type in localTypes.ts so I think it's coming from the server and not something in the wdio code. I think this is the same type of thing where you get the browser alert errors in the console when they are really not errors to the end user, with this error it just happens a lot more. I don't know if we can listen for certain types of errors and then do a warn on those instead so they are not logged to the end user in the console.

I updated to 8.32.4, removed node_modules, package-lock and npm i but still have the error.

**Comment by christian-bromann** [comment]
@WillBrock interesting, do you have a minimal reproducible example for this?

**Comment by WillBrock** [comment]
It's just the same thing what the original poster put in the description with the repo linked.

https://github.com/spencerlavallesonos/wdio-bug-scrollIntoView

**Comment by spencerlavallesonos** [comment]
Confirmed still happening even when updating my test repro repo to latest wdio release @christian-bromann 
https://github.com/spencerlavallesonos/wdio-bug-scrollIntoView

![image](https://github.com/webdriverio/webdriverio/assets/129799088/5b842f95-f2b6-43d6-bb79-3e00ddec8579)

**Comment by christian-bromann** [comment]
I pushed another fix that removes the error message.
