### ISSUE TITLE
Reversed waitForExist fails before timeout/element no longer in dom

### ISSUE THREAD

**Issue by qualityshepherd** [webdriverio/webdriverio#1215]
## Reversed waitForExist fails before timeout/element no longer in dom

I've got a method waiting for an element to be removed from the dom thusly: `browser.waitForExist('li.deleting-item', 5000, true);` *Before* the 5 seconds is up, this fails with `CommandError: element (li.deleting-item) still  existing after 5000ms`. The element is NOT found in a search via chrome inspector (see attached pic). 

It seems like reversed `waitForExist` is mistakingly failing when the element it's waiting for is removed from the dom. 

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: 4.2.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* Additional wdio packages used (if applicable): jasmine 

![image](https://cloud.githubusercontent.com/assets/3298906/14190367/f72e0b02-f757-11e5-99a7-8dd3cd080670.png)

**Comment by christian-bromann** [comment]
Fixed and will be published with `v4.0.6`

**Comment by SierraGolf** [comment]
I this supposed to be fixed on the current master, because I tried it and it still fails for me.

**Comment by christian-bromann** [comment]
@SierraGolf it works in our integration tests: https://github.com/webdriverio/webdriverio/blob/master/test/fixtures/specs/element.spec.js#L35-L41 

Do you have a reproducible example?

**Comment by SierraGolf** [comment]
I am on a tight schedule right now, but I will try to provide a reproducible example.
Some hints though, I am using chimpjs which is using wdio-sync and when I debug I can see that the `reverse` parameter is always undefined.

My temporary workarround looks like this.
```
browser.addCommand('waitForNotExisting', function (selector, timeout) {
        if (!timeout) {
            timeout = LOADING_TIMEOUT
        }

        try {
            return this.waitUntil(() => {
                const isExisting = this.isExisting(selector);
                if (!Array.isArray(isExisting)) {
                    return !isExisting;
                }

                let result = true;
                for (let val of isExisting) {
                    result = result && val;
                }

                return !result;
            }, timeout);
        } catch (error) {
            throw new Error(selector + ' never disappeared.');
        }
    });
```

**Comment by christian-bromann** [comment]
@SierraGolf I can not ensure that it works with chimpjs. I just know that I fixes this for the wdio test runner.

**Comment by SierraGolf** [comment]
@christian-bromann can you confirm that it works through wdio-sync?

**Comment by christian-bromann** [comment]
@SierraGolf yeah, [this](https://github.com/webdriverio/webdriverio/blob/master/test/fixtures/specs/element.spec.js#L35-L41) works with the latest wdio-sync. Maybe just wait until I have released the latest version of both of them this week.

**Comment by SierraGolf** [comment]
@christian-bromann ok, will do. 

on a related note, I observed that when I upgraded from 3.4.0 to 4.0.6 that the `element/s` methods got extremely slow (around factor 3000) when asking for non existing elements. which made all those waits I have really slow if the element would already be gone.

I could isolate that it is actually the call to the selenium server that is taking longer, but what is really confusing is that it is independent from the selenium server version. with 3.4.0 webdriverio I used 2.48.2  and with the 4.0.6 I used 2.53.0 of the selenium-standalone server. so I thought it is dependent on the server but when I run 3.4.0 with 2.53.0 it is not slower, and at the same time it is slower with 4.0.6 and 2.48.2.

so something seems to have changed in webdriver.io since 3.4.0 in such a way that it affects the performance of the selenium server.

are you aware of that already or should I create another issue for this?

**Comment by christian-bromann** [comment]
> are you aware of that already or should I create another issue for this?

No but have you tried to tweak the implicit timeout? It is responsible for that delay. I am not aware of anything that could slow down the element/s call

**Comment by SierraGolf** [comment]
jub, you are right, and it were the chimp guys that brought this change, see https://github.com/xolvio/chimp/blob/b4c382dfe41765987884f8ae2f8666158e2ccf85/HISTORY.md#0320
