### ISSUE TITLE
.addCommand is overwritten in wdio-sync

### ISSUE THREAD

**Issue by sixsixtrample** [webdriverio/webdriverio#1221]
## The problem

```
browser.addCommand("loginToCmc", function async (credentials){
return browser
            .url(_DEFAULT_PAGE_)
            .isExisting('#username_control').then(function (exists){
            if(exists) {
                return browser
                    .setValue('#username_control', credentials.login)
                    .setValue('#password_control', credentials.password)
                    .waitAndClick('#login_button')
                    .waitForExist('#organization_control', 30000)
                    .selectByVisibleText('#organization_control', credentials.organization)
                    .waitAndClick('#continue_button')
                    .waitForExist('.task-waiting-msg', 30000, true);
                }
            })
    });

browser.addCommand('waitAndClick', function async (element){
        return browser
            .keys(['Tab'])
            .waitForExist(element, 30000)
            .click(element);
    });

```

Running the .login command above results in `browser.setValue(...).setValue(...) is not a function error`

Per @christian-bromann 

> ahhh .. no I know .. we overwrite the addCommand function in the wdio-sync package
> and these commands are not added to the prototype
> or better to the monad

## Environment

* WebdriverIO version: 4.0.5
* Node.js version: latest
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asnychronous tests:
* Additional wdio packages used (if applicable):

**Comment by christian-bromann** [comment]
@sixsixtrample sorry but I wasn't able to reproduce this issue. See https://github.com/webdriverio/webdriverio/compare/issue1221. I need an reproducible example to fix the issue. Can you somehow get this together?

**Comment by sixsixtrample** [comment]
@christian-bromann I will try to get a working example running today, but I have this issue specifically when one custom command is calling another one.

Will work on this today though

**Comment by sixsixtrample** [comment]
`
browser.addCommand('someCustomCommand', function (element) {
            return browser
                .keys(['Tab'])
                .waitForExist(element, 30000)
                .click(element)
        })

        browser.addCommand('anotherCustomCommand', () => {
            return browser.someCustomCommand().then(() => {
                return true
            })
        })

        browser.addCommand('notAnotherCustomCommand', () => {
            return browser.url('http://localhost:8080').isExisting('body').then((exists) => {
                if (exists) {
                    return browser
                        .setValue('textarea', 'yo')
                        .someCustomCommand('textarea')
                        .setValue('textarea', 'hey')
                        .waitForExist('body', 100)
                        .getValue('textarea').then((value) => {
                            expect(value).to.be.equal('hey')
                        })
                }
            })
        })
`

I updated those tests a bit. That is what is causing my error. Also, in my code, those custom commands are `async`. Do they not need to be `async`?

**Comment by christian-bromann** [comment]
> Do they not need to be async?

Now if you run your tests sync you can easily rewrite them!

What's your environment?

## Environment

* WebdriverIO version:
* Node.js version:
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html):
* if wdio testrunner, running synchronous or asnychronous tests:
* Additional wdio packages used (if applicable):

**Comment by sixsixtrample** [comment]
**WebdriverIO version**: 4.0.5
**Node.js version: **latest
**Standalone mode or wdio testrunner: **wdio testrunner
**if wdio testrunner, running synchronous or asnychronous tests:** sync: true, but async for this test
**Additional wdio packages used (if applicable):** jasmine

**
Below is not related to this bug, just exposition about why I encountered it.
**

The problem I'm having is that it isn't easy to rewrite a test what has something like a `click` or `wait` in it because you can't chain it. So you end up having to change this:

```
browser
            .waitAndClick(navMenu.patientDetailsNav)
            .pause(2000)
            .waitAndClick(patientDetailsPage.GPpracticeSearchButton)
            .setValue(patientDetailsPage.GPpracticeSearchPopup.searchValue, patientDetailsPage.GPpracticeSearchPopup.practiceToSearch)
            .waitAndClick(patientDetailsPage.GPpracticeSearchPopup.searchButton)
            .waitAndClick(patientDetailsPage.GPpracticeSearchPopup.searchResult)
            .pause(2000)
            .waitAndClick(navMenu.patientDetailsNav)
            .pause(2000);

```

to this:

```
browser.waitAndClick(navMenu.patientDetailsNav);
browser.pause(2000);
browser.waitAndClick(patientDetailsPage.GPpracticeSearchButton);
browser.setValue(patientDetailsPage.GPpracticeSearchPopup.searchValue, patientDetailsPage.GPpracticeSearchPopup.practiceToSearch);
browser.waitAndClick(patientDetailsPage.GPpracticeSearchPopup.searchButton);
browser.waitAndClick(patientDetailsPage.GPpracticeSearchPopup.searchResult);
browser.pause(2000);
browser.waitAndClick(navMenu.patientDetailsNav);
browser.pause(2000);

```

Which ends up adding a lot of _seemingly_ unnecessary 'browser.' instead of chaining.

**Comment by christian-bromann** [comment]
I believe this is fixed on current master. I will do a recheck though.

**Comment by christian-bromann** [comment]
yeah this is fixed

**Comment by slavede** [comment]
Is this tagged in latest (4.2.7) version? I still get browser.getElement('<something'>.setValue is not a function when using it in before hook.

**Comment by christian-bromann** [comment]
Please also update your framework adapters

**Comment by slavede** [comment]
I'm using following npm modules to run this:

wdio-dot-reporter@0.0.6
webdriverio@4.2.7
wdio-jasmine-framework@0.2.5

Am I missing something here?
