### ISSUE TITLE
[🐛 Bug]: <webdriverio + edgedriver: The uploadFile command is not available in msedge>

### ISSUE THREAD

**Issue by d3m1art** [webdriverio/webdriverio#12385]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.25.2

### Node.js Version

18.12.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      // maxInstances can get overwritten per capability. So if you have an in-house Selenium
      // grid with only 5 firefox instances available you can make sure that not more than
      // 5 instances get started at a time.
      maxInstances: 5,
      //
      browserName: 'chrome',
      acceptInsecureCerts: true,
      // If outputDir is provided WebdriverIO can capture driver session logs
      // it is possible to configure which logTypes to include/exclude.
      // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
      // excludeDriverLogs: ['bugreport', 'server'],
      'goog:chromeOptions': {
        // extensions: [base64data],
        extensions: [base64Extension],
        prefs: {
          'download.default_directory': global.downloadDir,
        },
        args: [
          // `--disable-extensions-except=${pathToExtension}`,
          // `--load-extension=${pathToExtension}`,
          '--user-agent=ExtensionE2ETests',
        ],
      },
    },
```

### What happened?

We use webdriverio + edgedriver to run autotests.

Our tests work in Chrome.
But in Edge:
Error: The uploadFile command is not available in msedge at Browser.uploadFile (\node_modules\webdriverio\build\commands\browser\uploadFile.js:50:15) at Browser.wrapCommandFn (\node_modules\@wdio\utils\build\shim.js:137:38) at processTicksAndRejections (node:internal/process/task_queues:96:5)

Please advise us on how can we solve this problem to test the upload file functionality.

### What is your expected behavior?

The test works properly in MS Edge

### How to reproduce the bug.

```
export const setInputFile = async (filePath, file: WebdriverIO.Element) => {
  await browser.execute((el: any) => (el.style.display = 'block'), file);
  await file.waitForDisplayed();
  const remoteFilePath = await browser.uploadFile(filePath);
  await file.setValue(remoteFilePath);

  await browser.execute((el: any) => (el.style.display = 'none'), file);
};
```

### Relevant log output

```typescript
[MicrosoftEdge 122.0.2365.8 windows #0-4] The uploadFile command is not available in MicrosoftEdge
[MicrosoftEdge 122.0.2365.8 windows #0-4] Error: The uploadFile command is not available in MicrosoftEdge
[MicrosoftEdge 122.0.2365.8 windows #0-4]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[MicrosoftEdge 122.0.2365.8 windows #0-4]     at async setInputFile (/home/runner/work/chrome/chrome/e2e/lib/helpers/utils.ts:61:26)
[MicrosoftEdge 122.0.2365.8 windows #0-4]     at async Context.<anonymous> (/home/runner/work/chrome/chrome/e2e/specs/email-invoice/sending-invoice-with-attached-pdf.e2e.ts:29:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
The upload command is unfortunately only available in Chrome (I believe) and when using a Selenium server. Since Edge is using Chromium I wonder if we can enable this for Edge too here. Right now we have this command defined in [`@wdio/protocols`](https://github.com/webdriverio/webdriverio/blob/93d2894a6119891d47b125a4160438f39813cb8e/packages/wdio-protocols/src/protocols/chromium.ts#L289-L311) but don't [apply](https://github.com/webdriverio/webdriverio/blob/9aca81ab552bbec28b250bb4ca8fd754bd2a720a/packages/webdriver/src/utils.ts#L194-L197) it to Edge sessions. It would be nice if someone:

- could add an `isChromium` flag that is true when running tests in Chrome and Edge
- apply the Chromium protocol to theses sessions
- verify that upload works
- have a test for the new flag
- it would be nice to also have an example in https://github.com/webdriverio/example-recipes

**Comment by lacell75** [comment]
@d3m1art , could you test the last version? I fixed it

**Comment by d3m1art** [comment]
@lacell75 we use WebdriverIO Version: 7.25.2,  "edgedriver": "5.3.10".

**Comment by d3m1art** [comment]
<img width="1172" alt="Screenshot 2024-03-11 at 17 19 10" src="https://github.com/webdriverio/webdriverio/assets/114672347/dfc076fd-87f7-4610-a7f8-76d4b64e2994">
The issue is still existing

**Comment by christian-bromann** [comment]
@d3m1art this has not been ported back to v7 .. any chance you can update to v8 given that v7 will be deprecated soon?

**Comment by d3m1art** [comment]
we'll try it thanks a lot,  but last time when we wanted to upgrade to v8 we had a lot of issues.

**Comment by christian-bromann** [comment]
What were these issues?

**Comment by d3m1art** [comment]
@christian-bromann For node > 18v we had a lot of errors from ConfigParser
<img width="1382" alt="Screenshot 2024-03-11 at 19 40 19" src="https://github.com/webdriverio/webdriverio/assets/114672347/7ea97f73-15ce-4f7f-ba6d-5a948a602bba">

**Comment by christian-bromann** [comment]
Please make sure to read the [release blog post](https://webdriver.io/blog/2022/12/01/webdriverio-v8-released/), e.g. add `@wdio/types` to your `types` in `tsconfig.json`. Some of these issues seems legit and maybe should be addressed.

**Comment by Delta456** [comment]
I think this issue can be closed because v7 is deprecated and it works on v9 and hopefully v8.

**Comment by christian-bromann** [comment]
@Delta456 good call! I will go ahead and close this. Happy to re-open in case someone still experiences this with v9.
