### ISSUE TITLE
Jasmine - Remaining tests are skipped if waitForExist times out

### ISSUE THREAD

**Issue by patthiel** [webdriverio/webdriverio#1282]
## The problem

When running integration tests written in jasmine on v4.0.7 of wdio, if a waitForExist command within an it() times out then wdio throws an exception and immediately exits. Skipping the remaining tests.

## Environment

* WebdriverIO version: 4.0.7
* Node.js version: 4.2.4
* wdio testrunner running synchronous
* Additional wdio packages used (if applicable): gulp-webdriver

## Link to Selenium/WebdriverIO logs

[Stacktrace](https://gist.github.com/patthiel/56faf1e7371be14e2e5e97ba90c788d8)
[Selenium Logs](https://gist.github.com/patthiel/ab9e660525925ba5b8ad92841a7bdfd2)

## Code To Reproduce Issue
[Reproduceable Spec](https://gist.github.com/patthiel/140144815f03e9fc498bb132f64090c8)

**Comment by kileras** [comment]
We are seeing the same behaviour using node 4 and wdio 4.0.5 running in sync mode directly, no gulp or anything.

**Comment by FS89** [comment]
Can confirm that the same is happening for me without gulp or additional packages.

```
WebdriverIO: 4.0.7
Node.js: 4.2.4
wdio testrunner running synchronous
```

**Comment by williamsm1** [comment]
Seeing the same issue.
- Node v.4.2.4
- WebdriverIO v4.0.7

**Comment by christian-bromann** [comment]
@patthiel if waitForExist can't find the element after the timeout is over it automatically throws an error and let the test fail. Since all it blocks are on the same level they fail automatically. You can nest them in describe blocks to prevent this. This is not a bug of WebdriverIO.

**Comment by patthiel** [comment]
@christian-bromann This is very different behavior than in v.3.4.0 though. Are you considering a `test` as one describe block. I would consider it possible for a describe block to contain multiple tests. Each can be independent from the previous test (but part of the same session).

Is the crux of the issue, the fact that v4 considers each `it()` dependent on the previous `it()` not throwing any errors in order to proceed?

**Comment by christian-bromann** [comment]
This is the way how Jasmine treats failures in tests. It doesn't continue executing the next tests in the same level. Don't know if this has changed because I updated the Jasmine version to v2 however this is not something that is determined by WebdriverIO. There might be an option that allows you to alter that behavior.

**Comment by patthiel** [comment]
Ok thanks @christian-bromann !  @kileras  @FS89 @williamsm1 this behavior can be prevented by setting the below jasmine option in your respective wdio config:

`stopSpecOnExpectationFailure: false,`

**Comment by patthiel** [comment]
@christian-bromann I think this should be reopened.. I just tried the `stopSpecOnExpectationFailure: false,` option in jasmine and it didn't work.. 

I also created [another spec](https://gist.github.com/patthiel/8e85c32e63c0cdab9c99e13397c19c8e) that contains 3 tests, one of which throws an exception (similar to my first example) and this does not skip any of the tests in the spec, despite the middle test failing. 

It seems, if an exception is thrown by the wdio `waitForExist` command, the rest of the spec is skipped.

**Comment by kileras** [comment]
So this behaviour seem a bit strange to me, and I think I understand the intention behind it, but I don't think is the best way of handling it.

So generally speaking I think that when people write they expect to use assertions to make them fail, I don't see often people throwing in the middle os a spec to denote a failure, and they will most likely get confused by this behaviour. And I think that part of that is because this means that the person that writes the test loose control of it, you no longer decide to fail a test, now the tools you use decide for you which I don't think is ideal as you shouldn't try to anticipate or to put arbitrary limits to what the user want to do. Lets say for example what that I want to do something if the element is not visible? or that I have some cool assertion library that does something magical and wonderful? or even that I'm using a test runner that will crash if I throw an exception? 

I think that the previous behaviour or returning true or false instead of keep chaining methods is the best, more flexible and more understandable way of dealing with it.

Also apart form that I think that at least the documentation should be updated as it still says that the method returns a boolean when you choose latest and that made us believe that this was non intentional 😄  (http://webdriver.io/api/utility/waitForVisible.html)

**Comment by patthiel** [comment]
@christian-bromann Any thoughts on @kileras's comments? This behavior is still blocking us from upgrading to v4, especially since if a given waitFor command times out, the subsequent tests that are skipped are not logged anywhere to indicate to users what has occurred.

**Comment by FS89** [comment]
In case it's of any use, I've added a simple hack to our tests to provide the expected functionality.
```
browser._waitForVisible = browser.waitForVisible;
browser.waitForVisible = (selector, ms, reverse) => {
  const timeout = ms || browser.options.waitforTimeout;
  const __fail = () => {
    expect(selector).toBe('visible');
  };
  let wdioWaitForVisibleHasReturned = false;
  setTimeout(() => {
    if (!wdioWaitForVisibleHasReturned) {
      __fail();
    }
  }, timeout);

  try {
    browser._waitForVisible(selector, timeout + 500, reverse);
    wdioWaitForVisibleHasReturned = true;
  } catch (ex) {
    __fail();
  }
};
```

**Comment by patthiel** [comment]
@FS89 thanks for the hack, i had to add a return to get it to work. 

```

**Comment by christian-bromann** [comment]
@patthiel I think this is resolved with the latest `wdio-jasmine-framework` release right?

**Comment by patthiel** [comment]
@christian-bromann confirming this is resolved with latest. (Tested on latest `wdio-jasmine-framework ` and latest `webdriverio`)

**Comment by RayWasHere** [comment]
What was the fix for this? I'm on the latest wdio-jasmine-framework and webdriverio but still encounter this problem. Anytime waitfor timesout the exception will end the test runs.
