### ISSUE TITLE
[🐛 Bug]: v9: TypeError: fetch failed (ECONNREFUSED)

### ISSUE THREAD

**Issue by torbenkohlmeier** [webdriverio/webdriverio#13553]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.9

### Node.js Version

18.20.4

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  'wdio:maxInstances': 1,
  'wdio:enforceWebDriverClassic': true,
  browserName: 'chrome',
  browserVersion: '123',
  'goog:chromeOptions': {
    args: ['--disable-http2', '--headless', '--disable-dev-shm-usage', '--disable-gpu', '--no-sandbox', '--disable-extensions', '--accept-lang=de'],
    prefs: {
      'intl.accept_languages': 'de-DE',
      'download.prompt_for_download': false,
      'download.directory_upgrade': true,
      'download.default_directory': pathToDownloadDirectory
    }
  },
  acceptInsecureCerts: true
}
```

### What happened?

Sporadically, the following error occurs:

    TypeError: fetch failed

    error properties: Object({ cause: Error: connect ECONNREFUSED 127.0.0.1:62837 })
        at node:internal/deps/undici/undici:12618:11
    Caused by: Error: connect ECONNREFUSED 127.0.0.1:62837
    error properties: Object({ errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 62837 })
        at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
        at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

We have a large number of tests and I couldn't find a pattern which tests fail and which not. It seems to be completely random. I even ran the tests on different machines, the error occurs seemingly on any machine (at least Windows 10 and 11).

The error did not occur with webdriverio 8.

### What is your expected behavior?

The error should not occur.

### How to reproduce the bug.

I am not able to create a reproducible example since the error seems to occur completely randomly.

### Relevant log output

```typescript
TypeError: fetch failed

error properties: Object({ cause: Error: connect ECONNREFUSED 127.0.0.1:62837 })
    at node:internal/deps/undici/undici:12618:11
Caused by: Error: connect ECONNREFUSED 127.0.0.1:62837
error properties: Object({ errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 62837 })
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting. My hunch here is that the request retry doesn't work properly with the transition to native `fetch`. Any contributions or help is appreciated.

**Comment by torbenkohlmeier** [comment]
Could you point me to a method where you assume the problem is? Maybe I can find something.

To given an impression of the probability of the error: In our last three test runs with 669 tests, between 14 and 25 tests failed due to the fetch failed error.

**Comment by christian-bromann** [comment]
@torbenkohlmeier sure, [here](https://github.com/webdriverio/webdriverio/blob/cf4e7ecaa4cc9f88705fb5e27af22a5756213634/packages/webdriver/src/request/request.ts) is the file where we make the `fetch`. Before we used `got` and had an option set that would retry the request, this doesn't seem to be working anymore given that native `fetch` doesn't support this afaik.

**Comment by torbenkohlmeier** [comment]
Looks like retries are now handled in the `_request` function. I'm trying our tests with added handling for ECONNREFUSED errors [here](https://github.com/webdriverio/webdriverio/blob/47ac04a7a84c7611f36c881d91253189adb8c52b/packages/webdriver/src/request/index.ts#L240). Currently those errors are not considered for retrying.

**Comment by christian-bromann** [comment]
> Currently those errors are not considered for retrying.

That would be a regression, we should add these.

**Comment by torbenkohlmeier** [comment]
Looks like adding this [here](https://github.com/webdriverio/webdriverio/blob/47ac04a7a84c7611f36c881d91253189adb8c52b/packages/webdriver/src/request/index.ts#L240) fixes it:

      if (response.cause?.code === 'ECONNREFUSED') {
        return retry(response.cause, 'Connection refused.');
      }

Note that this checks `response.cause.code` instead of `response.code` like [here](https://github.com/webdriverio/webdriverio/blob/47ac04a7a84c7611f36c881d91253189adb8c52b/packages/webdriver/src/request/index.ts#L244). Are you sure that works or do we have to adjust it, too?

**Comment by christian-bromann** [comment]
> Looks like we should also handle `UND_ERR_CONNECT_TIMEOUT`.

That makes sense, do you see other error codes you think we should retry? Mind going ahead and raise a PR?

**Comment by torbenkohlmeier** [comment]
This is not fixed in webdriverio 9.1.0. Just got this error again:

	TypeError: fetch failed

	error properties: Object({ cause: Error: connect ECONNREFUSED 127.0.0.1:61734 })
		at node:internal/deps/undici/undici:12618:11
	Caused by: Error: connect ECONNREFUSED 127.0.0.1:61734
	error properties: Object({ errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 61734 })
		at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
		at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
		at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

Looking at #13649 it seems to only add retry for specific HTTP response codes. But responses with errors like ECONNREFUSED and UND_ERR_CONNECT_TIMEOUT shouldn't have any response code since no response could be retrieved from the server.

**Comment by christian-bromann** [comment]
@torbenkohlmeier I pushed another patched that will hopefully address this issue. Please keep me posted if not.

**Comment by torbenkohlmeier** [comment]
I'm sorry to say it's still not fixed. I don't see the "Request timed out!" warnings so no retrying is done.

The reason might be what I found out [here](https://github.com/webdriverio/webdriverio/issues/13553#issuecomment-2355252136). So replacing `const errorCode = (response as RequestLibError).code` with `const errorCode = (response as RequestLibError).cause.code` [here](https://github.com/webdriverio/webdriverio/blob/f70367e464d7c056328cd7d8e57ea296c0e766ae/packages/webdriver/src/request/index.ts#L212) might fix it. Of course we would need to modify RequestLibError.

**Comment by torbenkohlmeier** [comment]
And you might also want to add `UND_ERR_CONNECT_TIMEOUT` since I saw that, too.

**Comment by AKlochanov** [comment]
I see the same problem here. Is there any update on it?

**Comment by christian-bromann** [comment]
@AKlochanov just to set expectation clear: you should never expect others to do work on a bug for you. The beauty of Open Source is that everyone can get involved and this project can only survive thanks to contributions of others.

**Comment by christian-bromann** [comment]
I pushed another patch that will hopefully recreate our previous retry behavior.

**Comment by torbenkohlmeier** [comment]
Yes, now it works, thank you! Now I see many warnings like this indicating that retrying works:

```
[0-70] 2024-09-30T10:10:32.860Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.295/text" with method "GET"
[0-70] 2024-09-30T10:10:32.875Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.294/text" with method "GET"
[0-70] 2024-09-30T10:10:32.878Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.297/text" with method "GET"
[0-70] 2024-09-30T10:10:32.879Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.296/text" with method "GET"
[0-70] 2024-09-30T10:10:32.880Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.299/text" with method "GET"
[0-70] 2024-09-30T10:10:32.881Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.298/text" with method "GET"
[0-70] 2024-09-30T10:10:32.883Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.301/text" with method "GET"
[0-70] 2024-09-30T10:10:32.885Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.300/text" with method "GET"
[0-70] 2024-09-30T10:10:32.887Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.303/text" with method "GET"
[0-70] 2024-09-30T10:10:34.126Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.619/text" with method "GET"
[0-70] 2024-09-30T10:10:34.127Z WARN webdriver: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.8AA6605EE3A4EC553FDF24285096180D.d.5202C9CF65B03EE1DEEAA2055679F1ED.e.622/text" with method "GET"
```

In one case, retrying did not fix the problem and the test failed with:

    Error: WebDriverError: Request failed with error code ECONNREFUSED when running "element/f.59E5FD05714032DB194D599054178984.d.1C81EC4A8A3D1B24984E5BEC89D68304.e.694/text" with method "GET"

      error properties: Object({ url: http://localhost:49388/session/9255289a3fcc7451ccc80c6fbd1eb7b3/element/f.59E5FD05714032DB194D599054178984.d.1C81EC4A8A3D1B24984E5BEC89D68304.e.694/text, opts: Object({ method: 'GET', signal: [object AbortSignal], headers: [object Headers] }), statusCode: undefined, body: undefined, code: 'ECONNREFUSED' })

I assume that all those errors occur due to high load on the test machine. And it seems like in one case it did not recover fast enough. To improve this even more it could help to add a small wait time, maybe increasing with the number of retries. As you can see in the logs above the retries are currently done within milliseconds.

**Comment by christian-bromann** [comment]
> And it seems like in one case it did not recover fast enough. To improve this even more it could help to add a small wait time, maybe increasing with the number of retries.

Mind raising an issue for this please?

**Comment by torbenkohlmeier** [comment]
Of course, I created a feature request: #13725.
