### ISSUE TITLE
[🐛 Bug]: v9 - toBeExisting Command Fails for Element Inside Iframe

### ISSUE THREAD

**Issue by dilpreetj** [webdriverio/webdriverio#13757]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9.0.7

### Node.js Version

v21.7.3

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: [{
        browserName: 'chrome'
}],
```

### What happened?

The test case is failing when executing the toBeExisting command on an element within an iframe. While the $ command to find the element (#tinymce) inside the iframe works correctly, and the toHaveText command successfully verifies that the text is as expected, both .isExisting() and toBeExisting() commands fail to recognize the same element as existing.

This issue has been consistently reproducible on two different websites that contain iframes. The commands function correctly for elements outside of iframes, but fail specifically for elements nested within iframes.

### What is your expected behavior?

I expect the command toBeExisting to return true for the element within the iframe, similar to how it behaves for elements outside of an iframe.

### How to reproduce the bug.

```
  it("should have the correct text", async () => {
    await browser.url("https://the-internet.herokuapp.com/iframe");
    const iframeEl = await $("#mce_0_ifr");
    await browser.switchToFrame(iframeEl);
    const contentEl = await $("#tinymce");
    await expect(contentEl).toHaveText("Your content goes here.");
    await expect(contentEl).toBeExisting(); // this line fails
  });
  ```

### Relevant log output

```typescript
[0-0] 2024-10-12T18:23:08.585Z INFO webdriver: [POST] http://localhost:53970/session
[0-0] 2024-10-12T18:23:08.586Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       'goog:chromeOptions': [Object],
[0-0]       webSocketUrl: true
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     'goog:chromeOptions': {
[0-0]       binary: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
[0-0]     },
[0-0]     webSocketUrl: true
[0-0]   }
[0-0] }
[0-0] 2024-10-12T18:23:09.402Z INFO webdriver: Register BiDi handler for session with id a0e49ef7b047e4bbb7530688e8a9d3d6
[0-0] 2024-10-12T18:23:09.403Z INFO webdriver: Connect to webSocketUrl ws://127.0.0.1:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6
[0-0] 2024-10-12T18:23:09.411Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-10-12T18:23:09.412Z INFO webdriver: Connected session to Bidi protocol
[0-0] 2024-10-12T18:23:09.412Z INFO webdriver: Connected to WebDriver Bidi interface at ws://127.0.0.1:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6
[0-0] 2024-10-12T18:23:09.412Z INFO webdriver: BIDI COMMAND script.addPreloadScript { functionDeclaration: <PreloadScript[868 bytes]>, contexts: undefined }
[0-0] 2024-10-12T18:23:09.414Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted","network.responseCompleted","network.beforeRequestSent","network.fetchError"]}
[0-0] 2024-10-12T18:23:09.414Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.userPromptOpened"]}
[0-0] 2024-10-12T18:23:09.414Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["browsingContext.navigationStarted"]}
[0-0] 2024-10-12T18:23:09.414Z INFO webdriver: BIDI COMMAND session.subscribe {"events":["log.entryAdded"]}
[0-0] 2024-10-12T18:23:09.432Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-12T18:23:09.432Z INFO webdriver: [GET] http://localhost:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6/window
[0-0] 2024-10-12T18:23:09.443Z INFO webdriver: RESULT C7AF6FF19B56C84346B67C3372D1355F
[0-0] 2024-10-12T18:23:09.445Z INFO webdriver: BIDI COMMAND browsingContext.navigate {"context":"C7AF6FF19B56C84346B67C3372D1355F","url":"https://the-internet.herokuapp.com/iframe","wait":"complete"}
[0-0] 2024-10-12T18:23:09.450Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-12T18:23:09.451Z INFO webdriver: [GET] http://localhost:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6/window
[0-0] 2024-10-12T18:23:09.455Z INFO webdriver: RESULT C7AF6FF19B56C84346B67C3372D1355F
[0-0] 2024-10-12T18:23:09.455Z INFO webdriverio:ContextManager: Update current context: C7AF6FF19B56C84346B67C3372D1355F
[0-0] 2024-10-12T18:23:10.596Z INFO webdriver: COMMAND getWindowHandle()
[0-0] 2024-10-12T18:23:10.596Z INFO webdriver: [GET] http://localhost:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6/window
[0-0] 2024-10-12T18:23:10.598Z INFO webdriver: RESULT C7AF6FF19B56C84346B67C3372D1355F
[0-0] 2024-10-12T18:23:10.632Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#mce_0_ifr"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:10.647Z INFO webdriver: COMMAND switchToFrame(<object>)
[0-0] 2024-10-12T18:23:10.647Z INFO webdriver: [POST] http://localhost:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6/frame
[0-0] 2024-10-12T18:23:10.647Z INFO webdriver: DATA {
[0-0]   id: Element {
[0-0]     sessionId: 'a0e49ef7b047e4bbb7530688e8a9d3d6',
[0-0]     elementId: 'f.C7AF6FF19B56C84346B67C3372D1355F.d.3435A1BF5C13D0C04CA66857A9B6ACC0.e.10',
[0-0]     'element-6066-11e4-a52e-4f735466cecf': 'f.C7AF6FF19B56C84346B67C3372D1355F.d.3435A1BF5C13D0C04CA66857A9B6ACC0.e.10',
[0-0]     locator: { type: 'css', value: '#mce_0_ifr' },
[0-0]     selector: '#mce_0_ifr',
[0-0]     parent: Browser {
[0-0]       sessionId: 'a0e49ef7b047e4bbb7530688e8a9d3d6',
[0-0]       capabilities: [Object],
[0-0]       addCommand: [Function (anonymous)],
[0-0]       overwriteCommand: [Function (anonymous)],
[0-0]       addLocatorStrategy: [Function (anonymous)]
[0-0]     },
[0-0]     isReactElement: false,
[0-0]     isShadowElement: false,
[0-0]     addCommand: [Function (anonymous)],
[0-0]     overwriteCommand: [Function (anonymous)]
[0-0]   }
[0-0] }
[0-0] 2024-10-12T18:23:10.685Z INFO webdriver: RESULT null
[0-0] 2024-10-12T18:23:10.686Z INFO webdriver: COMMAND findElement("css selector", "#tinymce")
[0-0] 2024-10-12T18:23:10.686Z INFO webdriver: [POST] http://localhost:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6/element
[0-0] 2024-10-12T18:23:10.686Z INFO webdriver: DATA { using: 'css selector', value: '#tinymce' }
[0-0] 2024-10-12T18:23:10.695Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': 'f.51270450CE8DD8C3299B362AC6562E81.d.CC4CF16E0ACE955D27C5DDC831329D68.e.11'
[0-0] }
[0-0] 2024-10-12T18:23:10.699Z INFO webdriver: COMMAND getElementText("f.51270450CE8DD8C3299B362AC6562E81.d.CC4CF16E0ACE955D27C5DDC831329D68.e.11")
[0-0] 2024-10-12T18:23:10.699Z INFO webdriver: [GET] http://localhost:53970/session/a0e49ef7b047e4bbb7530688e8a9d3d6/element/f.51270450CE8DD8C3299B362AC6562E81.d.CC4CF16E0ACE955D27C5DDC831329D68.e.11/text
[0-0] 2024-10-12T18:23:10.712Z INFO webdriver: RESULT Your content goes here.
[0-0] 2024-10-12T18:23:10.714Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:11.219Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:11.723Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:12.229Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:12.733Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:13.238Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:13.742Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:14.245Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:14.749Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:15.251Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:15.755Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:16.259Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:16.763Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:17.267Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:17.771Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:18.275Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:18.777Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:19.281Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:19.785Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] 2024-10-12T18:23:20.290Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"C7AF6FF19B56C84346B67C3372D1355F"}
[0-0] Error in "My Login application.should have the correct logo text"
Error: Expect $(`#tinymce`) to be existing

Expected: "existing"
Received: "not existing"
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for raising the issue @dilpreetj 

We have just released a new command, called [`switchFrame`](https://webdriver.io/docs/api/browser/switchFrame), that fixes the problem of switching into frames. Given your example, the right code would be:

```ts
  it("should have the correct text", async () => {
    await browser.url("https://the-internet.herokuapp.com/iframe");
    await browser.switchFrame(() => $("#tinymce").isExisting());
    const contentEl = await $("#tinymce");
    await expect(contentEl).toHaveText("Your content goes here.");
    await expect(contentEl).toBeExisting(); // this line fails
  });
```

Let me know if you have any feedback to this command.

**Comment by dilpreetj** [comment]
@christian-bromann I tried that along with other ways as per doc but I am still getting an error - 

```
[0-0] 2024-10-12T19:11:45.628Z INFO webdriver: BIDI COMMAND browsingContext.getTree {}
[0-0] 2024-10-12T19:11:45.630Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"35F40506D7A2A3884D42DAC533C7FC62"}
[0-0] 2024-10-12T19:11:45.638Z INFO webdriver: BIDI COMMAND browsingContext.locateNodes {"locator":{"type":"css","value":"#tinymce"},"context":"35F40506D7A2A3884D42DAC533C7FC62"}
[0-0] Error in "My Login application.should have the correct text"
Error: Could not find the desired frame
```

```

  it("should have the correct text", async () => {
    await browser.url("https://the-internet.herokuapp.com/iframe");
    // await browser.switchFrame($('#mce_0_ifr')); // didn't work
    // await browser.switchFrame('https://the-internet.herokuapp.com/iframe') // didn't work
    await browser.switchFrame(async () => await $("#tinymce").isExisting()); // didn't work
    const contentEl = await $("#tinymce");
    await expect(contentEl).toHaveText("Your content goes here.");
    await expect(contentEl).toBeExisting();
  });
  ```
Package.json - 
```
  "devDependencies": {
    "@wdio/cli": "^9.2.1",
    "@wdio/local-runner": "^9.2.1",
    "@wdio/mocha-framework": "^9.1.3"
  },
  ```
  Could you please let me know if I am missing something?

**Comment by christian-bromann** [comment]
I will take another look at this , please follow #13763
