### ISSUE TITLE
[🐛 Bug]: connectionRetryTimeout  does not affect the actual fetch timeout for greater values

### ISSUE THREAD

**Issue by mykola-mokhnach** [webdriverio/webdriverio#13778]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

latest LTS

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
Does not matter
```

### What happened?

It looks like the `fetch` API timeout is currently not configured by WDIO, so it always uses the default one. See https://stackoverflow.com/questions/76755913/increase-timeout-in-nodejs-built-in-fetch-api for more details.

### What is your expected behavior?

WDIO should wait until the provided timeout occurs or the session creation request is finished

### How to reproduce the bug.

- Set [connectionRetryTimeout](https://webdriver.io/docs/configuration#connectionretrytimeout) option to 6 or more minutes.
- Send a session creation request, which takes more than 5 minutes

### Relevant log output

```typescript
WebDriverError: Request failed with error code UND_ERR_HEADERS_TIMEOUT when running "http://127.0.0.1:4567/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"platformName":"iOS","appium:platformVersion":"17.5","appium:deviceName":"iPhone 15","appium:automationName":"XCUITest","appium:launchWithIDB":true,"appium:noReset":true,"appium:maxTypingFrequency":30,"appium:clearSystemFiles":true,"appium:showXcodeLog":true,"appium:wdaLaunchTimeout":960000,"appium:wdaConnectionTimeout":960000,"appium:useNewWDA":true,"appium:webviewConnectTimeout":30000,"appium:simulatorStartupTimeout":960000,"appium:app":"/Users/runner/work/appium-xcuitest-driver/appium-xcuitest-driver/test/assets/UIKitCatalog-iphonesimulator.app","appium:usePrebuiltWDA":false},"firstMatch":[{}]}}"
      at startWebDriverSession (file:///Users/runner/work/appium-xcuitest-driver/appium-xcuitest-driver/node_modules/webdriver/build/index.js:857:11)
      at async Function.newSession (file:///Users/runner/work/appium-xcuitest-driver/appium-xcuitest-driver/node_modules/webdriver/build/index.js:1558:41)
      at async remote (file:///Users/runner/work/appium-xcuitest-driver/appium-xcuitest-driver/node_modules/webdriverio/build/index.js:7339:20)
      at async initSession (test/functional/helpers/session.js:14:14)
      at async Context.<anonymous> (test/functional/basic/basic-e2e-specs.js:26:14)
```

https://github.com/appium/appium-xcuitest-driver/actions/runs/11381654527?pr=2480
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by davidnavaskoa** [comment]
I still can reproduce the error with the last webdriver version. My deoendencies are:
` "@wdio/appium-service": "^9.4.0",
    "@wdio/cli": "^9.4.0",
    "@wdio/local-runner": "^9.4.0",`

I am running several tests against lambdaTest platform. I have set a long  connectionRetryTimeout: 1200000, but after 5 minutes I obtain the next errors (masking some ids):

`ERROR webdriver: Error: WebDriverError: Request failed with error code UND_ERR_HEADERS_TIMEOUT when running "http://mobile-hub.lambdatest.com/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"lt:options":{"deviceName":"iPhone ([7-9])","name":"automation - ios","isRealMobile":true,"app":"lt://APP10160162001732717332******","platformName":"iOS","build":"ios e2e tests execution - Codemagic build 674729d89357e8df6e5****"}},"firstMatch":[{}]}}"`

Is there anything else we have to configure to make it work? Should you reopen the investigation?

**Comment by christian-bromann** [comment]
I just pushed another commit and triggered a new release for `v9.4.1`, this applies a header timeout which wasn't set before. Let me know if this resolves the problem.

**Comment by davidnavaskoa** [comment]
I have updated to v9.4.1 my dependencies and I still reproduced the same error:
`ERROR @wdio/runner: Error: Failed to create session.
[0-3] WebDriverError: Request failed with error code UND_ERR_HEADERS_TIMEOUT when running "http://mobile-hub.lambdatest.com/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"lt:options":{"deviceName":"iPhone ([7-9])","name":"automation - ios","isRealMobile":true,"app":"lt://APP101601620017327243299***","platformName":"iOS","build":"ios e2e tests execution - Codemagic build 674745629357e8df6*****"}},"firstMatch":[{}]}}"`

**Comment by christian-bromann** [comment]
Can you double check that the update happen correctly by checking the code in your dependencies?

**Comment by davidnavaskoa** [comment]
I have double checked it with a developer and the dependencies should be updated. An example of the package-lock.json in the machine where I am running it: 

    "node_modules/@wdio/local-runner": {
      "version": "9.4.1",
      "resolved": "https://registry.npmjs.org/@wdio/local-runner/-/local-runner-9.4.1.tgz",
      "integrity": "sha512-MM5VM0V7zvajICr6eNROjkppRhGNpdV4nU5hrgSap92nou8G+zBgLxJ45P5BzLw67KQTOEa1E32b/zCBEkO+0g==",
      "dev": true,
      "license": "MIT",
      "dependencies": {
        "@types/node": "^20.1.0",
        "@wdio/logger": "9.1.3",
        "@wdio/repl": "9.0.8",
        "@wdio/runner": "9.4.1",
        "@wdio/types": "9.2.2",
        "async-exit-hook": "^2.0.1",
        "split2": "^4.1.0",
        "stream-buffers": "^3.0.2"
      },
      "engines": {
        "node": ">=18.20.0"
      }
    },


I checked the webdriver folder in the node-modules once the npm ci is done and this is the package.json:

{
  "name": "webdriverio",
  "description": "Next-gen browser and mobile automation test framework for Node.js",
  "version": "9.4.1",
  "homepage": "https://webdriver.io",
  "author": "Christian Bromann <mail@bromann.dev>",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/webdriverio/webdriverio.git",
    "directory": "packages/webdriverio"
  },

Is there anything else I should check?

**Comment by mykola-mokhnach** [comment]
I can confirm the exception still happening after update to 9.4.1, however it now happens less often (or maybe it's just GH CI performing better :) ): https://github.com/appium/appium-xcuitest-driver/actions/runs/12064517569/job/33641489323#step:10:72

**Comment by christian-bromann** [comment]
@davidnavaskoa @mykola-mokhnach the error message suggests that you are on `v9.4.0` and not on `v9.4.1.` which has the fix [0900c7a](https://github.com/webdriverio/webdriverio/commit/0900c7a27d335d7cc8dc357c820a4435f55f6380)

**Comment by davidnavaskoa** [comment]
In my previous comment I added some parts of the code where the dependencies are updated. I update them as usual. Are you completely sure it is in our side? Can anyone else confirm if the error is reproduced in v9.4.1?
