### ISSUE TITLE
[🐛 Bug]: Unable to install `@wdio/globals`

### ISSUE THREAD

**Issue by just-boris** [webdriverio/webdriverio#14586]
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

v20.19.3

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
n/a, the issue happens during `npm install`
```

### What happened?

1. In an empty folder, run `npm i @wdio/globals`
2. See this

```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
npm error A complete log of this run can be found in: ***
```

### What is your expected behavior?

`npm install` works

### How to reproduce the bug.

n/a

### Relevant log output

```typescript
See above
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

**Comment by just-boris** [comment]
Not sure what happened on your end, but `@wdio/globals@9.16.0` package.json file has this content

```json
"peerDependencies": {
  "expect-webdriverio": "^5.3.2",
  "webdriverio": "workspace:*"
},
```

Which is not a supported by NPM format.

Also it was not there in 9.15.0: https://npmdiff.dev/%40wdio%2Fglobals/9.15.0/9.16.0

**Comment by christian-bromann** [comment]
Sorry about that, will push a fix.

**Comment by christian-bromann** [comment]
Fixed in https://github.com/webdriverio/webdriverio/commit/47020cdbf7fd6d0fa1396b6e8daf0563d17ee7f5

**Comment by nspector** [comment]
@christian-bromann Looks like this didn't fully solve the issue for all packages. 9.16.0 published these packages, which include direct version references:

 - @wdio/allure-reporter@9.16.0
 - @wdio/appium-service@9.16.0
 - @wdio/browser-runner@9.16.0
 - @wdio/browserstack-service@9.16.0
 - @wdio/cli@9.16.0
 - @wdio/concise-reporter@9.16.0
 - @wdio/config@9.16.0
 - @wdio/cucumber-framework@9.16.0
 - @wdio/dot-reporter@9.16.0
 - @wdio/firefox-profile-service@9.16.0
 - @wdio/globals@9.16.0
 - @wdio/jasmine-framework@9.16.0
 - @wdio/json-reporter@9.16.0
 - @wdio/junit-reporter@9.16.0
 - @wdio/lighthouse-service@9.16.0
 - @wdio/local-runner@9.16.0
 - @wdio/mocha-framework@9.16.0
 - @wdio/protocols@9.16.0
 - @wdio/reporter@9.16.0
 - @wdio/runner@9.16.0
 - @wdio/sauce-service@9.16.0
 - @wdio/shared-store-service@9.16.0
 - @wdio/smoke-test-reporter@9.16.0
 - @wdio/spec-reporter@9.16.0
 - @wdio/static-server-service@9.16.0
 - @wdio/sumologic-reporter@9.16.0
 - @wdio/testingbot-service@9.16.0
 - @wdio/types@9.16.0
 - @wdio/utils@9.16.0
 - @wdio/webdriver-mock-service@9.16.0
 - webdriver@9.16.0
 - webdriverio@9.16.0

The change you made to fix touched these ones:
 - @wdio/browser-runner@9.16.1
 - @wdio/browserstack-service@9.16.1
 - @wdio/cli@9.16.1
 - @wdio/globals@9.16.1
 - @wdio/jasmine-framework@9.16.1
 - @wdio/lighthouse-service@9.16.1
 - @wdio/local-runner@9.16.1
 - @wdio/runner@9.16.1
 - @wdio/sauce-service@9.16.1
 - @wdio/shared-store-service@9.16.1
 - @wdio/testingbot-service@9.16.1
 - @wdio/webdriver-mock-service@9.16.1

**Comment by christian-bromann** [comment]
Thanks for pointing this out. Let me release for all packages.
