### ISSUE TITLE
browser.elements('selector') no longer works

### ISSUE THREAD

**Issue by albertogasparin** [webdriverio/webdriverio#1589]
After updating wdio-mocha-framework to v0.4.2 (and 0.4.3) `browser.elements()` returns an error when used inside `browser.waitUntil()`.
It run fine up to wdio-mocha-framework 0.4.1 (so it might be a wdio-sync bug)

## Environment

* WebdriverIO version: 4.2.12
* Node.js version: 4.4.1
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable): wdio-mocha-framework@0.4.2

## Link to Selenium/WebdriverIO logs

```
Error: An unknown server-side error occurred while processing the command. (UnknownError:13)
    at Object.Future.wait (/.../node_modules/fibers/future.js:449:15)
    at Object.elements (/.../node_modules/wdio-sync/build/index.js:388:31)
    at Object.<anonymous> (/.../app/components/__tests__/integration.js:82:22)
    at /.../node_modules/wdio-sync/build/index.js:322:29
```

## Code To Reproduce Issue [ Good To Have ]

``` js
browser.waitUntil(() => {
  return browser.elements('div').value.length > 0;
}, 5000, 'waitUntil condition not met');
```

**Comment by christian-bromann** [comment]
Not sure but this should have never worked because elements is a protocol command so you need to access the value property to get the actual response, so
```js
browser.waitUntil(() => {
  return browser.elements('div').value.length > 0;
}, 5000, 'waitUntil condition not met');
```
should work.

**Comment by albertogasparin** [comment]
Sorry, I have oversimplified the example. The error appears with the `.value` prop. I've updated the issue description.

**Comment by christian-bromann** [comment]
Fixed with `webdriverio@4.2.13` thanks for reporting

**Comment by albertogasparin** [comment]
Super! 👍 Thank you for the quick fix and the amazing work you are doing.

**Comment by albertogasparin** [comment]
Sorry to open this again but the issue is not completely fixed. It looks like the context get lost the second time `waitUntil` is evaluated.

```js
let parent = browser.element('#el');
browser.waitUntil(() => {
  let length = parent.elements('div').value.length;
  console.log(length);
  return length > 0;
}, 5000, 'waitUntil condition not met');
```

With other `div` elements on the page, the command will log `0` the first time while returning all divs on the page every time after. Moving the parent selector definition inside the `waitUntil` command works but it should not be mandatory.
