### ISSUE TITLE
TypeError: Cannot read property 'code' of null

### ISSUE THREAD

**Issue by dangmai** [webdriverio/webdriverio#2188]
## The problem

I'm running around ~100 specs on a server, and sometimes WebDriverIO is failing with the following stack trace:

```
TypeError: Cannot read property 'code' of null
    at Request._callback (C:\Program Files (x86)\Jenkins\workspace\iServe Regression Testing\tests\node_modules\webdriverio\build\lib\utils\RequestHandler.js:294:42)
    at Request.self.callback (C:\Program Files (x86)\Jenkins\workspace\iServe Regression Testing\tests\node_modules\webdriverio\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\Program Files (x86)\Jenkins\workspace\iServe Regression Testing\tests\node_modules\webdriverio\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Jenkins\workspace\iServe Regression Testing\tests\node_modules\webdriverio\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
```

Looking at the source code, I think it's failing when the wdio is past the retry count. Unfortunately I can't share the source code that's causing the issue, but maybe you can look at the stack trace above and see what the issue is.

## Environment

* WebdriverIO version: 4.8.0
* Node.js version: v8.1.3
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio testrunner
* if wdio testrunner, running synchronous or asynchronous tests: asynchronous tests
* Additional wdio packages used (if applicable): `wdio-junit-reporter`, `wdio-mocha-framework`, `wdio-selenium-standalone-service`

**Comment by christian-bromann** [comment]
Fixed! This will be released within the next version.

**Comment by acailly** [comment]
I think there is the same problem with err.message two line above your fix. See the comment in your commit.

**Comment by acailly** [comment]
Maybe this issue should be reopen while the err.message error is not fixed?

**Comment by christian-bromann** [comment]
@acailly or maybe open a PR with a simple fix? 😛

**Comment by acailly** [comment]
That's what I had in mind, but a PR for a closed issue? 
You're right, could have done it anyway :sweat_smile:
