### ISSUE TITLE
Successful Browerstack API Call Throwing Error + Terminating Tests

### ISSUE THREAD

**Issue by mmitchellgarcia** [webdriverio/webdriverio#2429]
## The problem
It appears BrowserStack Hub updated their API and wdio now considers the response to 'DELETE' a failure.

## Environment

* WebdriverIO version: 1.0.3
* Node.js version: 6.12.0
* Wdio test runner
* Additional wdio packages used (if applicable): [wdio-browserstack-service](https://github.com/itszero/wdio-browserstack-service/issues/16)

## Details

These are the offending methods: 
- https://github.com/webdriverio/webdriverio/blob/master/lib/helpers/utilities.js#L25
- https://github.com/webdriverio/webdriverio/blob/master/lib/utils/RequestHandler.js#L209

This is the shape of the object Browserstack is returning:
![image](https://user-images.githubusercontent.com/3027357/32626990-f71d838c-c55e-11e7-9522-9cea25da9090.png)

This is where the error is being thrown:
![image](https://user-images.githubusercontent.com/3027357/32626870-90ddd61c-c55e-11e7-85b7-d90841872ccd.png)

## Link to Selenium/WebdriverIO logs

[Logs](https://gist.github.com/mmitchellgarcia/b0d407bb2932e203ff3d9820ec3823f1)

**Comment by christian-bromann** [comment]
@mmitchellgarcia this is Browserstack not being WebDriver complaint. Each response requires to have a value property, according to the [WebDriver spec](https://w3c.github.io/webdriver/webdriver-spec.html#x6-3-processing-model):

> When required to send a response, with arguments status and data, a remote end must run the following steps:
    ...
    - Let response’s body be a JSON Object with a key "value" set to the JSON serialization of data.

**Comment by mmitchellgarcia** [comment]
@christian-bromann thank you - I sent them a [tweet](https://twitter.com/browserstack/status/928996979773882368). Depending on how long it takes them to respond / what they respond with, I have a PR ready. Ideally they'll solve this today, since everyone using Webdriver with BrowserStack have broken tests now.

**Comment by hrmoller** [comment]
This issues seems to be present with webdriverio 4.9.x only.
Downgrading to 4.8.0 solves it for me, which it also might do for others until Browserstack gets WebDriver complaint.

**Comment by mjawa** [comment]
Thanks for letting us know. This issue is fixed now.

**Comment by evan-scott-zocdoc** [comment]
I'm not sure it is. Using webdriverio latest:

<img width="879" alt="screen shot 2017-11-11 at 2 47 40 pm" src="https://user-images.githubusercontent.com/25586630/32692937-4a88da26-c6ef-11e7-9e5f-3a736874b18a.png">

**Comment by christian-bromann** [comment]
Just ran a test and was able to verify that this has been fixed.

**Comment by parris** [comment]
I'm definitely still getting this error still.

Versions:
webdriver - 4.10.1
wdio-browserstack-service - 0.1.14
wdio-mocha-framework - 0.5.12
browserstack-local - 1.3.0

In addition, it appears that the tests pass successfully, but then this issue will cause the test runner to fail.

**Comment by parris** [comment]
So amazingly I woke up this morning, and this stopped happening, with no changes from me.

**Comment by parris** [comment]
Andddd the issue is back. I'm going to talk to the browserstack support team soon, to see what's going on.

**Comment by parris** [comment]
Solution.... switched to sauce. That being said browserstack is investigating it with their team internally. I'll report back if they say anything (they told me it'll take a couple weeks).

**Comment by chethanak** [comment]
would there be any update on this? we are seeing the same issue with browserstack

**Comment by mohitmun** [comment]
@chethanak This issue is already fixed. If you still facing same issue please contact Browserstack support with detailed information

**Comment by repl-ashwani** [comment]
I am getting this issue, Not sure what could be the possible solution. I am using wdio 4.13. Is there a workaround to get rid of this?

I even tried ending the session manually it says "Don't end the session manually. This will be done automatically." 

And when I try to close browser using close method it says "no such session
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17134 x86_64)".

Any suggestions?

**Comment by vedharish** [comment]
This issue was opened because the DELETE response for automate sessions did not have a "value" field originally making BrowserStack "not WebDriver complaint". This was fixed server-side by BrowserStack.

Please note

When webdriverio detects any kind of failure with DELETE rqeuest, it retries the request ignoring the error. The error in the second request is shown in the logs.
[Check the uploaded gist logs](https://gist.github.com/mmitchellgarcia/b0d407bb2932e203ff3d9820ec3823f1#file-wdio-log-L43-L49) which shows that DELETE request was retried.


According to BrowserStack, if it receives a duplicate delete request (even if the first DELETE request is still ongoing etc), it will reply will "ERROR: Session not started or terminated", essentially saying that the session is not present / was deleted. [Check](https://gist.github.com/mmitchellgarcia/b0d407bb2932e203ff3d9820ec3823f1#file-wdio-log-L65)

The above issue was fixed. The symptom was "Session not started or terminated" and the cause was "DELETE response did not have 'value' field"


For further issues with "Session not started or terminated", if you are sure that the cause is the same as above, please follow up here / re-open the issue etc. If not, please create a separate issue.

Other than that, there is one more known issue which shows the symptom "Session not started or terminated" with session being successfully stopped on BrowserStack dashboard and failing / throwing an exception locally on webdriverio.
[Please check this issue](https://github.com/webdriverio/webdriverio/issues/3067) for that, with steps on how to check if your issue is the same as that one. If the issue is neither, then please create a separate issue with steps to reproduce / more logs to debug.
