### ISSUE TITLE
pressKeycode has keyCode type as string

### ISSUE THREAD

**Issue by gitkav** [webdriverio/webdriverio#2774]
Hi,

pressKeycode method has parameter keyCode type as String. The example here
http://webdriver.io/api/mobile/pressKeycode.html

shows type as string but actually a number is passed to it. 
pressKeycode does not work when keyCode value is string.

**Comment by christian-bromann** [comment]
@gitkav thanks for letting me know. I fixed the docs (not deployed yet thought). Feel free to propose a PR next time 😉

**Comment by Gilad-WT** [comment]
@christian-bromann it looks like this is not fixed I'm opening a PR for it

**Comment by Gilad-WT** [comment]
@christian-bromann PR opened https://github.com/webdriverio/webdriverio/pull/3733
