### ISSUE TITLE
Cannot configure MicrosoftEdge with webdriverio v5+

### ISSUE THREAD

**Issue by jlchereau** [webdriverio/webdriverio#3196]
#### Environment (please complete the following information):

 - **WebdriverIO version:** 5.0.3
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 11.6.0
 - **NPM version:** 6.5.0
 - **Browser name and version:** MicrosoftEdge v44.17763.1.0
 - **Platform name and version:** Windows 10 v1809
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service

#### Config of WebdriverIO

```
capabilities: {
        {
            maxInstances: 1,
            browserName: 'MicrosoftEdge',
            platformName: 'windows 10'
        }
}
```

#### Describe the bug

I am migrating a v4 configuration that works with:

```
capabilities: {
        {
            maxInstances: 1,
            browserName: 'MicrosoftEdge',
            osPlatform: 'Windows',
            osVersion: '10'
        }
}
```

but if I use this configuration with webdriverio v5, I get:

```
[0-1] 2018-12-28T11:45:31.086Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [osPlatform, osVersion]
[0-1] 2018-12-28T11:45:31.091Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [osPlatform, osVersion]
[0-1] 2018-12-28T11:45:31.095Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [osPlatform, osVersion]
[0-1] 2018-12-28T11:45:31.099Z ERROR webdriver: Request failed due to Error: Illegal key values seen in w3c capabilities: [osPlatform, osVersion]
    at Request._callback (.\node_modules\webdriver\src\request.js:86:27)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
[0-1] 2018-12-28T11:45:31.104Z ERROR wdio-runner: Error: Illegal key values seen in w3c capabilities: [osPlatform, osVersion]
    at Request._callback (.\node_modules\webdriver\src\request.js:86:27)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
```

So I have tried:

```
capabilities: {
        {
            maxInstances: 1,
            browserName: 'MicrosoftEdge'
        }
}
```

which triggers:

```
Error: Unable to create session from {
  "desiredCapabilities": {
    "browserName": "MicrosoftEdge"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "MicrosoftEdge"
      }
    ]
  }
}
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'DESK', ip: '192.168.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
    at Request._callback (.\node_modules\webdriver\src\request.js:86:27)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
```

and

```
capabilities: {
        {
            maxInstances: 1,
            browserName: 'MicrosoftEdge',
            platformName: 'windows 10'
        }
}
```
which triggers:

```
Error: Unable to create session from {
  "desiredCapabilities": {
    "platformName": "windows 10",
    "browserName": "MicrosoftEdge"
  },
  "capabilities": {
    "firstMatch": [
      {
        "browserName": "MicrosoftEdge",
        "platformName": "windows 10"
      }
    ]
  }
}
Build info: version: '3.141.0', revision: '2ecb7d9a', time: '2018-10-31T20:22:52'
System info: host: 'DESK', ip: '192.168.75.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_131'
Driver info: driver.version: unknown
    at Request._callback (.\node_modules\webdriver\src\request.js:86:27)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
```

In the last two cases, Microsoft Edge is launched but is not automated.

#### Expected behaviour

Any capabilities configuration that works.

Note that I had no issue configuring chrome, firefox and internet explorer with v5 as the capabilities did not require any change since v4.

**Comment by christian-bromann** [comment]
This issue is fixed but not yet released. We will release a new version later today.

**Comment by jlchereau** [comment]
Please note v5.1.0 has not fixed this issue. Logs are exactly the same as above with v5.0.3.

**Comment by christian-bromann** [comment]
osPlatform ans osVersion are indeed invalid w3c capabilities. The latest error is not related to webdriverio, it indicates that you haven’t downloaded the ms edgedriver.

**Comment by jlchereau** [comment]
It is downloaded with selenium-standalone after `selenium-standalone install`.
When I run the test MS Edge is launched and closed but does not seem to receive any command.

**Comment by christian-bromann** [comment]
Please check the driver logs

**Comment by jlchereau** [comment]
I am progressing with this issue and I am keeping you updated because you might want to document this (`@wdio/selenium-standalone-service`).

`selenium-standalone install` installs an obsolete version of MicrosoftEdgeDriiver located at `./node_modules/selenium-standalone/.selenium/edgedriver/17134-MicrosoftEdgeDriver.exe`.

This version is capable of opening and closing MS Edge but won't send any command. This is what I have experienced.

In fact Microsoft has recently changed the way to install MicrosoftWebDriver.exe. See https://blogs.windows.com/msedgedev/2018/06/14/webdriver-w3c-recommendation-feature-on-demand/

You now need to install it from Settings -> Manage Optional Features:

![image](https://user-images.githubusercontent.com/2556751/50562564-a7f30100-0d0c-11e9-8cb6-75badc3df985.png)

or use `DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0` as mentionned on the Microosft WebDriver page at https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads

Then you need to add *seleniumArgs* in wdio.conf.js as shown below:

```
services: ['selenium-standalone'],
seleniumArgs: {
  javaArgs: [
    '-Dwebdriver.edge.driver=C:\\Windows\\System32\\MicrosoftWebDriver.exe'
  ]
},
``` 
The tests are now executing but all tests fail for the same reason:

```
[MicrosoftEdge  windows #0-1] Promise was rejected with the following reason: Error: Unknown error
[MicrosoftEdge  windows #0-1] Error: Promise was rejected with the following reason: Error: Unknown error
[MicrosoftEdge  windows #0-1]     at timer.catch.e (.\node_modules\webdriverio\src\commands\browser\waitUntil.js:63:15)
```

PLease note that nodejs version is 11.6.0 so Promise is available on the server and client code runs with the @babel/polyfill so Promise is also available in the browser.

Please note that the same tests work in Chrome, Firefox and Internet Explorer after being migrated from webdriverio v4 to webdriverio v5, so the issue is not the tests,

Thank you for your help.

**Comment by jlchereau** [comment]
FYI waitUntil is used in a custom command as follows:

```
browser.addCommand('waitForReadyStateEx', function waitForReadyStateEx(
    state,
    timeout
) {
    const that = this;
    that.waitUntil(
        () => state === that.execute(() => document.readyState),
        timeout
    );
});
```

The tests that fail in MS Edge (not chrome, firefox or IE) use:

```
browser.waitForReadyStateEx('complete', 2000);
```

Increasing the timeout to 5000 or 10000 does not help. Note that all timeouts in wdio.conf.js are above 10000 including mochaOpts.timeout.

Using `const logger = require('@wdio/logger').default('X')`, I have changed the custom command as follows:

```
browser.addCommand('waitForReadyStateEx', function waitForReadyStateEx(
    state,
    timeout
) {
    logger.info('------------------------------------------> BEFORE');
    const that = this;
    that.waitUntil(
        () => state === that.execute(() => document.readyState),
        timeout
    );
    logger.info('------------------------------------------> AFTER');
});
```

The error is still the same and the INFO log entries are not displayed, suggesting that the function is not even executed.

**Comment by christian-bromann** [comment]
> I have raised an issue with selenium-standalone at [vvo/selenium-standalone#419](https://github.com/vvo/selenium-standalone/issues/419).

Thanks!

> Please note that the same tests work in Chrome, Firefox and Internet Explorer after being migrated from webdriverio v4 to webdriverio v5, so the issue is not the tests,

And also not in WebdriverIO.

Can you please provide the edgedriver logs?

**Comment by jlchereau** [comment]
I have tried different wdio settings (in wdio.conf.js) to access the logs after reading:
- https://github.com/SeleniumHQ/selenium/wiki/Logging
- https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities
- https://seleniumhq.github.io/selenium/docs/api/javascript/module/selenium-webdriver/lib/logging.html
- https://github.com/webdriverio/webdriverio/issues/590

In wdio.conf.js:

```
capabilities: [{
    maxInstances: 1,
    browserName: 'MicrosoftEdge',
    loggingPrefs: { driver: 'INFO', browser: 'INFO' }
}],
```

This results in:

```
Stderr:
[0-0] 2019-01-07T08:55:33.694Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [loggingPrefs]
[0-0] 2019-01-07T08:55:33.702Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [loggingPrefs]
[0-0] 2019-01-07T08:55:33.707Z WARN webdriver: Request failed due to Illegal key values seen in w3c capabilities: [loggingPrefs]
[0-0] 2019-01-07T08:55:33.716Z ERROR webdriver: Request failed due to Error: Illegal key values seen in w3c capabilities: [loggingPrefs]
    at Request._callback (.\node_modules\webdriver\build\request.js:113:21)
    at Request.self.callback (.\node_modules\request\request.js:185:22)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (.\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:188:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (.\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:276:13)
    at IncomingMessage.emit (events.js:193:15)
```

Do you have any pointers as how to enable edgedriver logs?

**Comment by defusioner** [comment]
Hello guys, any news on this? Still can't get how to run an automated Edge - it opens but drifts as a dead body

**Comment by mgrybyk** [comment]
Nothing special in comparison to other browser drivers except of it works really bad.
But the tests are starting up normally, can't see any difference between wdio and java frameworks here

**Comment by defusioner** [comment]
@mgrybyk could you post some guide on how to enable wdio working with windows 10 and edge please? I think I've seen the whole Google already

**Comment by romanran** [comment]
+1

**Comment by tugend** [comment]
+1

**Comment by johnwun** [comment]
+1

**Comment by vrudhay** [comment]
+1

**Comment by j320** [comment]
+1

**Comment by osmolyar** [comment]
+1

**Comment by christian-bromann** [comment]
Locking this conversation as the issue seem to be resolved and everyone who is experiencing issues should reach out to the Gitter channel with more details.
