### ISSUE TITLE
JUnit Reporter not allowing wdio to execute tests

### ISSUE THREAD

**Issue by ematta** [webdriverio/webdriverio#3557]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.4.17
 - **Mode:** WDIO TestRunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** N/A
 - **Platform name and version:** macOS 10.14.3 (18D42)
 - **Additional wdio packages used (if applicable):** 
```
    "@wdio/allure-reporter": "^5.4.9",
    "@wdio/cli": "^5.4.13",
    "@wdio/local-runner": "^5.4.13",
    "@wdio/mocha-framework": "^5.4.13",
    "@wdio/spec-reporter": "^5.4.15",
    "@wdio/sync": "^5.4.13",
```

**Config of WebdriverIO**

```
module.exports.config = {
  runner: 'local',
  specs: [`./specs/shared/**/*.js`, `./specs/${ config.app }/**/*.js`], // Pulled in from an external file
  exclude: [],
  maxInstances: config.maxInstances, // Pulled in from an external file
  capabilities: capabilities(), // Pulled in from an external file
  logLevel: config.logLevel, // Pulled in from an external file
  deprecationWarnings: true,
  bail: 0,
  baseUrl: config.url, // Pulled in from an external file
  waitforTimeout: 1 * 60 * 1000,
  connectionRetryTimeout: 90000,
  connectionRetryCount: 3,
  framework: 'mocha',
  reporters: [
    'spec',
    ['junit', {
      outputDir: `target`,
      outputFileFormat: {
        single: function () {
          return 'report.xml'
        },
        multi: function (opts) {
          return `WDIO.xunit.${opts.capabilities}.${opts.cid}.xml`
        }
      }
    }],
    [
      'allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: false,
        disableWebdriverScreenshotsReporting: false,
      }
    ]
  ],
  mochaOpts: {
    ui: `bdd`,
    timeout: 10 * 60 * 1000,
    compilers: ['js:@babel/register'],
  },
  before: function () {
    require('@babel/register')
    const chai = require(`chai`)
    global.expect = chai.expect
    chai.Should()
  },
  afterTest: function (test) {
    if (!test.passed) {
      browser.takeScreenshot()
    }
  }
}
```

**Describe the bug**
Use the junit reporter config (modified from Guide) in wdio execution prevents actual execution to be successful.

**To Reproduce**
Use this reporter setting:
```
    ['junit', {
      outputDir: `target`,
      outputFileFormat: {
        single: function () {
          return 'report.xml'
        },
```

Also tried the following:

```
    ['junit', {
      outputDir: `target`,
      outputFileFormat: {
        single: function () {
          return 'report.xml'
        },
        multi: function (opts) {
          return `WDIO.xunit.${opts.capabilities}.${opts.cid}.xml`
        }
      }
    }],
```

Then, running through npm, attempt to execute wdio cli. NPM task looks like `"test": "wdio wdio.conf.js",`

**Expected behavior**
Tests to run, junit to generate reports based off of single and multi-functions.

**Log**

NPM Logs

[singleAndMulti.log](https://github.com/webdriverio/webdriverio/files/2866787/singleAndMulti.log)
[singleOnly.log](https://github.com/webdriverio/webdriverio/files/2866788/singleOnly.log)

**Additional context**
None at the moment.

**Comment by finelord** [comment]
Having the same, validator says `outputFileFormat must be a function` despite docs

**Comment by WillBrock** [comment]
Confirmed this is a bug. Will look to put in a fix.

**Comment by naddison** [comment]
I'm taking a look at this... is it warranted if we drop the "multi" outputFileFormat option and just default to a single report? It would make life easier.

**Comment by naddison** [comment]
I've realized that since reporters are initialized per instance, the `multi` property for outputFile does not work. Basically the fix for this is to update the documentation to drop the outputFile examples using `single` and `multi`. 

To generate a single junit report we will have to come up with something that on `after` event/hook will combine existing reports. Some form of plugin.

**Comment by naddison** [comment]
I've submitted a PR updating the documentation reflecting my comments above. The further question of "how do I aggregate my test results in the reporter" is a larger discussion.

**Comment by naddison** [comment]
@christian-bromann this issue has been resolved, can we close this?

**Comment by christian-bromann** [comment]
great 👍

**Comment by micschro** [comment]
The documentation is still wrong, though. Using the example 
```
outputFileFormat: {
    single: function (options) {
        return 'mycustomfilename.xml';
    }
}
```
will still throw "outputFileFormat must be a function".

**Comment by kdthomas2121** [comment]
The documentation is still incorrect and leading to this error

**Comment by christian-bromann** [comment]
@kdthomas2121 I can't spot this example in the docs anymore

**Comment by kdthomas2121** [comment]
It's still here for the xml reporter, which uses the junit reporter

https://github.com/naddison/webdriverio/blob/240adc5b60cb8c38f8fe25b4c26491a875bb28e4/packages/wdio-junit-reporter/README.md

And the NPM package
https://www.npmjs.com/package/wdio-junit-reporter

Just to confirm as I'm struggling with this, what is the complete way to
output all tests into a single test file?
