### ISSUE TITLE
Applitools example is failing

### ISSUE THREAD

**Issue by kewgrz** [webdriverio/webdriverio#3725]
**Environment:**
 - **WebdriverIO version:** "^5.4.4"
 - **Mode:** WDIO
 - **WDIO Testrunner:** Sync
 - **Node.js version:** 10.14.1
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome 73
 - **Platform name and version:** Mac Mojave

 - **Additional wdio packages used (if applicable):
     "@wdio/applitools-service": "^5.7.2",
    "@wdio/cli": "^5.7.2",
    "@wdio/local-runner": "^5.7.2",
    "@wdio/mocha-framework": "^5.7.2",
    "@wdio/spec-reporter": "^5.7.2",
    "@wdio/sync": "^5.7.2",
    "wdio-chromedriver-service": "^5.0.1"
    "chai": "^4.2.0",
    "chromedriver": "^2.46.0",
    "webdriverio": "^5.7.2"

**Config of WebdriverIO**
exports.config = {
    port: 9515,
    path: '/',
    runner: 'local',
    applitoolsKey: process.env.APPLITOOLS_KEY,
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [],
    maxInstances: 10,

    capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
    }],
    logLevel: 'silent',
    bail: 0,
    baseUrl: 'http://www.google.com',
    waitforTimeout: 10000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    services: ['chromedriver','applitools',],
    framework: 'mocha',
    reporters: ['spec'],
    mochaOpts: {
        ui: 'bdd',
        timeout: 30000,
        compilers: ['js:@babel/register']
    }
}

**Describe the bug**
I was following along with the example of the Applitools Service:
https://webdriver.io/docs/applitools-service.html

The browser opens and goes on about the test. However at the end of the tests the following error appears: 'This class does not implement methods!'. It is failing at the         browser.takeSnapshot().

**To Reproduce**
1. Add applitools to the services
2. Add the API key for it
3. Create a test file
4. Add examples from link above to test file
5. Run it the test

**Expected behavior**
Tests should pass and I should see the results in the Applitools Dashboard.

**Log**
[chrome #0-0] My Google Search
[chrome #0-0]    ✖ should open the page
[chrome #0-0]    ✖ should search for something
[chrome #0-0]
[chrome #0-0] 2 failing (20.7s)
[chrome #0-0]
[chrome #0-0] 1) My Google Search should open the page
[chrome #0-0] This class does not implement methods!
[chrome #0-0] TypeError: This class does not implement methods!
[chrome #0-0]     at InvalidPositionProvider.setPosition (/Users/kw/Documents/applitools-example/node_modules/@applitools/eyes.sdk.core/lib/positioning/InvalidPositionProvider.js:27:11)
[chrome #0-0]     at Eyes.check (/Users/kw/Documents/applitools-example/node_modules/@wdio/eyes.webdriverio/src/Eyes.js:267:39)
[chrome #0-0]     at Browser.global.browser.addCommand.title (/Users/kw/Documents/applitools-example/node_modules/@wdio/applitools-service/build/index.js:62:24)
[chrome #0-0]     at Browser.next [as takeSnapshot] (/Users/kw/Documents/applitools-example/node_modules/webdriver/build/monad.js:120:27)
[chrome #0-0]     at Context.takeSnapshot (/Users/kw/Documents/applitools-example/test/specs/visual.js:4:17)
[chrome #0-0]
[chrome #0-0] 2) My Google Search should search for something
[chrome #0-0] This class does not implement methods!
[chrome #0-0] TypeError: This class does not implement methods!
[chrome #0-0]     at InvalidPositionProvider.setPosition (/Users/kw/Documents/applitools-example/node_modules/@applitools/eyes.sdk.core/lib/positioning/InvalidPositionProvider.js:27:11)
[chrome #0-0]     at Eyes.check (/Users/kw/Documents/applitools-example/node_modules/@wdio/eyes.webdriverio/src/Eyes.js:267:39)
[chrome #0-0]     at Browser.global.browser.addCommand.title (/Users/kw/Documents/applitools-example/node_modules/@wdio/applitools-service/build/index.js:62:24)
[chrome #0-0]     at Browser.next [as takeSnapshot] (/Users/kw/Documents/applitools-example/node_modules/webdriver/build/monad.js:120:27)
[chrome #0-0]     at Context.takeSnapshot (/Users/kw/Documents/applitools-example/test/specs/visual.js:10:17)

**Comment by goatsy** [comment]
I also had problems to set up the example-project.
Now I added also the dependency

"@wdio/eyes.webdriverio": "^2.0.5" 

and some errors vanished.
I'd recommend you re-try it after adding that to your dependencies and see if it makes any difference.

**Comment by christian-bromann** [comment]
Yes I published a new version that should have fixed this issue.

**Comment by kewgrz** [comment]
@christian-bromann 

I added the @wdio/eyes.webdriverio package and it still didn't work. Still getting the same errors.

"@wdio/applitools-service": "^5.7.2"
 "@wdio/eyes.webdriverio": "^2.0.5"

[chrome #0-0] 1) My Google Search should open the page
[chrome #0-0] This class does not implement methods!
[chrome #0-0] TypeError: This class does not implement methods!
[chrome #0-0]     at InvalidPositionProvider.setPosition (/Users/kw/Documents/applitools-example/node_modules/@applitools/eyes.sdk.core/lib/positioning/InvalidPositionProvider.js:27:11)
[chrome #0-0]     at Eyes.check (/Users/kw/Documents/applitools-example/node_modules/@wdio/eyes.webdriverio/src/Eyes.js:267:39)

**Comment by kewgrz** [comment]
I think I see part of the problem. The browser.takeSnapshot doesn't take a string. Once I got rid of the string and the tests passed. It just didn't send the snapshots to my applitools account. Any idea why? I have my apikey set in my wdio.conf file.

**Comment by christian-bromann** [comment]
> Any idea why?

Sorry but the Applitools integration was pretty much just a POC. Unfortunately their webdriverio plugin still runs on v4. I don't have the capacity to work on this. Please help us to get a better integration running. Thanks!

**Comment by tulasirm** [comment]
Hi Kewgrz, any progress on this yet?

**Comment by danieltisdale** [comment]
Any update on this issue? Thanks!

**Comment by kewgrz** [comment]
@tulasirm Not working on this. I only brought up the issue. I wouldn't know how to address this anyway.

**Comment by tulasirm** [comment]
@kewgrz thank you so much for the reply

**Comment by christian-bromann** [comment]
I updated the applitools service yesterday and got it working, see [this](https://github.com/christian-bromann/webdriverio-hands-on/tree/master/solutions/chapter7) example.
