### ISSUE TITLE
Using @wdio/jasmine-framework does not support spec retry on failure

### ISSUE THREAD

**Issue by SanthoshBonala** [webdriverio/webdriverio#4008]
**Pre-check**
- [x] I'm aware that I can [edit the docs](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) and submit a pull request

**Describe the improvement**

I'd like to report
- [x] Unclear documentation
- [ ] A typo
- [x] Missing documentation
- [ ] Other

**Description of the improvement/report**
When I use @wdio/jasmine-framework as a plugin for jasmine. The docs say that I can pass test retry count as the last parameter for the spec or hook. But when I try to do that it picking it as a timeout parameter instead of test retry which is the behaviour of jasmine framework.

** package.json
```
  "dependencies": {
    "@wdio/cli": "^5.7.15",
    "@wdio/jasmine-framework": "^5.7.13",
    "@wdio/local-runner": "^5.7.15",
    "webdriverio": "^5.7.13"
  }
```
** test.js
```
describe('Webdriverio', function () {
    it('Testing async function',  async () => {
        // redirect to url so that we can exceed default 1ms timeout
        let title;
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        browser.url('https://webdriver.io/docs/retry.html');
        title  = await browser.getUrl();
        expect(title).toBeTruthy();
    }, 1);
});
```
Error from @wdio/jasmine-framework adapter:
```
 "Error: Timeout - Async callback was not invoked within 1ms (custom timeout)
    at <Jasmine>
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)"
```

**Comment by mike-d-davydov** [comment]
Please note that it can be an async-specific bug. I have tried it with '@wdio/sync", and it work perfectly (except for it only retries on exceptions, not on expectation failures - which indeed need to be reflected in documentation.

@SanthoshBonala , please kindly check that you have followed setup instructions in `@wdio/jasmine-framework`. Thanks!

**Comment by christian-bromann** [comment]
> except for it only retries on exceptions

This is a bug

> retries didn't happen

This is also a bug

**Comment by himildesai** [comment]
@christian-bromann Are there any plans on fixing retry to work with Jasmin Expect failures? Do you know of a workaround if not?

**Comment by christian-bromann** [comment]
> Are there any plans on fixing retry to work with Jasmin Expect failures?

Absolutely! Please get involved and propose a bugfix. This is an open source project!

**Comment by SanthoshBonala** [comment]
Hey folks,

Got it to work using @wdio/sync.
Even though I was in async mode I had to install @wdio/sync. since this package contains all of the test retry logic which is triggered by fabric context method (referenced in jasmine-framework, to be precise in run method). The only things which can go wrong when using @wdio/sync is not naming the function as async. Even though if we are passing an anonymous async function it still falls back to sync execution since the function type is based on the function name (which is referenced below)

works as sync eventhough sync is set to false in config
```
it('name', async ()=>{})
```

Works as async
```
it('name', async function async(){})
```
The above behavior is due to the follwoing method in @wdio/sync/src/index.js

```
const runSpec = function (specTitle, specFn, origFn, repeatTest = 0) {
    /**
     * user wants handle async command using promises, no need to wrap in fiber context
     */
    if (specFn.name === 'async') {
        return origFn(specTitle, function async (...specArgs) {
            return executeAsync.call(this, specFn, repeatTest, filterSpecArgs(specArgs))
        })
    }

    return origFn(specTitle, function (...specArgs) {
        return new Promise(runSync.call(this, specFn, repeatTest, filterSpecArgs(specArgs)))
    })
}
```
please correct me if i am wrong about sync and async type checking.

And lastly, it does work on both cases expectation failures and errors.

Hope this could help someone. We need to install @wdio/sync eventhough we are running ```sync=false``` to enable retry logic

**Comment by SanthoshBonala** [comment]
To fix the above type checking, I think we need to check the name of the constructor. Below is an example of what I think
```(async ()=>{}).name```
output: ```""```
```(async ()=>{}).constructor.name```
output: ```"AsyncFunction"```

**Comment by christian-bromann** [comment]
> If the above approach is fine then i can send a pr for this

Please do

**Comment by nami-varthakavi** [comment]
Do you guys have an exiting PR up for this? @SanthoshBonala Will, you be able to open up PR anytime soon? I was about to dig down to this issue some point next week as per my schedule...If you have a solution it would be great if you can have a PR up for this :)

**Comment by SanthoshBonala** [comment]
@nami-varthakavi will be sending pr in a couple of days

**Comment by nami-varthakavi** [comment]
> @nami-varthakavi will be sending pr in a couple of days

Thanks a lot :) and thanks for the quick reply

**Comment by SanthoshBonala** [comment]
lets track the issue in [pr ](https://github.com/webdriverio/webdriverio/pull/4308)

**Comment by mgrybyk** [comment]
fixed in https://github.com/webdriverio/webdriverio/pull/4308 and released in 5.11.13

**Comment by nami-varthakavi** [comment]
Hi I tried to run a simple test against WDIO to check the retries on expect failures. this is my code snippet 

import { WDIOHomeWebPage } from '../pages';

describe('Verify navigation', () => {
    it('should navigate to the Home Page when clicked', () => {
        WDIOHomeWebPage.open(); // command to open the url
        expect(browser.getTitle()).toBe('WebdriverIO');
    }, 3);
});

It didn't trigger a retry? Am I doing this correctly or this fix was not for expect failure retries? I'm using 5.12.1 the latest

**Comment by mike-d-davydov** [comment]
As far as I see, this is still not fixed (see above), because reason, why wdio does not retry failed expectations is still there. And I am still working on solution. @mgrybyk @christian-bromann  please re-open, or I can create a separate bug for expectation failures not being retried

**Comment by christian-bromann** [comment]
I looked into this and behavior is as expected. Added smoke tests for it. Please make sure that you've updated the packages correctly by also removing the package-lock file and reinstall dependencies.

**Comment by mike-d-davydov** [comment]
I believe the retry expectations bug us still there. Will create a new one
soon.
