### ISSUE TITLE
getMetrics() result the same values

### ISSUE THREAD

**Issue by rdpanek** [webdriverio/webdriverio#4085]
My setup:

OSX 10.14.4
```
"devDependencies": {
    "@babel/cli": "7.2.3",
    "@babel/core": "7.4.0",
    "@babel/preset-env": "7.4.2",
    "@babel/register": "7.4.0",
    "@wdio/cli": "5.9.4",
    "@wdio/devtools-service": "5.9.6",
    "@wdio/local-runner": "5.9.4",
    "@wdio/mocha-framework": "5.9.4",
    "@wdio/spec-reporter": "5.7.2",
    "@wdio/sync": "5.9.4",
    "aws-sdk": "2.0.9",
    "chai": "4.2.0",
    "node-uuid": "1.4.8",
    "webdriverio": "5.9.4"
  }
```

**wdio.conf.js••
`['devtools', {debuggerAddresss: 'localhost:9222'}]`

**Example**
describe('PT demo', () => {
  before(() => {
    browser.enablePerformanceAudits()
  })

  it('page a', () => {
    browser.url('https://www.xyz.com/')
    console.log(browser.getMetrics())
  })

  it('page b', () => {
    browser.url('https://www.xyz.com/en/shop/')
    console.log(browser.getMetrics())
  })

  it('page c', () => {
    browser.url('https://www.xyz.com/en/shop/basket.html')
    console.log(browser.getMetrics())
  })

  after(() => {
    browser.disablePerformanceAudits()
  })
})

Second and third method `getMetrics` results the same value. Where is a problem?

**Result**
```
[0-0] RUNNING in chrome - /test/demo/metrics.js
[0-0] 2019-06-12T22:34:21.748Z ERROR @wdio/devtools-service:TraceGatherer: Neither network nor CPU idle time could be detected within timeout, wrapping up tracing
[0-0] { estimatedInputLatency: 19,
  timeToFirstByte: 563,
  domContentLoaded: 6191,
  firstVisualChange: 6003,
  firstPaint: 5979,
  firstContentfulPaint: 6234,
  firstMeaningfulPaint: 7569,
  lastVisualChange: 58303,
  firstCPUIdle: 9135,
  firstInteractive: 13511,
  load: 13508,
  speedIndex: 7010 }
[0-0] { estimatedInputLatency: 360,
  timeToFirstByte: 563,
  domContentLoaded: 9512,
  firstVisualChange: 15530,
  firstPaint: 15524,
  firstContentfulPaint: 15524,
  firstMeaningfulPaint: 15524,
  lastVisualChange: 30701,
  firstCPUIdle: 25485,
  firstInteractive: 25485,
  load: 24592,
  speedIndex: 16017 }
[0-0] { estimatedInputLatency: 360,
  timeToFirstByte: 563,
  domContentLoaded: 9512,
  firstVisualChange: 15530,
  firstPaint: 15524,
  firstContentfulPaint: 15524,
  firstMeaningfulPaint: 15524,
  lastVisualChange: 30701,
  firstCPUIdle: 25485,
  firstInteractive: 25485,
  load: 24592,
  speedIndex: 16017 }
[0-0] >>> Elastic total process time: 0 ms
[0-0] >>> Elastic total process time: 0 ms
[0-0] PASSED in chrome - /test/demo/metrics.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome  mac os x #0-0] Spec: /Users/HTDOCS/test-stack/wdio-runner/test/demo/metrics.js
[chrome  mac os x #0-0] Running: chrome on mac os x
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] PT demo
[chrome  mac os x #0-0]    ✓ page a
[chrome  mac os x #0-0]    ✓ page b
[chrome  mac os x #0-0]    ✓ page c
[chrome  mac os x #0-0]
[chrome  mac os x #0-0] 3 passing (1m 50.5s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:01:53 
```

**Comment by christian-bromann** [comment]
I am assuming that something went wrong when trying to calculate the performance metrics for the 3rd page which causes the data not being updated. I think we should rather return an error in this case.

**Comment by rdpanek** [comment]
@christian-bromann no, without errors

```
➜  wdio-runner git:(wdio5-paudit) ✗ PT_AUDIT=allow ENV=localhost WAIT_FOR_TIMEOUT=25000 ./node_modules/.bin/wdio --spec ./test/demo/metrics.js  --baseUrl=https://www.xyz.cz/ 

Execution of 1 spec files started at 2019-06-13T09:01:10.729Z

[0-0] RUNNING in chrome - /test/demo/metrics.js
[0-0] 2019-06-13T09:02:15.438Z ERROR @wdio/devtools-service:TraceGatherer: Neither network nor CPU idle time could be detected within timeout, wrapping up tracing
[0-0] { estimatedInputLatency: 16,
  timeToFirstByte: 570,
  domContentLoaded: 6460,
  firstVisualChange: 6300,
  firstPaint: 6281,
  firstContentfulPaint: 6503,
  firstMeaningfulPaint: 8202,
  lastVisualChange: 60115,
  firstCPUIdle: 9242,
  firstInteractive: 15287,
  load: 15284,
  speedIndex: 8119 }
[0-0] { estimatedInputLatency: 290,
  timeToFirstByte: 571,
  domContentLoaded: 7013,
  firstVisualChange: 14,
  firstPaint: 6075,
  firstContentfulPaint: 6150,
  firstMeaningfulPaint: 8207,
  lastVisualChange: 22164,
  firstCPUIdle: 17030,
  firstInteractive: 17030,
  load: 16083,
  speedIndex: 4709 }
[0-0] { estimatedInputLatency: 290,
  timeToFirstByte: 571,
  domContentLoaded: 7013,
  firstVisualChange: 14,
  firstPaint: 6075,
  firstContentfulPaint: 6150,
  firstMeaningfulPaint: 8207,
  lastVisualChange: 22164,
  firstCPUIdle: 17030,
  firstInteractive: 17030,
  load: 16083,
  speedIndex: 4709 }
[0-0] >>> Elastic total process time: 0 ms
[0-0] >>> Elastic total process time: 0 ms
[0-0] PASSED in chrome - /test/demo/metrics.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 74.0.3729.169 Mac OS X #0-0] Spec: /Users/rdpanek/HTDOCS/test-stack/wdio-runner/test/demo/metrics.js
[chrome 74.0.3729.169 Mac OS X #0-0] Running: chrome (v74.0.3729.169) on Mac OS X
[chrome 74.0.3729.169 Mac OS X #0-0]
[chrome 74.0.3729.169 Mac OS X #0-0] PT demo
[chrome 74.0.3729.169 Mac OS X #0-0]    ✓ page a
[chrome 74.0.3729.169 Mac OS X #0-0]    ✓ page b
[chrome 74.0.3729.169 Mac OS X #0-0]    ✓ page c
[chrome 74.0.3729.169 Mac OS X #0-0]
[chrome 74.0.3729.169 Mac OS X #0-0] 3 passing (1m 43.7s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:01:47 
```

**Comment by christian-bromann** [comment]
> no, without errors

check the wdio logs

**Comment by rdpanek** [comment]
@christian-bromann 

- wdio-0-0-server.log - nothing interesting
- wdio-0-0-browser.log - only warning / recommendation for example
```
{"level":"WARNING","message":"https://connect.facebook.net/en_US/fbevents.js 23:11237 \"[Facebook Pixel] - Duplicate Pixel ID: 226360874407061.\"","source":"console-api","timestamp":1560419644259}
{"level":"WARNING","message":"https://www.ixyz.ab/ - The connection used to load resources from https://bbnaut.ibillboard.com used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later. See https://www.chromestatus.com/feature/5654791610957824 for more information.","source":"other","timestamp":1560419644259}
```
- and wdio-0-0.log - this is more interesting


First measurements contains a lot 
- 2019-06-13T09:53:03.881Z INFO @wdio/devtools-service:TraceGatherer: Waiting on DomContentLoaded
- next a lot 2019-06-13T09:53:09.574Z INFO @wdio/devtools-service:TraceGatherer: Found 12 inflight network records
- and end it

```
2019-06-13T09:54:01.521Z ERROR @wdio/devtools-service:TraceGatherer: Neither network nor CPU idle time could be detected within timeout, wrapping up tracing
2019-06-13T09:54:01.521Z INFO @wdio/devtools-service:TraceGatherer: Tracing completed after 58410ms, capturing performance data for frame B68EC886CD30A1180842A9F1EB655240
2019-06-13T09:54:03.166Z INFO @wdio/devtools-service:TraceGatherer: Replace mainFrame process id 12696 with actual thread process id 12695
2019-06-13T09:54:03.167Z INFO @wdio/devtools-service:TraceGatherer: Tracing for B68EC886CD30A1180842A9F1EB655240 completed
2019-06-13T09:54:03.168Z INFO @wdio/devtools-service: Disable throttling
2019-06-13T09:54:03.170Z INFO @wdio/devtools-service: continuing with next WebDriver command
2019-06-13T09:54:03.171Z INFO webdriver: COMMAND getMetrics()
2019-06-13T09:54:04.243Z INFO webdriver: RESULT { estimatedInputLatency: 16,
  timeToFirstByte: 570,
  domContentLoaded: 6350,
  firstVisualChange: 6188,
  firstPaint: 6168,
  firstContentfulPaint: 6394,
  firstMeaningfulPaint: 8353,
  lastVisualChange: 58154,
  firstCPUIdle: 13317,
  firstInteractive: 13317,
  load: 13313,
  speedIndex: 7258 }
```

Second measurement is similar

```
2019-06-13T09:54:27.494Z INFO @wdio/devtools-service:TraceGatherer: Replace mainFrame process id 12695 with actual thread process id 12695
2019-06-13T09:54:27.502Z INFO @wdio/devtools-service:TraceGatherer: Tracing for B68EC886CD30A1180842A9F1EB655240 completed
2019-06-13T09:54:27.502Z INFO @wdio/devtools-service: Disable throttling
2019-06-13T09:54:27.507Z INFO @wdio/devtools-service: continuing with next WebDriver command
2019-06-13T09:54:27.507Z INFO webdriver: COMMAND getMetrics()
2019-06-13T09:54:28.499Z INFO webdriver: RESULT { estimatedInputLatency: 345,
  timeToFirstByte: 569,
  domContentLoaded: 7728,
  firstVisualChange: 84,
  firstPaint: 6274,
  firstContentfulPaint: 6436,
  firstMeaningfulPaint: 9614,
  lastVisualChange: 21334,
  firstCPUIdle: 16215,
  firstInteractive: 16215,
  load: 15255,
  speedIndex: 5162 }
```

but third measurement is much shortened

```
2019-06-13T09:54:28.501Z INFO @wdio/devtools-service:TraceGatherer: Start tracing frame with url https://www.ixyz.ab/cz/abc_klub/index.html
2019-06-13T09:54:28.507Z INFO @wdio/devtools-service:TraceGatherer: Waiting for CPU to become idle
2019-06-13T09:54:28.507Z INFO webdriver: COMMAND navigateTo("https://www.ixyz.ab/cz/abc_klub/index.html")
2019-06-13T09:54:28.507Z INFO webdriver: [POST] http://127.0.0.1:4444/wd/hub/session/897926a1fa7625a1967cbac79739eb76/url
2019-06-13T09:54:28.508Z INFO webdriver: DATA { url: 'https://www.ixyz.ab/cz/abc_klub/index.html' }
2019-06-13T09:54:28.557Z INFO @wdio/devtools-service:TraceGatherer: Waiting on DomContentLoaded
2019-06-13T09:54:28.568Z INFO @wdio/devtools-service:TraceGatherer: Driver CPU has been idle for 8063.875000007101 ms
2019-06-13T09:54:28.568Z INFO @wdio/devtools-service:TraceGatherer: Driver CPU has been idle for 8063.875000007101 ms
2019-06-13T09:54:29.218Z INFO @wdio/devtools-service:TraceGatherer: Wait for network idle canceled
2019-06-13T09:54:29.218Z INFO @wdio/devtools-service:TraceGatherer: Tracing for "unsuccessful loaded frame" completed
2019-06-13T09:54:43.066Z INFO webdriver: COMMAND getMetrics()
2019-06-13T09:54:43.067Z INFO webdriver: RESULT { estimatedInputLatency: 345,
  timeToFirstByte: 569,
  domContentLoaded: 7728,
  firstVisualChange: 84,
  firstPaint: 6274,
  firstContentfulPaint: 6436,
  firstMeaningfulPaint: 9614,
  lastVisualChange: 21334,
  firstCPUIdle: 16215,
  firstInteractive: 16215,
  load: 15255,
  speedIndex: 5162 }
```

**Comment by rdpanek** [comment]
@christian-bromann test with public sites

```
describe('PT demo', () => {
  before(() => {
    browser.enablePerformanceAudits()
  })

  it('page a', () => {
    browser.url('https://www.youtube.com')
    console.log(browser.getMetrics())
  })

  it('page b', () => {
    browser.url('https://www.facebook.com/')
    console.log(browser.getMetrics())
  })

  it('page c', () => {
    browser.url('https://twitter.com')
    console.log(browser.getMetrics())
  })

  after(() => {
    browser.disablePerformanceAudits()
  })
})
```

result

```
Execution of 1 spec files started at 2019-06-13T10:51:21.682Z

[0-0] RUNNING in chrome - /test/demo/metrics.js
[0-0] { estimatedInputLatency: 16,
  timeToFirstByte: 567,
  domContentLoaded: 7930,
  firstVisualChange: 3996,
  firstPaint: 3966,
  firstContentfulPaint: 3966,
  firstMeaningfulPaint: 7943,
  lastVisualChange: 26531,
  firstCPUIdle: 7943,
  firstInteractive: 7930,
  load: 13753,
  speedIndex: 9273 }
[0-0] { estimatedInputLatency: 16,
  timeToFirstByte: 567,
  domContentLoaded: 7930,
  firstVisualChange: 3996,
  firstPaint: 3966,
  firstContentfulPaint: 3966,
  firstMeaningfulPaint: 7943,
  lastVisualChange: 26531,
  firstCPUIdle: 7943,
  firstInteractive: 7930,
  load: 13753,
  speedIndex: 9273 }
[0-0] { estimatedInputLatency: 16,
  timeToFirstByte: 567,
  domContentLoaded: 7930,
  firstVisualChange: 3996,
  firstPaint: 3966,
  firstContentfulPaint: 3966,
  firstMeaningfulPaint: 7943,
  lastVisualChange: 26531,
  firstCPUIdle: 7943,
  firstInteractive: 7930,
  load: 13753,
  speedIndex: 9273 }
[0-0] >>> Elastic total process time: 0 ms
[0-0] >>> Elastic total process time: 0 ms
[0-0] PASSED in chrome - /test/demo/metrics.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 74.0.3729.169 Mac OS X #0-0] Spec: /Users/rdpanek/HTDOCS/test-stack/wdio-runner/test/demo/metrics.js
[chrome 74.0.3729.169 Mac OS X #0-0] Running: chrome (v74.0.3729.169) on Mac OS X
[chrome 74.0.3729.169 Mac OS X #0-0]
[chrome 74.0.3729.169 Mac OS X #0-0] PT demo
[chrome 74.0.3729.169 Mac OS X #0-0]    ✓ page a
[chrome 74.0.3729.169 Mac OS X #0-0]    ✓ page b
[chrome 74.0.3729.169 Mac OS X #0-0]    ✓ page c
[chrome 74.0.3729.169 Mac OS X #0-0]
[chrome 74.0.3729.169 Mac OS X #0-0] 3 passing (40.4s)


Spec Files:	 1 passed, 1 total (100% completed) in 00:00:42 
```

**Comment by kevinmcdonnell** [comment]
I've encountered this as well

**Comment by DimitryRd** [comment]
```
[0-0] 2019-07-30T07:52:42.033Z INFO webdriver: RESULT 1
[0-0] 2019-07-30T07:52:42.033Z INFO webdriver: COMMAND getPageWeight()
[0-0] 2019-07-30T07:52:42.034Z INFO webdriver: RESULT { pageWeight: 1472831,
  transferred: 538401,
  requestCount: 99,
  details:
   { Document: { size: 1100, encoded: 0, count: 1 },
     Script: { size: 1067611, encoded: 532023, count: 15 },
     XHR: { size: 79, encoded: 90, count: 1 },
     Image: { size: 392783, encoded: 5316, count: 78 },
     Other: { size: 150, encoded: 150, count: 1 },
     Stylesheet: { size: 11108, encoded: 822, count: 1 },
     Font: { size: 0, encoded: 0, count: 2 } } }
[0-0] await browser.getPageWeight();:  { pageWeight: 1472831,
  transferred: 538401,
  requestCount: 99,
  details:
   { Document: { size: 1100, encoded: 0, count: 1 },
     Script: { size: 1067611, encoded: 532023, count: 15 },
     XHR: { size: 79, encoded: 90, count: 1 },
     Image: { size: 392783, encoded: 5316, count: 78 },
     Other: { size: 150, encoded: 150, count: 1 },
     Stylesheet: { size: 11108, encoded: 822, count: 1 },
     Font: { size: 0, encoded: 0, count: 2 } } }
[0-0] TypeError in "Google Maps should init map"
browser.getMetrics is not a function
[0-0] 2019-07-30T07:52:42.038Z INFO webdriver: COMMAND deleteSession()
[0-0] 2019-07-30T07:52:42.039Z INFO webdriver: [DELETE] http://127.0.0.1:4723/session/386040499b8b838d1c16ca36aa4338bf
[0-0] FAILED in chrome - /test/specs/google_spec.js
```
I have situation when browser.getPageWeight() is working as intended, however 
I get error 
```
browser.getMetrics is not a function
```
I have the next package.json configuration: 
```
"devDependencies": {
    "@rpii/wdio-html-reporter": "^0.7.4",
    "@wdio/appium-service": "^5.11.4",
    "@wdio/cli": "^5.10.7",
    "@wdio/devtools-service": "^5.10.6",
    "@wdio/dot-reporter": "^5.11.7",
    "@wdio/firefox-profile-service": "^5.11.10",
    "@wdio/local-runner": "^5.11.10",
    "@wdio/mocha-framework": "^5.11.0",
    "@wdio/selenium-standalone-service": "^5.11.2",
    "@wdio/spec-reporter": "^5.11.7",
    "@wdio/sync": "^5.11.10",
    "appium": "^1.14.0",
    "chromedriver": "^75.1.0",
    "selenium-webdriver": "^4.0.0-alpha.4",
    "wdio-chromedriver-service": "^5.0.2",
    "wdio-json-reporter": "^1.3.1",
    "webdriverio": "^5.11.10"
  }
```

**Comment by rdpanek** [comment]
@christian-bromann any progress pls? Exist some fast solutions?

**Comment by christian-bromann** [comment]
> any progress pls? Exist some fast solutions?

I haven't looked into this at all which is why I labeled this thread this way.

**Comment by christian-bromann** [comment]
This is being fixed in #4416

**Comment by hisisirdas** [comment]
I think this issue is still exists if you try to get metrics inside loop :- 
@christian-bromann Can you please confirm if this is working, because we are trying to get metrics of around 100 urls in loop and getting error in auditor JS...
Same error I get using below code.
 (node:35024) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pageUrl' of undefined
    at new Auditor (D:\Tek Projects\Allegis-automation\allegis-performance-kpi-metrics-allure\node_modules\@wdio\devtools-service\build\auditor.js:57:26)


describe('PT demo', () => {
    before(() => {
      browser.enablePerformanceAudits()
    })
  for(var i =1 ; i <= 5; i++){
  
    it('page c', () => {
      browser.url('https://twitter.com')
      console.log(browser.getMetrics())
    })
}
    after(() => {
      browser.disablePerformanceAudits()
    })
  })

**Comment by pratimghosh76** [comment]
could any one help me on this, 

getting below error

[0-0] (node:90883) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'promise' of undefined
    at TraceGatherer.onLoadEventFired (/Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/@wdio/devtools-service/build/gatherer/trace.js:117:67)
    at /Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/puppeteer-core/lib/cjs/vendor/mitt/src/index.js:47:43)
    at CDPSession.emit (/Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (/Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:225:18)
    at Connection._onMessage (/Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:101:25)
    at WebSocket.<anonymous> (/Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WebSocketTransport.js:13:32)
    at WebSocket.onMessage (/Users/pxg8q0v/git/webdriverio-performance-testing/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:327:22)
[0-0] (node:90883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:90883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
