### ISSUE TITLE
Getting error `capabilities" is missing` but capabilities are defined

### ISSUE THREAD

**Issue by hunzai** [webdriverio/webdriverio#4097]
**Environment (please complete the following information):**
```
   "@wdio/cli": "^5.10.5",
    "@wdio/local-runner": "^5.10.5",
    "@wdio/mocha-framework": "^5.10.1",
    "@wdio/spec-reporter": "^5.9.3",
    "@wdio/sync": "^5.10.1",
    "chromedriver": "^75.0.0",
    "wdio-chromedriver-service": "^5.0.2"
```

**Config of WebdriverIO**
```
exports.config = {
    //
    // ====================
    // Runner Configuration
    // ====================
    //
    // WebdriverIO allows it to run your tests in arbitrary locations (e.g. locally or
    // on a remote machine).
    //runner: 'local',
    //
    // ==================
    // Specify Test Files
    // ==================
    // Define which test specs should run. The pattern is relative to the directory
    // from which `wdio` was called. Notice that, if you are calling `wdio` from an
    // NPM script (see https://docs.npmjs.com/cli/run-script) then the current working
    // directory is where your package.json resides, so `wdio` will be called from there.
    //
    specs: [
        './test/specs/**/*.js'
    ],
    // Patterns to exclude.
    exclude: [
        // 'path/to/excluded/files'
    ],
    //
    // ============
    // Capabilities
    // ============
    // Define your capabilities here. WebdriverIO can run multiple capabilities at the same
    // time. Depending on the number of capabilities, WebdriverIO launches several test
    // sessions. Within your capabilities you can overwrite the spec and exclude options in
    // order to group specific specs to a specific capability.
    //
    // First, you can define how many instances should be started at the same time. Let's
    // say you have 3 different capabilities (Chrome, Firefox, and Safari) and you have
    // set maxInstances to 1; wdio will spawn 3 processes. Therefore, if you have 10 spec
    // files and you set maxInstances to 10, all spec files will get tested at the same time
    // and 30 processes will get spawned. The property handles how many capabilities
    // from the same test should run tests.
    //
    maxInstances: 10,
    //
    // If you have trouble getting all important capabilities together, check out the
    // Sauce Labs platform configurator - a great tool to configure your capabilities:
    // https://docs.saucelabs.com/reference/platforms-configurator
    //
    capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
    //
    // ===================
    // Test Configurations
    // ===================
    // Define all options that are relevant for the WebdriverIO instance here
    //
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    logLevel: 'info',
    //
    // Set specific log levels per logger
    // loggers:
    // - webdriver, webdriverio
    // - @wdio/applitools-service, @wdio/browserstack-service, @wdio/devtools-service, @wdio/sauce-service
    // - @wdio/mocha-framework, @wdio/jasmine-framework
    // - @wdio/local-runner, @wdio/lambda-runner
    // - @wdio/sumologic-reporter
    // - @wdio/cli, @wdio/config, @wdio/sync, @wdio/utils
    // Level of logging verbosity: trace | debug | info | warn | error | silent
    // logLevels: {
        // webdriver: 'info',
        // '@wdio/applitools-service': 'info'
    // },
    //
    // If you only want to run your tests until a specific amount of tests have failed use
    // bail (default is 0 - don't bail, run all tests).
    bail: 0,
    //
    // Set a base URL in order to shorten url command calls. If your `url` parameter starts
    // with `/`, the base url gets prepended, not including the path portion of your baseUrl.
    // If your `url` parameter starts without a scheme or `/` (like `some/path`), the base url
    // gets prepended directly.
    baseUrl: 'http://localhost',
    //
    // Default timeout for all waitFor* commands.
    waitforTimeout: 10000,
    //
    // Default timeout in milliseconds for request
    // if Selenium Grid doesn't send response
    connectionRetryTimeout: 90000,
    //
    // Default request retries count
    connectionRetryCount: 3,
    //
    // Test runner services
    // Services take over a specific job you don't want to take care of. They enhance
    // your test setup with almost no effort. Unlike plugins, they don't add new
    // commands. Instead, they hook themselves up into the test process.
    services: ['chromedriver'],
    //
    // Framework you want to run your specs with.
    // The following are supported: Mocha, Jasmine, and Cucumber
    // see also: https://webdriver.io/docs/frameworks.html
    //
    // Make sure you have the wdio adapter package for the specific framework installed
    // before running any tests.
    framework: 'mocha',
    //
    // The number of times to retry the entire specfile when it fails as a whole
    // specFileRetries: 1,
    //
    // Test reporter for stdout.
    // The only one supported by default is 'dot'
    // see also: https://webdriver.io/docs/dot-reporter.html
    reporters: ['spec'],
    
    //
    // Options to be passed to Mocha.
    // See the full list at http://mochajs.org/
    mochaOpts: {
        ui: 'bdd',
        timeout: 60000
    },
    //
    // =====
    // Hooks
    // =====
    // WebdriverIO provides several hooks you can use to interfere with the test process in order to enhance
    // it and to build services around it. You can either apply a single function or an array of
    // methods to it. If one of them returns with a promise, WebdriverIO will wait until that promise got
    // resolved to continue.
    /**
     * Gets executed once before all workers get launched.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     */
    // onPrepare: function (config, capabilities) {
    // },
    /**
     * Gets executed just before initialising the webdriver session and test framework. It allows you
     * to manipulate configurations depending on the capability or spec.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // beforeSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed before test execution begins. At this point you can access to all global
     * variables like `browser`. It is the perfect place to define custom commands.
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that are to be run
     */
    // before: function (capabilities, specs) {
    // },
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    // beforeCommand: function (commandName, args) {
    // },
    
    /**
     * Hook that gets executed before the suite starts
     * @param {Object} suite suite details
     */
    // beforeSuite: function (suite) {
    // },
    /**
     * Function to be executed before a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // beforeTest: function (test) {
    // },
    /**
     * Hook that gets executed _before_ a hook within the suite starts (e.g. runs before calling
     * beforeEach in Mocha)
     */
    // beforeHook: function () {
    // },
    /**
     * Hook that gets executed _after_ a hook within the suite starts (e.g. runs after calling
     * afterEach in Mocha)
     */
    // afterHook: function () {
    // },
    /**
     * Function to be executed after a test (in Mocha/Jasmine) or a step (in Cucumber) starts.
     * @param {Object} test test details
     */
    // afterTest: function (test) {
    // },
    /**
     * Hook that gets executed after the suite has ended
     * @param {Object} suite suite details
     */
    // afterSuite: function (suite) {
    // },
    
    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
    // afterCommand: function (commandName, args, result, error) {
    // },
    /**
     * Gets executed after all tests are done. You still have access to all global variables from
     * the test.
     * @param {Number} result 0 - test pass, 1 - test fail
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // after: function (result, capabilities, specs) {
    // },
    /**
     * Gets executed right after terminating the webdriver session.
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {Array.<String>} specs List of spec file paths that ran
     */
    // afterSession: function (config, capabilities, specs) {
    // },
    /**
     * Gets executed after all workers got shut down and the process is about to exit. An error
     * thrown in the onComplete hook will result in the test run failing.
     * @param {Object} exitCode 0 - success, 1 - fail
     * @param {Object} config wdio configuration object
     * @param {Array.<Object>} capabilities list of capabilities details
     * @param {<Object>} results object containing test results
     */
    // onComplete: function(exitCode, config, capabilities, results) {
    // },
    /**
    * Gets executed when a refresh happens.
    * @param {String} oldSessionId session ID of the old session
    * @param {String} newSessionId session ID of the new session
    */
    //onReload: function(oldSessionId, newSessionId) {
    //}
}
``` 
**Describe the bug**
 Test with Chromedriver and local runner is not running

**To Reproduce**
1. Follow the instructions to setup on https://webdriver.io/docs/gettingstarted.html
2. Make sure you choose `local` runner 
3. Add sample test provided at https://webdriver.io/docs/gettingstarted.html
4. Run `./node_modules/.bin/wdio wdio.conf.js ` 

**Expected behavior**
It should run the test based on initial setup configuration. The official documentation should proved to be working which is provided at https://webdriver.io/docs/gettingstarted.html 

**Log**
```
 'Error: unhandled request\n    at getErrorFromResponseBody (/projects/sync-app-e2e/node_modules/webdriver/build/utils.js:343:12)\n    at Request._callback (/sync-app-e2e/node_modules/webdriver/build/request.js:121:64)\n    at Request.self.callback (/projects/sync-app-e2e/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at Request.<anonymous> (/projects/sync-app-e2e/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at Request.EventEmitter.emit (domain.js:441:20)\n    at IncomingMessage.<anonymous> (//projects/sync-app-e2e/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)' }
[0-0] 2019-06-18T11:00:57.183Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/projects/sync-app-e2e/node_modules/@wdio/runner/build/index.js:91:74)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by mgrybyk** [comment]
@hunzai please add `path: '/'` to config.

This will be fixed with https://github.com/webdriverio/webdriverio/pull/4089 in next release

**Comment by hunzai** [comment]
@mgrybyk I am still getting same error. It complains about capabilities being`TypeError: Cannot read property 'capabilities' of null`  . May be it has to do with runner ?

**Comment by hunzai** [comment]
I found the issue, capabilities should be defined as follow
```
  capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an in-house Selenium
        // grid with only 5 firefox instances available you can make sure that not more than
        // 5 instances get started at a time.
        // maxInstances: 5,
        //
        browserName: 'chrome',
        'goog:chromeOptions': {
        // to run chrome headless the following flags are required
        // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
         args: ['--disable-gpu'],
        }
        // If outputDir is provided WebdriverIO can capture driver session logs
        // it is possible to configure which logTypes to include/exclude.
        // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
        // excludeDriverLogs: ['bugreport', 'server'],
    }],
```

**Comment by christian-bromann** [comment]
This has been fixed and released. The getting started example is now working as described on the page.

**Comment by pratikvarma** [comment]
This is still not working for me. What versions of wdio should i be checking for?

**Comment by sabarishnarain** [comment]
@pratikvarma  5.11.10. Are you sure you have `path`: `/wd/hub` in your config ?

**Comment by dmytro-basiuk** [comment]
try to set a different port in wdio.conf file. 
Ex.
```
 path: '/',
 port: 9515
```
It worked for me
'cause I have one more wdio.config with another port set

**Comment by liangchr** [comment]
@hunzai I have the same problem. Tried everything on this thread but I can't get it to work with firefox. Did you end up figuring it out?

**Comment by jcollum-autodesk** [comment]
Same here in `  "webdriverio": "^5.11.13"`

My config (the relevant part?): 

```
 "maxInstances": 2,
 "capabilities": [
        {
            "browserName": "firefox",
            "moz:firefoxOptions": {
                "args": [
                    "-headless"
                ]
            }
        }
    ],
    "path": "/",
    "port": 9515
```

The error I get: 

```
0-1 worker error {
  name: 'Error',
  message: 'connect ECONNREFUSED 127.0.0.1:9515',
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:9515\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)'
}
[0-0] 2019-10-15T18:56:31.057Z ERROR @wdio/runner: Error: connect ECONNREFUSED 127.0.0.1:9515
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
2019-10-15T18:56:31.057Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/runner/build/index.js:68:74)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[0-1] 2019-10-15T18:56:31.057Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'capabilities' of null
    at Runner.run (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/@wdio/runner/build/index.js:68:74)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
0-0 worker error {
  name: 'Error',
  message: 'connect ECONNREFUSED 127.0.0.1:9515',
  stack: 'Error: connect ECONNREFUSED 127.0.0.1:9515\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)'
}
```

**Comment by mgrybyk** [comment]
how do you run geckodriver?

**Comment by jcollum-autodesk** [comment]
From the command line: `wdio wdio/firefox.conf.js`; not sure if that answers your question.

**Comment by mgrybyk** [comment]
No, what are you running on port 9515?

**Comment by jcollum-autodesk** [comment]
Nothing. I set that because of this comment: https://github.com/webdriverio/webdriverio/issues/4097#issuecomment-516822349

**Comment by mgrybyk** [comment]
So how do you expect it can work? You should run browser driver / selenium server so that wdio can connect to it.
You may use selenium standalone service for that

**Comment by mgrybyk** [comment]
You may start with https://webdriver.io/docs/gettingstarted.html
Choose selenium standalone and use that generated config as a starting point. Jdk have to be installed for selenium to work

**Comment by jcollum-autodesk** [comment]
Because if I set ` maxInstances: 10,` in chrome config, it works. 

But I set ` maxInstances: 2,` in firefox it fails. Is Firefox + WDIO only able to run >1 instance if you have Selenium Grid running?

**Comment by mgrybyk** [comment]
wdio supports whatever is supporter by geckodriver, so yes, you can run 1, 2 or 10 instances with firefox / chrome

**Comment by jcollum-autodesk** [comment]
OK I'm telling you that: 

`maxInstances: 1` - works

`maxInstances: 2` - fails

for `services: ['geckodriver'],`

The error is: 

``` 
> yarn test-firefox
yarn run v1.17.3
$ wdio wdio/firefox.conf.js

Execution of 32 spec files started at 2019-10-15T19:41:09.616Z

[0-0] RUNNING in firefox - /specs/desktop/admin/cacheAdmin.spec.js
[0-1] RUNNING in firefox - /specs/desktop/admin/contestAdmin.spec.js
[0-1] 2019-10-15T19:41:11.848Z ERROR webdriver: Request failed due to session not created: Session is already started
    at getErrorFromResponseBody (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
[0-1] 2019-10-15T19:41:11.850Z ERROR @wdio/runner: session not created: Session is already started
    at getErrorFromResponseBody (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/webdriver/build/utils.js:175:10)
    at Request._callback (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/webdriver/build/request.js:110:64)
    at Request.self.callback (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at Request.<anonymous> (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:471:20)
    at IncomingMessage.<anonymous> (/Users/collumj/Documents/work/ibleclient/e2e-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
``` 

So either the docs don't discuss how to get multiple instances of `geckodriver` running or there is a bug in the code.

**Comment by mgrybyk** [comment]
@jcollum-autodesk I have never used wdio-geckodriver-service, let me try

**Comment by mgrybyk** [comment]
@jcollum-autodesk you are right, geckodriver doesn't support that, see https://github.com/nightwatchjs/nightwatch/issues/1929

So, time to switch to selenium-standalone service and forget about chromedrivers and geckodrivers :)
it works perfectly with all drivers

**Comment by jcollum-autodesk** [comment]
ok that helps thanks for clarifying

**Comment by mgrybyk** [comment]
@jcollum-autodesk raised an issue to wdio-geckodriver-service https://github.com/RafalSkorka/wdio-geckodriver-service/issues/1

**Comment by giri-gonzai** [comment]
> I found the issue, capabilities should be defined as follow in case of 'chrome'.
> 
> ```
>   capabilities: [{
>         // maxInstances can get overwritten per capability. So if you have an in-house Selenium
>         // grid with only 5 firefox instances available you can make sure that not more than
>         // 5 instances get started at a time.
>         // maxInstances: 5,
>         //
>         browserName: 'chrome',
>         'goog:chromeOptions': {
>         // to run chrome headless the following flags are required
>         // (see https://developers.google.com/web/updates/2017/04/headless-chrome)
>          //args: ['--disable-gpu'],
>         }
>         // If outputDir is provided WebdriverIO can capture driver session logs
>         // it is possible to configure which logTypes to include/exclude.
>         // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
>         // excludeDriverLogs: ['bugreport', 'server'],
>     }],
> ```
> 
> Above is based on https://webdriver.io/docs/configurationfile.html.
> But `firefox`still is not working with
> 
> ```
> {
>         // maxInstances can get overwritten per capability. So if you have an in house Selenium
>         // grid with only 5 firefox instance available you can make sure that not more than
>         // 5 instance gets started at a time.
>         maxInstances: 5,
>         browserName: 'firefox',
>         specs: [
>             'test/ffOnly/*'
>         ],
>         "moz:firefoxOptions": {
>           // flag to activate Firefox headless mode (see https://github.com/mozilla/geckodriver/blob/master/README.md#firefox-capabilities for more details about moz:firefoxOptions)
>           // args: ['-headless']
>         },
>         // If outputDir is provided WebdriverIO can capture driver session logs
>         // it is possible to configure which logTypes to exclude.
>         // excludeDriverLogs: ['*'], // pass '*' to exclude all driver session logs
>         excludeDriverLogs: ['bugreport', 'server'],
>     }],
> ```

This worked for me, turns out the new versions of dependencies had some new changes to be included in the old wdio.config.js. Cheers for the link man.
