### ISSUE TITLE
Confusing SauceLabs creds with TestingBot creds

### ISSUE THREAD

**Issue by jaFerrazza** [webdriverio/webdriverio#4343]
**Describe your question with as much detail as possible**
When running my tests through the CI, webdriverIO is trying to authenticate me in TestingBot instead of SauceLabs as the service is set up to do. 

Error message:

`ERROR webdriver: Request failed due to Error: The key (username) and secret (XXXXXXXXXXXXXXXXXXXXXXXXXXXX1234) you used to authenticate are incorrect TestingBot credentials`

My wdio.config:

```
capabilities: [{
        deviceName: 'iPhone 8', //Name of the device or emulator
        platformVersion: '12.4',
        app: process.env.BUILDURL,
        testobject_api_key: process.env.TESTOBJECT_API_KEY,
        testobject_suite_name: 'iOS - Login',
        testobject_test_name: 'iOS Tests'

    }],
    services: ['sauce'],
    user: process.env.SCUSER,
    key: process.env.SCUSERKEY 

```

**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.10.2
 - **Mode:**WDIO Testrunner 
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 8.12.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Not apply, I'm using Appium
 - **Platform name and version:** Linux machine in the CI
 - **Additional wdio packages used (if applicable):** 

- "@wdio/appium-service": "^5.0.0",
    "@wdio/cli": "^5.10.9",
    "@wdio/local-runner": "^5.10.9",
    "@wdio/sauce-service": "^5.11.1",
    "@wdio/spec-reporter": "^5.9.3",
    "@wdio/sync": "^5.10.8",
    "eslint": "^5.16.0",
    "wdio-mocha-framework": "^0.6.4"

**Additional context**
This error only happens if I pass the user and key values to SauceLabs, if I don't my tests connect to SauceLab but they through a warning stating the following:
`Error: no auth mechanism defined`

**Comment by mgrybyk** [comment]
please use `@wdio/mocha-framework` instead of `wdio-mocha-framework` and avoid mixing v4 and v5 packages!

**Comment by mgrybyk** [comment]
Also, try deleting node_modules folder and your package-lock.json and installing packages from scratch.

**Comment by jaFerrazza** [comment]
Thanks for the suggestions on my dependencies, didn't realize I was using the wrong one. I just updated them.

I tried deleting both node_modules and package-lock.json and the error is still showing.

**Comment by christian-bromann** [comment]
@jaFerrazza then you use an invalid sauce access key. SauceLabs access keys are 36 characters long and the one for TestingBot 32.

**Comment by christian-bromann** [comment]
@jaFerrazza were you able to fix the issue?

**Comment by christian-bromann** [comment]
PR with a fix was merged and released.

**Comment by jaFerrazza** [comment]
For anyone encountering this issue, it was related to me using TestObject creds instead of SauceLabs. Once I changed the creds, the warning disappeared. Thanks for the quick hands on this, thank you guys.

**Comment by simonDominos** [comment]
@jaFerrazza @christian-bromann  I'm still getting this error when running tests on real devices in Saucelabs, when i log into Saucelabs and go to my account settings, my API key is 32 chars long not 36.  Am I getting the key from the wrong place?

**Comment by sulaysumaria** [comment]
I am also facing a similar issue. My access key from sauce labs is also 32 characters long. Any updates on this?

**Comment by Gar-ufo** [comment]
> I am also facing a similar issue. My access key from sauce labs is also 32 characters long. Any updates on this?
> 
> I find it weird that the cloud service is automatically detected based on the credentials. There should be some way to specify which cloud service to connect to.

try to regenerate your key, this worked for me, my first key missed the 4 dashes so wdio tried to connect to testing bot.
the key should look like this:
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Maybe you can try to add the dashes manually but i didn't test this.
