### ISSUE TITLE
set LOGLEVEL='silent', the console still output debug log

### ISSUE THREAD

**Issue by dtboy1995** [webdriverio/webdriverio#4433]
**Environment (please complete the following information):**
 - **WebdriverIO version: 5.11.7
 - **Mode:** [Standalone mode or WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:**  10.16.1
 - **NPM version:** 6.9.0
 - **Platform name and version:Android6.0

**Config of WebdriverIO**
```js
await wdio.remote({
            port: 4723,
            capabilities: {
                platformName: "Android",
                platformVersion: "6",
                deviceName: device,
                udid: device,
                ....
            },
            logLevel: "silent"
        })
```

**Describe the bug**
set LOGLEVEL='silent', the console still output debug log 2019-09-02T09:54:14.160Z DEBUG webdriverio: command click was called on an element

Why this happend? any help was very thanksful

**Comment by dtboy1995** [comment]
```log
PS D:\newcode\MinicapViewer\bin\Debug\script\feed> node .\2.js
2019-09-02T09:53:31.364Z DEBUG webdriverio: command click was called on an element ("//android.view.View[contains(@content-desc,"動態消息，")]") that wasn't found, waiting for it...
2019-09-02T09:53:33.079Z DEBUG webdriverio: command setValue was called on an element ("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText") that wasn't found, waiting for it...
2019-09-02T09:53:33.777Z DEBUG webdriverio: command setValue was called on an element ("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText") that wasn't found, waiting for it...
2019-09-02T09:53:34.003Z DEBUG webdriverio: command setValue was called on an element ("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText") that wasn't found, waiting for it...
2019-09-02T09:53:34.511Z DEBUG webdriverio: command setValue was called on an element ("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText") that wasn't found, waiting for it...
2019-09-02T09:53:36.512Z DEBUG webdriverio: command setValue was called on an element ("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText") that wasn't found, waiting for it...
2019-09-02T09:53:37.484Z DEBUG webdriverio: command setValue was called on an element ("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText") that wasn't found, waiting for it...
2019-09-02T09:53:37.957Z DEBUG webdriverio: command setValue was called on an element ("/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.ScrollView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.EditText") that wasn't found, waiting for it...
```

**Comment by dtboy1995** [comment]
I found that when clicking on an empty element or setting text, even if the log level was set to silence, the console would have related logs.

**Comment by dtboy1995** [comment]
is there any help?

**Comment by mgrybyk** [comment]
What kind of help do you expect? If you have any ideas how to fix the issue feel free to raise PR!

**Comment by dtboy1995** [comment]
@mgrybyk, This behavior is clearly a bug.

**Comment by mgrybyk** [comment]
Can you provide with reproducible example?

**Comment by dtboy1995** [comment]
@mgrybyk, thanks for reply
I can only tell you first, the code of the extra log will appear under the silent log level.
```js
const element = await driver.$('//android.widget.Button[contains(@content-desc,"Some Flag")]')
element.click() // but this element is not found
```
I will prepare an example that can be reproduced as soon as possible, wait a moment.

**Comment by theduykh** [comment]
If you simply don't want any logs to show on the console, you can add one more config
  ```outputDir: './report/'```
All logs will be stored in the report folder.

**Comment by dtboy1995** [comment]
@theduykh thanks a lot , i'll try it

**Comment by mhio** [comment]
So the reproduction is
```
async function test(){
  try {
    const browser = await require('webdriverio').remote({ capabilities: {}, logLevel: 'silent' })
    browser.url('/test')
  }
  catch (e) {}
}
test()
```
```
$ node test/int/logging-bug.js 
2019-09-23T08:55:10.354Z INFO webdriverio: Initiate new session using the webdriver protocol
```

Or setting `logLevel` to `error`/`warn`

**Comment by mhio** [comment]
Actually in my case I think it's `logLevels` that need to be set for webdriver, but that doesn't seem to work either.
```
async function test(){
  try {
    const browser = await require('webdriverio').remote({ capabilities: {}, logLevel: 'silent', logLevels: { webdriver: 'silent' }})
    browser.url('/test')
  }
  catch (e) {}
}
test()
```

**Comment by christian-bromann** [comment]
Fixed in #4527

**Comment by ianwalter** [comment]
5.13.2 doesn't seem to fix this for me. Could be on my end I guess, but just wanted to give a heads up.

**Comment by christian-bromann** [comment]
The patch was not released yet

**Comment by ianwalter** [comment]
> The patch was not released yet

Ah sorry for the noise, I was just looking at the "5 days ago".
