### ISSUE TITLE
@wdio/cucumber-framework: Issues with multiple tables in Scenarios

### ISSUE THREAD

**Issue by nextlevelbeard** [webdriverio/webdriverio#4478]
**Environment:**
 - **WebdriverIO version:** 5.15.0

**Config of WebdriverIO**
Any + steps to reproduce

~**Issue 1**: Cannot use row data in the Scenario name when the Scenario has multiple tables. Only the first example is printed by the spec reporter and an error is thrown, test/Scenario still runs.~ SOLVED
**Issue 2**: Trying to execute a Scenario that has multiple tables when the Examples section has tags will throw an error if that tag is used in a tagged hook.

**To Reproduce Issue 1**: 
feature file:
```
@tag
Feature: Foo
  foobar 1
  foobar 2
  foobar 3

  Background:
    Given stub

  @tag
  Scenario Outline: Logged in with user <userId>
    Given stub
    Then User <userId> with <password> is logged in
      Examples:
        | userId    | password |
        | 345       | pw3      |

      Examples:
        | userId    | password |
        | 456       | pw4      |
```
Steps:
```js
Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    console.log(userId, password)
})

Given('stub', function () {
    console.log('stub')
})
```

**To Reproduce Issue 2**: 
feature file:
```
@tag
Feature: Foo
    foobar 1
    foobar 2
    foobar 3

  Backgroud:
      Given stub

  @tag
  Scenario Outline: Bar
    Given stub
    Then User <userId> with <password> is logged in
      Examples:
        | userId    | password |
        | 345       | pw3      |

      @tag2
      Examples:
        | userId    | password |
        | 456       | pw4      |
```
Steps:
```js
const { Given, Before } = require("cucumber");

// The tag here is important, to reproduce the issue, it has to be an used tag
Before("@tag2", function() {
  this.user = 'foobar';
});

Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    console.log(userId, password)
})

Given('stub', function () {
    console.log('stub')
})
```

**Expected behavior**
The tests should pass and not error, the spec reporter should present both Scenarios.

**Log**
**Issue 1 (console)**:
```js
0-0 worker error {
  name: 'TypeError',
  message: "Cannot read property 'complete' of undefined",
  stack: "TypeError: Cannot read property 'complete' of undefined\n    at " +
    'SpecReporter.<anonymous> ' +
    '(C:\\Users\\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\reporter\\build\\index.js:143:17)\n' +
   
```

**Issue 2 (console)**:
```js
0-0 worker error {
  name: 'TypeError',
  message: "Cannot read property 'type' of undefined",
  stack: "TypeError: Cannot read property 'type' of undefined\n    at " +
    'getStepFromFeature ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\build\\utils.js:168:18)\n' +
    '    at CucumberEventListener.onTestStepStarted ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\build\\cucumberEventListener.js:60:48)\n' +
    '    at EventEmitter.emit (events.js:200:13)\n    at EventEmitter.emit ' +
    '(domain.js:471:20)\n    at TestCaseRunner.emit ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:85:27)\n' +
    '    at ' +
    'C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:177:13\n' +
    '    at Generator.next (<anonymous>)\n    at asyncGeneratorStep ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:22:103)\n' +
    '    at _next ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:194)\n' +
    '    at ' +
    'C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:364\n' +
    '    at new Promise (<anonymous>)\n    at ' +
    'C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:97\n' +
    '    at TestCaseRunner.aroundTestStep ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:201:7)\n' +
    '    at ' +
    'C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:253:24\n' +
    '    at Generator.next (<anonymous>)\n    at asyncGeneratorStep ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:22:103)\n' +
    '    at _next ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:194)\n' +
    '    at ' +
    'C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:364\n' +
    '    at new Promise (<anonymous>)\n    at ' +
    'C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:24:97\n' +
    '    at ' +
    'C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\@wdio\\cucumber-framework\\node_modules\\cucumber\\lib\\runtime\\test_case_runner.js:257:23\n' +
    '    at tryCatcher ' +
    '(C:\\Users\[REDACTED]\\repos\\wdio-e2e\\node_modules\\bluebird\\js\\release\\util.js:16:23)'  
```

**Comment by christian-bromann** [comment]
This issue was fixed and released. Closing.

**Comment by nextlevelbeard** [comment]
@christian-bromann I can still reproduce these two issues with latest version 5.15.0.
PR #4290 fixed a similar but different ultimately issue.
Could someone please try to reproduce and if confirmed, reopen this issue?

**Comment by mgrybyk** [comment]
regarding the case
```
// The tag here is important, to reproduce the issue, it has to be an used tag
Before("@tag2", function () {
    this.user = 'foobar';
});
```

I have no idea what is the expected result and how it works all together.

**Comment by mgrybyk** [comment]
Issue 1 confirmed

**Comment by nextlevelbeard** [comment]
If you have multiple example tables in a Scenario Outline, each table is able to have its own separate tags.
In the scenario below, the second table has the tag "tag2".

```gherkin
  @tag
  Scenario Outline: Bar
    Given stub
    Then User <userId> with <password> is logged in
      Examples:
        | userId    | password |
        | 345       | pw3      |

      @tag2
      Examples:
        | userId    | password |
        | 456       | pw4      |
```

The issue happens when you implement a tagged hook that includes the tag (in this case, a before hook).
If you do not define the tagged hook, the issue does not occur.

So if you define the tagged hook like so:
```js
Before("@tag2", function () {
    console.log("Hello before tag2 scenario");
});
```

What's expected:
- The scenario should run for example 1
- Run the hook, in this case, a log to console: Hello before tag2 scenario
- The scenario runs again for example 2
- spec-reporter should print both scenarios (example 1 and example 2):

Bar
	✓ Given stub
    	✓ Then User 345 with pw3 is logged in
Bar
	✓ Given stub
    	✓ Then User 456 with pw4 is logged in

**Comment by mgrybyk** [comment]
@nextlevelbeard is it possible to have something like
```
Before("@tag2", function () {
    console.log("Hello before tag2 scenario");
});
```
for Given/Then ?

**Comment by nextlevelbeard** [comment]
Don't think that is possible according to the docs, Before/After Step is not possible.
It is possible to have general Before After each scenario tho.
I think [here](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md#tagged-hooks) you'll find all possible hooks.

**Comment by mgrybyk** [comment]
@nextlevelbeard found how to fix issues 2

**Comment by mgrybyk** [comment]
issue gonna be fixed with the PR, we may proceed discussion there if needed

**Comment by mgrybyk** [comment]
Given both issues are fixed and having feature file like this:
```
@tag
Feature: Foo
  foobar 1
  foobar 2
  foobar 3

  Background:
    Given stub

  @tag
  Scenario Outline: Logged in with user <userId>
    Given stub
    Then User <userId> with <password> is logged in
      Examples:
        | userId    | password |
        | 345       | pw3      |

      @tag2
      Examples:
        | userId    | password |
        | 456       | pw4      |

      Examples:
        | userId    | password |
        | 567       | pw5     |
```

with step definitions like this:
```
import { Given, After, AfterAll, BeforeAll, Before } from "cucumber"

BeforeAll(() => {
    console.log("BeforeAll")
})

AfterAll(() => {
    console.log("AfterAll")
})

After(() => {
    console.log("After each")
})

Given(/^User (.*) with (.*) is logged in$/, { wrapperOptions: { retry: 2 } }, function (userId, password) {
    console.log(userId, password)
})

Given('stub', function () {
    console.log('stub')
})

// The tag here is important, to reproduce the issue, it has to be an used tag
Before("@tag2", function () {
    this.user = 'foobar';
    console.log('tagged Before each hook')
});
```

I'm getting the following console output:
```
[0-0] RUNNING in chrome - /test/specs/a.feature
[0-0] BeforeAll
[0-0] stub
[0-0] stub
[0-0] 345 pw3
[0-0] After each
[0-0] tagged Before each hook
[0-0] stub
[0-0] stub
[0-0] 456 pw4
[0-0] After each
[0-0] stub
[0-0] stub
[0-0] 567 pw5
[0-0] After each
[0-0] AfterAll
[0-0] PASSED in chrome - /test/specs/a.feature
```
and spec reporter output looks like this
![image](https://user-images.githubusercontent.com/25589559/66838668-5cd97000-ef65-11e9-9990-ec1b2c4735f4.png)

@nextlevelbeard may you please confirm it works as expected?
