### ISSUE TITLE
Individual test runs given with --spec fail if the path includes a space (VSCode)

### ISSUE THREAD

**Issue by ccurtis0** [webdriverio/webdriverio#4810]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.9
 - **Mode:** WDIO Testrunner (?)
 - **If WDIO Testrunner, running sync/async:** sync ?
 - **Node.js version:** 12.1.0
 - **NPM version:** 6.13.1
 - **Browser name and version:** Chrome 78
 - **Platform name and version:** Windows 7
 - **Additional wdio packages used (if applicable):**
    "@babel/cli": "^7.7.4",
    "@babel/core": "^7.7.4",
    "@babel/preset-env": "^7.7.4",
    "@babel/register": "^7.7.4",
    "@wdio/cli": "^5.16.9",
    "@wdio/local-runner": "^5.16.9",
    "@wdio/mocha-framework": "^5.16.5",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.9",
    "babel-register": "^6.26.0",
    "chromedriver": "^78.0.1",
    "wdio-chromedriver-service": "^5.0.2"

**Config of WebdriverIO**
Should be N/A, basically followed the quickstart.

**Describe the bug**
Configured Visual Studio Code per online documentation. Set up test configurations for "Run All Tests" and "Run Selected Spec". Running all tests works fine, but running individual tests fails with the error:

    @wdio/local-runner: Failed launching test session: TypeError: args[0].endsWith is not a function

From the VS Code terminal, I am able to copy-paste the commands and get the same behavior. I ran the individual tests using a relative path and it succeeded. I then added "..\\\<parent>" to the path until the test no longer ran. The test began to fail when the parent directory name was "Unit tests".

The problem appears to be that passing paths containing spaces to WDIO via the "--spec" parameter causes it to fail.

**To Reproduce**
- Move your test suite to a folder containing a space somewhere in the path
- Attempt to run an individual test via the --spec argument, including the embedded space.

Example:

    node node_modules\@wdio\cli\bin\wdio.js wdio.conf.js --spec "..\..\Unit tests\webdriverio\test\specs\map.spec.js"

**Expected behavior**
I expect to be able to run individual tests from within VS Code via --spec regardless of the path that the test is running from, as I am able to when I run all tests.

**Log**
```
node node_modules\@wdio\cli\bin\wdio.js wdio.conf.js --spec "c:\...\Unit tests\webdriverio\test\specs\map.spec.js"
[...]

Execution of 1 spec files started at 2019-11-25T15:23:11.607Z

[0-0] RUNNING in chrome - c:\...\Unit tests\webdriverio\test\specs\map.spec.js

DevTools listening on ws://127.0.0.1:33968/devtools/browser/7442ea1c-a521-4843-a15d-5cd9ec7c14a6
[0-0] 2019-11-25T15:23:16.162Z ERROR @wdio/local-runner: Failed launching test session: TypeError: args[0].endsWith is not a function
    at C:\...\Unit tests\webdriverio\node_modules\@wdio\sync\node_modules\@wdio\logger\build\node.js:63:62
    at Array.filter (<anonymous>)
    at Logger.error (C:\...\Unit tests\webdriverio\node_modules\@wdio\sync\node_modules\@wdio\logger\build\node.js:63:42)
    at Runner.run (C:\...\Unit tests\webdriverio\node_modules\@wdio\runner\build\index.js:157:11)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
[0-0] FAILED in chrome - c:\...\Unit tests\webdriverio\test\specs\map.spec.js
```

**Additional context**
Here are the relevant sections from the VS Code launch.json file:

```
        {
            "name": "run all tests (works)",
            "type": "node",
            "request": "launch",
            "args": ["wdio.conf.js"],
            "cwd": "${workspaceFolder}",
            "autoAttachChildProcesses": true,
            "program": "${workspaceRoot}/node_modules/@wdio/cli/bin/wdio.js",
            "console": "integratedTerminal"
        },
        {
            "name": "run select spec (fails mocha:babel)",
            "type": "node",
            "request": "launch",
            "args": ["wdio.conf.js", "--spec", "${file}"],
            "cwd": "${workspaceFolder}",
            "autoAttachChildProcesses": true,
            "program": "${workspaceRoot}/node_modules/@wdio/cli/bin/wdio.js",
            "console": "integratedTerminal"
        },
```

**Workaround**
Note that a workaround exists for VS Code specifically by modifying the run-one-spec configuration block from:

    "args": ["wdio.conf.js", "--spec", "${file}"],

to:

    "args": ["wdio.conf.js", "--spec", "${relativeFile}"],

Other execution environments would have to be modified per their own configurations, assuming that the test suites being created do not also contain spaces in their path names.

**Comment by ccurtis0** [comment]
Potential point of confusion:

I upgraded the software while I was writing this. This is the upgrade that happened:

 @babel/cli             ^7.7.0  →     ^7.7.4
 @babel/core            ^7.7.2  →     ^7.7.4
 @babel/preset-env      ^7.7.1  →     ^7.7.4
 @babel/register        ^7.7.0  →     ^7.7.4
 @types/node         ^12.12.11  →  ^12.12.12
 @wdio/cli             ^5.16.7  →    ^5.16.9
 @wdio/local-runner    ^5.16.7  →    ^5.16.9
 @wdio/sync            ^5.16.5  →    ^5.16.9

The description above is accurate for the version numbers on the left side. After upgrading the packages I get a different error:

```
[0-0] 2019-11-25T16:39:14.783Z ERROR @wdio/runner: C:\...\Unit tests\webdriverio\test\specs\map.spec.js:1
import MapPage from '../pageobjects/map.page'; //
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Module._compile (C:\...\Unit tests\webdriverio\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (C:\...\Unit tests\webdriverio\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at C:\...\Unit tests\webdriverio\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
[0-0] Error: Unexpected identifier
[0-0] FAILED in chrome - C:\...\Unit tests\webdriverio\test\specs\map.spec.js
```

Why mocha requires babel causes me no end of confusion, but the symptom is the same: With the space in the path name the individual unit test fails, but a relative path without a space works.

```
C:\...\Unit tests\webdriverio>node node_modules\@wdio\cli\bin\wdio.js wdio.conf.js --spec "..\webdriverio\test\specs\map.spec.js"
[...]

[0-0] RUNNING in chrome - C:\...\Unit tests\webdriverio\test\specs\map.spec.js

DevTools listening on ws://127.0.0.1:41934/devtools/browser/2b3c74ce-04d9-419c-b965-0e4b8e223b35
[30696:32956:1125/114826.240:ERROR:gles2_cmd_decoder.cc(3541)] ContextResult::kFatalFailure: fail_if_major_perf_caveat + swiftshader
[30696:32956:1125/114826.247:ERROR:gles2_cmd_decoder.cc(3541)] ContextResult::kFatalFailure: fail_if_major_perf_caveat + swiftshader
[0-0] PASSED in chrome - C:\...\Unit tests\webdriverio\test\specs\map.spec.js

 "spec" Reporter:
------------------------------------------------------------------
[...]
Spec Files:      1 passed, 1 total (100% completed) in 00:00:06
```

**Comment by christian-bromann** [comment]
Duplicate of #4785. Would you mind deleting `node_modules` and `package-lock.json` , updating all WebdriverIO dependencies and re-install them?

**Comment by christian-bromann** [comment]
We merged the PR and will release it soon.

**Comment by ccurtis0** [comment]
Thanks, but I'm having the same problem. I upgraded these components:
```
 @types/node            ^12.12.12  →  ^12.12.14
 @wdio/cli                ^5.16.9  →   ^5.16.10
 @wdio/local-runner       ^5.16.9  →   ^5.16.10
 @wdio/mocha-framework    ^5.16.5  →   ^5.16.10
 @wdio/sync               ^5.16.9  →   ^5.16.10
```

Then I removed and reinstalled all off node_modules, but I still get the error about an Unexpected Identifier when I run the `--spec ${file}` instead of `--spec ${relativeFile}` configuration. Again, with relative paths there are no errors.

```
[0-0] 2019-11-26T22:57:38.050Z ERROR @wdio/runner: c:\...\Unit tests\webdriverio\test\specs\map.spec.js:1
import MapPage from '../pageobjects/map.page'; //
       ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Module._compile (C:\...\Unit tests\webdriverio\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (C:\...\Unit tests\webdriverio\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at C:\...\Unit tests\webdriverio\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
[0-0] Error: Unexpected identifier
```

**Comment by christian-bromann** [comment]
This is different from the issue posted originally and looks like that Babel is not set up properly. Please have a look here: https://webdriver.io/docs/babel.html

**Comment by ccurtis0** [comment]
Thanks again. I still don't understand though.

I'm using Mocha and the setup requires 'common.js', which doesn't exist. This file isn't listed as part of the 'Page-Object' pattern I'm following and with that file omitted it continues to fail with the same error above. In the wdio.conf I've tried configuring mocha with both the before() hook and via mochaOpts,

https://webdriver.io/docs/pageobjects.html
https://webdriver.io/docs/babel.html
https://webdriver.io/docs/frameworks.html

With the before() hook shown on the framework page, I added a console.log after the require for \@babel/register, and that **does** get displayed when I run the failing test.

Perhaps it's babel that has a problem with spaces in the names, but using relative paths works for now.
