### ISSUE TITLE
@wdio/repl: No matching version found for @wdio/repl@5.16.11

### ISSUE THREAD

**Issue by meruga92** [webdriverio/webdriverio#4842]
`npm install webdriverio` giving above error

**Environment (please complete the following information):**

- Node: 10.16.3
-npm: 6.9.0

package.json

**Describe the bug**
For the latest webdriverio when i do npm install it is erroring out

**To Reproduce**
nom install webdriverio

**Log**
https://gist.github.com/meruga92/440ca11915a56eebd9ca360bdf49015e

**Comment by christian-bromann** [comment]
> @wdio/repl: No matching version found for @wdio/repl@5.16.11

This was probably a race condition as we just did a release. This version has been pushed to NPM and an install should work now. I verified this.

**Comment by meruga92** [comment]
I am still getting this error when i do npm install webdriverio

**Comment by christian-bromann** [comment]
The NPM package is published and should be downloadable.

**Comment by meruga92** [comment]
thank you it worked now
