### ISSUE TITLE
JavaScript error on element.isClickable() and element.waitForClickable() in IE11

### ISSUE THREAD

**Issue by MalteHer** [webdriverio/webdriverio#5043]
Hey everyone,
I am having an issue with IE11 and webdriverIO used with Browserstack. isClickable() and waitForClickable() is casing a JavaScript error and so far I was unable to find any related topics on this.
I use "webdriverio": "^5.18.6" in sync with BrowserStack browsers. Unfortunately the error log doesn't actually describe what the problem is, but if I take those methods out, it works.

`[0-0] 2020-02-19T14:14:34.693Z ERROR webdriver: Request failed due to Error: JavaScript error
    at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (node_modules/webdriver/build/request.js:111:64)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)

[0-0] 2020-02-19T14:14:36.189Z ERROR webdriver: Request failed due to Error: JavaScript error
    at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (node_modules/webdriver/build/request.js:111:64)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)

[0-0] 2020-02-19T14:14:37.282Z ERROR webdriver: Request failed due to Error: JavaScript error
    at getErrorFromResponseBody (node_modules/webdriver/build/utils.js:124:10)
    at Request._callback (node_modules/webdriver/build/request.js:111:64)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)`

**Browserstack Logfile**
@christian-bromann I provided logs from Browserstack now
[logs.txt](https://github.com/webdriverio/webdriverio/files/4225576/logs.txt)

**Comment by christian-bromann** [comment]
Can you provide logs from BrowserStack?

**Comment by MalteHer** [comment]
@christian-bromann I added the logs from Browserstack to my previous post now.

**Comment by christian-bromann** [comment]
@MalteHer can you provide a minimal reproducible example?

**Comment by MalteHer** [comment]
@christian-bromann I attached a dummy project. There is still some stuff in there that in uneccessary but if you run add your browserstack credentials in the .env file and run npm install and npm run test it should show you the error.
[test.zip](https://github.com/webdriverio/webdriverio/files/4245948/test.zip)

**Comment by maxmellen** [comment]
@christian-bromann I can confirm `isClickable` doesn't work on IE11. It seems the javascript it generates to be run on the browser isn't compatible with IE11.

Sauce Labs logs when running `isClickable`:

> Command:
> ```
> POST execute/sync
> ```
> 
> Parameters:
> ```
> { "args": [ { "element-6066-11e4-a52e-4f735466cecf": "c353bf98-2b65-440d-9565-cfaed8f8e561", "ELEMENT": "c353bf98-2b65-440d-9565-cfaed8f8e561" } ], "script": "return (function isElementClickable(elem) {\n if (!elem.getBoundingClientRect || !elem.scrollIntoView || !elem.contains || !elem.getClientRects || !document.elementFromPoint) {\n return false;\n }\n\n const isOldEdge = !!window.StyleMedia;\n const scrollIntoViewFullSupport = !(window.safari || isOldEdge);\n\n function getOverlappingElement(elem, context = document) {\n const elemDimension = elem.getBoundingClientRect();\n const x = elemDimension.left + elem.clientWidth / 2;\n const y = elemDimension.top + elem.clientHeight / 2;\n return context.elementFromPoint(x, y);\n }\n\n function getOverlappingRects(elem, context = document) {\n const elems = [];\n const rects = elem.getClientRects();\n const rect = rects[0];\n const x = rect.left + rect.width / 2;\n const y = rect.top + rect.height / 2;\n elems.push(context.elementFromPoint(x, y));\n return elems;\n }\n\n function getOverlappingElements(elem, context) {\n return [getOverlappingElement(elem, context), ...getOverlappingRects(elem, context)];\n }\n\n function nodeContains(elem, otherNode) {\n if (isOldEdge) {\n let tmpElement = otherNode;\n\n while (tmpElement) {\n if (tmpElement === elem) {\n return true;\n }\n\n tmpElement = tmpElement.parentNode;\n\n if (tmpElement && tmpElement.nodeType === 11 && tmpElement.host) {\n tmpElement = tmpElement.host;\n }\n }\n\n return false;\n }\n\n return elem.contains(otherNode);\n }\n\n function isOverlappingElementMatch(elementsFromPoint, elem) {\n if (elementsFromPoint.some(elementFromPoint => elementFromPoint === elem || nodeContains(elem, elementFromPoint))) {\n return true;\n }\n\n let elemsWithShadowRoot = [...new Set(elementsFromPoint)];\n elemsWithShadowRoot = elemsWithShadowRoot.filter(x => x && x.shadowRoot && x.shadowRoot.elementFromPoint);\n let shadowElementsFromPoint = [];\n\n for (let shadowElement of elemsWithShadowRoot) {\n shadowElementsFromPoint.push(...getOverlappingElements(elem, shadowElement.shadowRoot));\n }\n\n shadowElementsFromPoint = [...new Set(shadowElementsFromPoint)];\n shadowElementsFromPoint = shadowElementsFromPoint.filter(x => !elementsFromPoint.includes(x));\n\n if (shadowElementsFromPoint.length === 0) {\n return false;\n }\n\n return isOverlappingElementMatch(shadowElementsFromPoint, elem);\n }\n\n function isElementInViewport(elem) {\n if (!elem.getBoundingClientRect) {\n return false;\n }\n\n const rect = elem.getBoundingClientRect();\n const windowHeight = window.innerHeight || document.documentElement.clientHeight;\n const windowWidth = window.innerWidth || document.documentElement.clientWidth;\n const vertInView = rect.top <= windowHeight && rect.top + rect.height > 0;\n const horInView = rect.left <= windowWidth && rect.left + rect.width > 0;\n return vertInView && horInView;\n }\n\n function isClickable(elem) {\n return isElementInViewport(elem) && elem.disabled !== true && isOverlappingElementMatch(getOverlappingElements(elem), elem);\n }\n\n if (!isClickable(elem)) {\n elem.scrollIntoView(scrollIntoViewFullSupport ? {\n block: 'nearest',\n inline: 'nearest'\n } : false);\n\n if (!isClickable(elem)) {\n elem.scrollIntoView(scrollIntoViewFullSupport ? {\n block: 'center',\n inline: 'center'\n } : true);\n return isClickable(elem);\n }\n }\n\n return true;\n}).apply(null, arguments)" }
> ```
> 
> Response:
> ```
> HTTP Status: 500
> { "stacktrace": "", "message": "Error executing JavaScript", "data": null, "error": "javascript error" }
> ```

**Comment by christian-bromann** [comment]
It seems that the `newWindow` script is also failing on IE11.
https://app.saucelabs.com/tests/3a233521be5f44629462c4984b89b340#7

**Comment by christian-bromann** [comment]
Fixed in #5279

**Comment by ArminazK** [comment]
This is still reproducible in wdio 6.6.7
'waitUntil condition failed with the following reason: Error executing JavaScript' on elemen.waitForLClickable

**Comment by Bartleonid** [comment]
It is reproducible for me on "webdriverio": "^7.7.3" and "@wdio/browserstack-service": "^7.8.0" using Chrome 91 and "chromedriver": "^91.0.0".
`1
POST /session/e51c49871452c980ba1736815225b347378eb087/execute/sync
2
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
3
System info: host: '10-144-162-103', ip: '10.144.162.103', os.name: 'windows', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_181'
4
Driver info: driver.version: unknown`


`return (function isElementDisplayed(element) {
    function nodeIsElement(node) {
        if (!node) {
            return false;
        }
        switch (node.nodeType) {
            case Node.ELEMENT_NODE:
            case Node.DOCUMENT_NODE:
            case Node.DOCUMENT_FRAGMENT_NODE:
                return true;
            default:
                return false;
        }
    }
    function parentElementForElement(element) {
        if (!element) {
            return null;
        }
        return enclosingNodeOrSelfMatchingPredicate(element.parentNode, nodeIsElement);
    }
    function enclosingNodeOrSelfMatchingPredicate(targetNode, predicate) {
        for (let node = targetNode; node && node !== targetNode.ownerDocument; node = node.parentNode)
            if (predicate(node)) {
                return node;
            }
        return null;
    }
    function enclosingElementOrSelfMatchingPredicate(targetElement, predicate) {
        for (let element = targetElement; element && element !== targetElement.ownerDocument; element = parentElementForElement(element))
            if (predicate(element)) {
                return element;
            }
        return null;
    }
    function cascadedStylePropertyForElement(element, property) {
        if (!element || !property) {
            return null;
        }
        // if document-fragment, skip it and use element.host instead. This happens
        // when the element is inside a shadow root.
        // window.getComputedStyle errors on document-fragment.
        if (element instanceof DocumentFragment) {
            element = element.host;
        }
        let computedStyle = window.getComputedStyle(element);
        let computedStyleProperty = computedStyle.getPropertyValue(property);
        if (computedStyleProperty && computedStyleProperty !== 'inherit') {
            return computedStyleProperty;
        }
        // Ideally getPropertyValue would return the 'used' or 'actual' value, but
        // it doesn't for legacy reasons. So we need to do our own poor man's cascade.
        // Fall back to the first non-'inherit' value found in an ancestor.
        // In any case, getPropertyValue will not return 'initial'.
        // FIXME: will this incorrectly inherit non-inheritable CSS properties?
        // I think all important non-inheritable properties (width, height, etc.)
        // for our purposes here are specially resolved, so this may not be an issue.
        // Specification is here: https://drafts.csswg.org/cssom/#resolved-values
        let parentElement = parentElementForElement(element);
        return cascadedStylePropertyForElement(parentElement, property);
    }
    function elementSubtreeHasNonZeroDimensions(element) {
        let boundingBox = element.getBoundingClientRect();
        if (boundingBox.width > 0 && boundingBox.height > 0) {
            return true;
        }
        // Paths can have a zero width or height. Treat them as shown if the stroke width is positive.
        if (element.tagName.toUpperCase() === 'PATH' && boundingBox.width + boundingBox.height > 0) {
            let strokeWidth = cascadedStylePropertyForElement(element, 'stroke-width');
            return !!strokeWidth && (parseInt(strokeWidth, 10) > 0);
        }
        let cascadedOverflow = cascadedStylePropertyForElement(element, 'overflow');
        if (cascadedOverflow === 'hidden') {
            return false;
        }
        // If the container's overflow is not hidden and it has zero size, consider the
        // container to have non-zero dimensions if a child node has non-zero dimensions.
        return Array.from(element.childNodes).some((childNode) => {
            if (childNode.nodeType === Node.TEXT_NODE) {
                return true;
            }
            if (nodeIsElement(childNode)) {
                return elementSubtreeHasNonZeroDimensions(childNode);
            }
            return false;
        });
    }
    function elementOverflowsContainer(element) {
        let cascadedOverflow = cascadedStylePropertyForElement(element, 'overflow');
        if (cascadedOverflow !== 'hidden') {
            return false;
        }
        // FIXME: this needs to take into account the scroll position of the element,
        // the display modes of it and its ancestors, and the container it overflows.
        // See Selenium's bot.dom.getOverflowState atom for an exhaustive list of edge cases.
        return true;
    }
    function isElementSubtreeHiddenByOverflow(element) {
        if (!element) {
            return false;
        }
        if (!elementOverflowsContainer(element)) {
            return false;
        }
        if (!element.childNodes.length) {
            return false;
        }
        // This element's subtree is hidden by overflow if all child subtrees are as well.
        return Array.from(element.childNodes).every((childNode) => {
            // Returns true if the child node is overflowed or otherwise hidden.
            // Base case: not an element, has zero size, scrolled out, or doesn't overflow container.
            // Visibility of text nodes is controlled by parent
            if (childNode.nodeType === Node.TEXT_NODE) {
                return false;
            }
            if (!nodeIsElement(childNode)) {
                return true;
            }
            if (!elementSubtreeHasNonZeroDimensions(childNode)) {
                return true;
            }
            // Recurse.
            return isElementSubtreeHiddenByOverflow(childNode);
        });
    }
    // walk up the tree testing for a shadow root
    function isElementInsideShadowRoot(element) {
        if (!element) {
            return false;
        }
        if (element.parentNode && element.parentNode.host) {
            return true;
        }
        return isElementInsideShadowRoot(element.parentNode);
    }
    // This is a partial reimplementation of Selenium's "element is displayed" algorithm.
    // When the W3C specification's algorithm stabilizes, we should implement that.
    // If this command is misdirected to the wrong document (and is NOT inside a shadow root), treat it as not shown.
    if (!isElementInsideShadowRoot(element) && !document.contains(element)) {
        return false;
    }
    // Special cases for specific tag names.
    switch (element.tagName.toUpperCase()) {
        case 'BODY':
            return true;
        case 'SCRIPT':
        case 'NOSCRIPT':
            return false;
        case 'OPTGROUP':
        case 'OPTION': {
            // Option/optgroup are considered shown if the containing <select> is shown.
            let enclosingSelectElement = enclosingNodeOrSelfMatchingPredicate(element, (e) => e.tagName.toUpperCase() === 'SELECT');
            return isElementDisplayed(enclosingSelectElement);
        }
        case 'INPUT':
            // <input type="hidden"> is considered not shown.
            if (element.type === 'hidden') {
                return false;
            }
            break;
        // case 'MAP':
        // FIXME: Selenium has special handling for <map> elements. We don't do anything now.
        default:
            break;
    }
    if (cascadedStylePropertyForElement(element, 'visibility') !== 'visible') {
        return false;
    }
    let hasAncestorWithZeroOpacity = !!enclosingElementOrSelfMatchingPredicate(element, (e) => {
        return Number(cascadedStylePropertyForElement(e, 'opacity')) === 0;
    });
    let hasAncestorWithDisplayNone = !!enclosingElementOrSelfMatchingPredicate(element, (e) => {
        return cascadedStylePropertyForElement(e, 'display') === 'none';
    });
    if (hasAncestorWithZeroOpacity || hasAncestorWithDisplayNone) {
        return false;
    }
    if (!elementSubtreeHasNonZeroDimensions(element)) {
        return false;
    }
    if (isElementSubtreeHiddenByOverflow(element)) {
        return false;
    }
    return true;
}).apply(null, arguments)

args
[{"element-6066-11e4-a52e-4f735466cecf":"2ccfb74f-c56b-4c39-80b6-425ba508006c","ELEMENT":"2ccfb74f-c56b-4c39-80b6-425ba508006c"}]`

**Comment by vvsgarapati** [comment]
element.isClickable() returning true even though it is not clickable. 
Is there any method to check whether the text is not clickable.
