### ISSUE TITLE
iOS simulators on Sauce are not working with V6

### ISSUE THREAD

**Issue by wswebcreation** [webdriverio/webdriverio#5262]
**Environment (please complete the following information):**
 - **WebdriverIO version:** `6.x.x`
 - **Mode:** Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12
 - **NPM version:** 6
 - **Browser name and version:** Sauce iOS Simulator
 - **Additional wdio packages used (if applicable):** `@wdio/sauce-service`

**Config of WebdriverIO**
See https://github.com/wswebcreation/wdio-image-comparison-service/blob/master/tests/configs/wdio.saucelabs.conf.js

**Describe the bug**
Sauce Labs provides simulators that can be used to do the automation. I use them for my image-compare-module. The simulators (iOS and Appium version independent) can be started with WebdriverIO V5, but they can't be started with WebdriverIO V6. This is only happening with iOS simulators, but not with Android emulators or normal browsers on VM's.
Based on the log you would say to increase the timeout, but even if I set it to 180 seconds, it doesn't work. If you watch the video the session is already started within the 90 seconds, so that is not the problem

**To Reproduce**
Start a clean project and use the sauce service, then try to start an iOS simulators

**Expected behavior**
Simulators can be started

**Log**
- This is the V5 execution: https://app.eu-central-1.saucelabs.com/tests/1c8785a54eed481987646764bdaab340
- This is some V5 log:

```log
2020-04-05T16:14:58.074Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2020-04-05T16:14:58.124Z DEBUG @wdio/utils:initialiseServices: initialise custom service "WdioImageComparisonService"
2020-04-05T16:14:58.125Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-04-05T16:14:58.127Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./tests/configs/wdio.saucelabs.conf.js,--logLevel=debug
[0-0] 2020-04-05T16:14:58.382Z INFO @wdio/local-runner: Run worker command: run
[0-0] RUNNING in safari - /tests/specs/mobile.spec.js
[0-0] 2020-04-05T16:14:58.462Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
[0-0] 2020-04-05T16:14:58.504Z DEBUG @wdio/utils:initialiseServices: initialise custom service "WdioImageComparisonService"
[0-0] 2020-04-05T16:14:58.632Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-04-05T16:14:58.635Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-04-05T16:14:58.638Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com:443/wd/hub/session
[0-0] 2020-04-05T16:14:58.638Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'safari',
      automationName: 'XCUITest',
      deviceName: 'iPad Pro (12.9 inch) (2nd generation) Simulator',
      platformVersion: '12.0',
      platformName: 'IOS',
      logName: 'iPadPro12.9.2nd'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'safari',
    automationName: 'XCUITest',
    deviceName: 'iPad Pro (12.9 inch) (2nd generation) Simulator',
    platformVersion: '12.0',
    platformName: 'IOS',
    logName: 'iPadPro12.9.2nd'
  }
}
[0-0] 2020-04-05T16:16:12.044Z INFO webdriver: COMMAND navigateTo("https://wswebcreation.github.io/protractor-image-comparison/")
[0-0] 2020-04-05T16:16:12.044Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com:443/wd/hub/session/1c8785a54eed481987646764bdaab340/url
[0-0] 2020-04-05T16:16:12.044Z INFO webdriver: DATA { url: 'https://wswebcreation.github.io/protractor-image-comparison/' }
```

- This is the V6 execution: https://app.eu-central-1.saucelabs.com/tests/0f737c90c38f4341a5582afe1676aba3
- This is the V6 log:
8:32

```log
2020-04-05T16:07:41.381Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2020-04-05T16:07:41.435Z DEBUG @wdio/utils:initialiseServices: initialise custom service "WdioImageComparisonService"
2020-04-05T16:07:41.436Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-04-05T16:07:41.437Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-04-05T16:07:41.438Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./tests/configs/wdio.saucelabs.conf.js,--logLevel=debug
[0-0] 2020-04-05T16:07:41.790Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-04-05T16:07:41.848Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-04-05T16:07:41.849Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in safari - /tests/specs/mobile.spec.js
[0-0] 2020-04-05T16:07:41.907Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
[0-0] 2020-04-05T16:07:41.954Z DEBUG @wdio/utils:initialiseServices: initialise custom service "WdioImageComparisonService"
[0-0] 2020-04-05T16:07:42.098Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-04-05T16:07:42.099Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-04-05T16:07:42.101Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session
[0-0] 2020-04-05T16:07:42.101Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'safari',
      automationName: 'XCUITest',
      deviceName: 'iPad Pro (12.9 inch) (2nd generation) Simulator',
      platformVersion: '12.0',
      platformName: 'IOS',
      logName: 'iPadPro12.9.2nd',
      build: 'Local build-1586102861365'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'safari',
    automationName: 'XCUITest',
    deviceName: 'iPad Pro (12.9 inch) (2nd generation) Simulator',
    platformVersion: '12.0',
    platformName: 'IOS',
    logName: 'iPadPro12.9.2nd',
    build: 'Local build-1586102861365'
  }
}
[0-0] 2020-04-05T16:09:57.409Z ERROR webdriver: GotError: Timeout awaiting 'request' for 90000ms
    at onError (/Users/wimselles/Git/wdio-image-comparison-service/node_modules/got/dist/source/request-as-event-emitter.js:137:29)
    at ClientRequest.<anonymous> (/Users/wimselles/Git/wdio-image-comparison-service/node_modules/got/dist/source/request-as-event-emitter.js:157:17)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (/Users/wimselles/Git/wdio-image-comparison-service/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at Timeout.timeoutHandler [as _onTimeout] (/Users/wimselles/Git/wdio-image-comparison-service/node_modules/got/dist/source/utils/timed-out.js:40:17)
    at listOnTimeout (internal/timers.js:551:17)
    at Timeout.timeoutHandler [as _onTimeout] (/Users/wimselles/Git/wdio-image-comparison-service/node_modules/got/dist/source/utils/timed-out.js:40:31)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:492:7)
[0-0] 2020-04-05T16:09:57.409Z ERROR @wdio/runner: Error: Failed to create session.
```

**Comment by christian-bromann** [comment]
This seems to be an issue with got not being able to follow SauceLabs redirect hack when requests take longer than 45s.

**Comment by wswebcreation** [comment]
@christian-bromann 

Do you happen to know how we can fix this, this isn't only a problem with EMU/SIM, but can also become a problem with Real Devices, not only with Sauce but with all vendors. Especially if connecting to a device takes longer that 45-60 seconds due to waiting.

**Comment by esaari** [comment]
@wswebcreation I can concur I've had a similar issue with iOS devices on the Browserstack vendor - basically, I had no problem running a full suite of tests on wdio v5, but once v6 came, something like 90% of my tests can't create sessions, reporting that they hit the Got timeout of 60s.

**Comment by christian-bromann** [comment]
I found the solution and working on a fix

**Comment by christian-bromann** [comment]
Fixed in #5306

**Comment by wswebcreation** [comment]
@christian-bromann 

Re-opening because it is not fixed 

https://app.eu-central-1.saucelabs.com/tests/61e98f031f724358bcec21dfbc61ef49#0

`[4-0]  Error:  Failed to create session.`

Working with these dependencies

```js
  "devDependencies": {
    "@wdio/cli": "^6.1.3",
    "@wdio/jasmine-framework": "^6.1.3",
    "@wdio/local-runner": "^6.1.3",
    "@wdio/sauce-service": "^6.1.0",
    "@wdio/spec-reporter": "^6.0.16",
    "@wdio/sync": "^6.1.0",
    "webdriverio": "^6.1.3"
}
```

**Comment by christian-bromann** [comment]
@wswebcreation can you provide some wdio logs?

**Comment by wswebcreation** [comment]
Yep, this is the log

```log
yarn test.saucelabs --logLevel=debug
yarn run v1.22.0
$ wdio ./tests/configs/wdio.saucelabs.conf.js --logLevel=debug

Execution of 1 spec files started at 2020-04-25T09:44:43.654Z

2020-04-25T09:44:43.656Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
2020-04-25T09:44:43.700Z DEBUG @wdio/utils:initialiseServices: initialise custom service "WdioImageComparisonService"
2020-04-25T09:44:43.701Z INFO @wdio/cli:launcher: Run onPrepare hook
2020-04-25T09:44:43.702Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2020-04-25T09:44:43.702Z INFO @wdio/local-runner: Start worker 0-0 with arg: ./tests/configs/wdio.saucelabs.conf.js,--logLevel=debug
[0-0] 2020-04-25T09:44:43.949Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2020-04-25T09:44:43.993Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-04-25T09:44:43.994Z INFO webdriverio: Initiate new session using the ./protocol-stub protocol
[0-0] RUNNING in safari - /tests/specs/mobile.spec.js
[0-0] 2020-04-25T09:44:44.036Z DEBUG @wdio/utils:initialiseServices: initialise service "sauce" as NPM package
[0-0] 2020-04-25T09:44:44.110Z DEBUG @wdio/utils:initialiseServices: initialise custom service "WdioImageComparisonService"
[0-0] 2020-04-25T09:44:44.254Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2020-04-25T09:44:44.257Z INFO webdriverio: Initiate new session using the webdriver protocol
[0-0] 2020-04-25T09:44:44.258Z INFO webdriver: [POST] https://ondemand.eu-central-1.saucelabs.com/wd/hub/session
[0-0] 2020-04-25T09:44:44.258Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'safari',
      deviceName: 'iPhone X Simulator',
      logName: 'iPhoneXSimulator',
      platformName: 'ios',
      platformVersion: '12.2',
      build: 'Local build-1587807883639'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'safari',
    deviceName: 'iPhone X Simulator',
    logName: 'iPhoneXSimulator',
    platformName: 'ios',
    platformVersion: '12.2',
    build: 'Local build-1587807883639'
  }
}
[0-0] 2020-04-25T09:47:00.348Z WARN webdriver: Request timed out! Consider increasing the "connectionRetryTimeout" option.
[0-0] 2020-04-25T09:47:00.348Z INFO webdriver: Retrying 1/3
```

Increasing this doesn't matter. Strange thing is that this is working for V5, see the instance here https://app.eu-central-1.saucelabs.com/tests/0c0f41f085aa41bca26eabd4bf3664ba#9

It also looks like that with WebdriverIO V5 everything is starting quicker than with V6

- V5 instance: https://app.eu-central-1.saucelabs.com/tests/0c0f41f085aa41bca26eabd4bf3664ba
- V6 instance: https://app.eu-central-1.saucelabs.com/tests/fe4de06d4bbc4f8fbbf78009b640fce6


Increasing the `idleTimeout` in Sauce Labs also doesn't matter, if I set it to 240 seconds it still doesn't work, it looks like the command is not getting back to WebdriverIo from Sauce Labs, because the session is created in Sauce Labs and also send back, see the instanc eof V6, but no new command is triggered from WebdriverIO

Pretty blocking now for people with Sim tests to migrate to V6. Please let me know what I can do extra to help with this.

You can just verify this with a set of capabilities like this

```js
{
        browserName: 'safari',
        deviceName: 'iPhone X Simulator',
        logName: 'iPhoneXSimulator',
        platformName: 'ios',
        platformVersion: '12.2',
}
```

**Comment by christian-bromann** [comment]
> Request timed out! Consider increasing the "connectionRetryTimeout" option.

The patch seem to work, it says to increase the `connectionRetryTimeout` option. Can you set it to a very high number to see if tests start?

**Comment by wswebcreation** [comment]
@christian-bromann 

I already did that

> ...Increasing this doesn't matter. 

> ..Increasing the idleTimeout in Sauce Labs also doesn't matter, if I set it to 240 seconds it still doesn't work...

**Comment by christian-bromann** [comment]
It seems like updated `got` magically resolves this issue. Please review!
