### ISSUE TITLE
All sessions marked as failed on Browserstack with "Unknown Error"

### ISSUE THREAD

**Issue by goatsy** [webdriverio/webdriverio#5315]
Since  @wdio/browserstack-service 6.0.10 we experience that all sessions (no matter of the actual result of the test) are marked as failed.

Status: Failed
(Marked via REST API : Unknown Error)

We use webdriverio 6.1.3
with browserstack-service 6.0.17

https://github.com/webdriverio/webdriverio/blob/f7b43b2fab60bf87b49352957b28709cc63a7f66/packages/wdio-browserstack-service/src/service.js#L62

![image](https://user-images.githubusercontent.com/27290029/80145706-e4f19f80-85b0-11ea-9310-8594095d008c.png)

It's independent of the device chosen and happens with the most simple test. 

Sample project: https://github.com/goatsy/webdriverio-tests

**Comment by christian-bromann** [comment]
Can anyone with a BS account take a look at this? @goatsy ?

**Comment by esaari** [comment]
I use Browserstack @christian-bromann. I think a lot of info is missing here. 

- Is a session being created and logged in the Browserstack portal/API? 
- What capabilities are being passed? Browserstack caps can vary depending on the platform and webdriver protocol. 

FWIW, v6 has been fine for me on just about every platform Browserstack offers except iOS.

**Comment by goatsy** [comment]
I try to setup a simple project to reproduce it

**Comment by goatsy** [comment]
I created a simple project - the only thing you need is a username/key. But I could help out with a temporary one for debugging cases.

https://github.com/goatsy/webdriverio-tests

The test is succesful (Spec Files:      1 passed, 1 total (100% completed) in 00:00:12)

But on Browserstack it shows it failed: 

![image](https://user-images.githubusercontent.com/27290029/80249267-d1f2d400-8671-11ea-8b1d-49772949f461.png)

**Comment by goatsy** [comment]
@christian-bromann Can you please remove the label "Reproducible Example Missing" 
Thank you

**Comment by bcaudan** [comment]
Could it be fixed with #5324 shipped in @wdio/browserstack-service@6.1.4?

**Comment by goatsy** [comment]
@bcaudan I found out that with 6.1.4 now setting the status of tests (Passed/Failed) works again. 
But in case the test fails you still get "(Marked via REST API : **Unknown Error**)" instead of the real error reason.

**Comment by goatsy** [comment]
I just tested with @wdio/browserstack-service@6.1.4 and the error is gone. 
I have valid results when a test fails now again!

**Comment by christian-bromann** [comment]
Awesome, thanks @nextlevelbeard for fixing it in #5271
