### ISSUE TITLE
Failure to refetch an element previously fetched using a custom locator

### ISSUE THREAD

**Issue by chrisbottin** [webdriverio/webdriverio#6377]
**Environment (please complete the following information):**
 - **WebdriverIO version:** v6.12.1 and v7.0.0+
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v12.10.0
 - **NPM version:** v6.10.3
 - **Browser name and version:** Chrome 88.0.4324.96
 - **Platform name and version:** Mac OS Catalina
 - **Additional wdio packages used (if applicable):** n/a

**Config of WebdriverIO**
Using configuration from the tests inside `packages/webdriverio` 

**Describe the bug**
When retrieving an element using a custom locator and if at some point the element become stale and it needs to be refetch automatically, the method fail because the strategy is a custom strategy not expected by the code.

**To Reproduce**

To simplify the reproduction I have created a new test to `packages/webdriverio/tests/utils/refetchElement.test.ts`:

```js
it('should successfully refetch an element using custom locator', async () => {
    browser.addLocatorStrategy('myLocator', (id: string) => (
        { 'element-6066-11e4-a52e-4f735466cecf': id }
    ))

    const elem = await browser.custom$('myLocator', 'foo')
    const refetchedElement = await refetchElement(elem, '$')
    expect(elem.elementId).toEqual('foo')
    expect(refetchedElement.elementId).toEqual(elem.elementId)   // << This assertion fails
})
```

When running this test, the last `expect` fails with `Expected: "foo" but Received: "some-elem-123"`.

When running the code on the browser with WDIO Testrunner, I receive an error about the selector is not a valid XPATH. In this case the selector is the custom locator function as a string. e.g.  using the above test code the selector passed to webdriver is `"(id) => ({ 'element-6066-11e4-a52e-4f735466cecf': id })"`

**Expected behavior**

* When refetching an element previously fetched using a custom locator, the code should reuse the custom locator to refetch the element.
* The above test should pass

**Comment by christian-bromann** [comment]
Fixed in #6915

**Comment by chrisbottin** [comment]
@christian-bromann I think there is still an issue with the custom locator strategy.

The correct strategy is now used to refetch the element thanks to your fix but the `strategyArguments` passed in the original `custom$` or `custom$$` are not being passed again during the refetch, instead we are getting an empty arguments list.

Here for example https://github.com/webdriverio/webdriverio/pull/6915/commits/5ca1ff496b34c92610e464ab39937c13d5c3a688#diff-bba60dc111952f63dd1af3d75c7f5ef481ac2a2e3ece7bc75e7357e13dc4f4f9R55 I think we should provide `strategyArguments` to `getElement` so the original arguments can be reused when calling the custom strategy again to refetch the element.

The unit test that I wrote above in this issue still fails which I believe is a good indication that a bug is still present.

**Comment by christian-bromann** [comment]
@chrisbottin mind creating a new issue with a reproducible example? Any contribution to WebdriverIO are also appreciated.

**Comment by chrisbottin** [comment]
@christian-bromann done #8176
