### ISSUE TITLE
Devtools with coverageReporter will freeze the page/not render the page

### ISSUE THREAD

**Issue by kailin0512** [webdriverio/webdriverio#6993]
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.7.3
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 14.16.0
 - **NPM version:** 6.14.11
 - **Browser name and version:** Chrome 90
 - **Platform name and version:**MAC OS
 - **Additional wdio packages used (if applicable):** @wdio/selenium-standalone service, @wdio/devtools-service

**Config of WebdriverIO**
```
services: [
        'selenium-standalone',
        ['devtools', 
        {
                coverageReporter: {
                enable: true,
                type: 'html',
                logDir: __dirname + '/coverage',
                // exclude: [/.*jquery-1.11.3.min.js/],
                exclude: [/.*298279967.js/],
            }
        }]
    ],
```
**Describe the bug**
When we include coverageReporter, multiple sites are not able to run the e2e tests(some pages not rendered, some page keep loading without finishing) Eg: www.ebay.com, http://json.org/foo.js

**To Reproduce**
Repo: https://github.com/kailin0512/webdriverio-debug 
Run yarn run test
if comment coverageReporter code block, everything works fine

**Expected behavior**
Including coverage reporter should also able to run test cases

**Log**
Create a [Error log for devtools/codecoverage](https://gist.github.com/kailin0512/a31662b0f7bc4384950a8ce659a1dbe9)

**Comment by kailin0512** [comment]
Hello @christian-bromann , any suggestions or starting point that I can take a look or maybe contribute?

**Comment by christian-bromann** [comment]
Please have a look into our [contributing guidelines](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) and the responsible code for this is located in the [devtools service](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-devtools-service/src/gatherer/coverage.ts).

**Comment by kailin0512** [comment]
Thanks, It seems to me that for ebay.com, one js file is blocked (keep pending status)
![image](https://user-images.githubusercontent.com/82549164/122093030-a03e4e80-cdd8-11eb-8514-a9bc87dfab86.png), I think that might be the reason why the page freezes, but I am not quite sure how to resolve this.

for the http://json.org/foo.js, I am not able to capture the network traffic from chrome so a little bit harder for me to debug.

I feel like it might relate to something for the redirect?

Any suggestions?

**Comment by christian-bromann** [comment]
fixed in #7020

**Comment by kailin0512** [comment]
@christian-bromann 
It seems that these issues are still happening with the latest release For ebay.com, it just skips the code coverage, for json.org, it still have this 
```
Timeout of 60000ms exceeded. The execution in the test "My Login application should foo" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/Users/kailin/Desktop/work/opensource/webdriverio-debug/test/specs/example.e2e.js)
```

Any thoughts?

**Comment by christian-bromann** [comment]
I checked and stumbled now on other problems that I didn't experienced when I fixed this bug. Feel free to raise another issue and help us provide a PR. Thanks!

**Comment by kailin0512** [comment]
It seems that most description remains the same and the that debug repo remains working, should we just reopen this issue? @christian-bromann

**Comment by christian-bromann** [comment]
Same labels stand .. please get involved if you like a fix for this.

**Comment by kailin0512** [comment]
Thanks, I made several tries several months ago and it seems not working, I will revisit this again and try to make a fix

**Comment by ShivaPotlapelli** [comment]
@christian-bromann we are facing this issue when can we expect an fix for this

**Comment by christian-bromann** [comment]
As I mentioned before in this thread, if you experience this bug, get involved and help provide a fix. I am not working on this as I am contributing to other parts of the project.

**Comment by christian-bromann** [comment]
We are about to deprecate this feature with v9. It would be amazing to have a dedicated community package that allows to capture JS coverage for frontend apps. At this point it doesn't seem valuable enough for the main WebdriverIO team to take on and continue to maintain. Any feedback is appreciated.
