### ISSUE TITLE
It cannot iterate over a list of elements if checked an invisible sub-element in the loop

### ISSUE THREAD

**Issue by wei-y** [webdriverio/webdriverio#7204]
[//]: # NOTE: This repository only maintains packages that are listed in the [Readme](https://github.com/webdriverio/webdriverio/blob/main/README.md#packages). Please make sure that your issue is directly caused by one of these packages and if not file an issue in the correct 3rd party package repository.

**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.9.0
 - **Mode:** framework: "mocha"
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v15.3.0
 - **NPM version:** 7.0.14
 - **Browser name and version:** Chrome v92.0.4515.107
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** [e.g. @wdio/spec reporter, @wdio/selenium-standalone service]

**Config of WebdriverIO**
```javascript
exports.config = {
  runner: "local",
  specs: ["./test/specs/**/*.js"],
  exclude: [],
  bail: 0,
  baseUrl: global.baseUrl,
  waitforTimeout: 30000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: ["chromedriver"],
  framework: "mocha",
  reporters: ["spec"],
  mochaOpts: {
    ui: "bdd",
    timeout: 24 * 60 * 60 * 1000,
  },
};
```

**Describe the bug**
When I use `$$()` to locate a group of elements, and iterate over them using a `forEach` loop, if a invisible sub-element is checked, it will stuck in the loop.

**To Reproduce**

An example is as below
```javascript
describe("test wdio", function () {
  it("should click menus", function () {
    browser.url("https://webdriver.io/docs/gettingstarted");
    const $$menus = $$(".sidebar_15mo button+ul>.menu__list-item");
    $$menus.forEach(($menu) => {
      if (!$menu.$(".menu__listaa").isDisplayed()) {
        console.log($menu.getText());
        $menu.$("a").click();
      }
    });
  });
});
```
It stuck on the first element and cannot finish the loop in v7.9.0.
There were no issues running in v7.8.0. Also, there is no issue if the condition checking element visibility is removed.

**Expected behavior**
Same behavior as in v7.8.0

**Log**
If applicable, add logs to help explain your problem.
Create a [gist](https://gist.github.com) which is a paste of your _full_ Selenium/WebdriverIO logs, and link them here. Do _not_ paste your full Appium logs here, as it will make this issue very long and hard to read! If you are reporting a bug, _always_ include Selenium/WebdriverIO logs!

**Additional context**

> Please use the correct markdown

**Comment by christian-bromann** [comment]
Can you provide logs running this for `v7.8.0` and `v7.9.0`? Also can you try:
```js
describe("test wdio", function () {
  it("should click menus", function () {
    browser.url("https://webdriver.io/docs/gettingstarted");
    const $$menus = $$(".sidebar_15mo button+ul>.menu__list-item");
    for (const $menu of $$menus) {
      if (!$menu.$(".menu__listaa").isDisplayed()) {
        console.log($menu.getText());
        $menu.$("a").click();
      }
    }
  });
});
```

**Comment by wei-y** [comment]
Changing the loop from `forEach` to `for (... of ...)` did not change the behavior. Logs of both versions are attached.
[v7.8.0.log](https://github.com/webdriverio/webdriverio/files/6913645/v7.8.0.log)
[v7.9.0.log](https://github.com/webdriverio/webdriverio/files/6913646/v7.9.0.log)

**Comment by christian-bromann** [comment]
@wei-y what is the error you are experiencing?

**Comment by christian-bromann** [comment]
fixed in #7225

**Comment by wei-y** [comment]
@christian-bromann I upgraded to 7.9.1 and it seems that it's not fixed. The issue is that when running the example, it always clicks the first element. The expectation is that it can click all menu items in the loop. Please see it in action in the screen capture attached.

https://user-images.githubusercontent.com/17232098/128988343-db0c9a96-0017-45ad-af56-38e57d0eb17a.mp4

**Comment by christian-bromann** [comment]
@wei-y what is the code you are running?

**Comment by wei-y** [comment]
> @wei-y what is the code you are running?

It's the code in the ticket description:

```javascript
describe("test wdio", function () {
  it("should click menus", function () {
    browser.url("https://webdriver.io/docs/gettingstarted");
    const $$menus = $$(".sidebar_15mo button+ul>.menu__list-item");
    $$menus.forEach(($menu) => {
      if (!$menu.$(".menu__listaa").isDisplayed()) {
        console.log($menu.getText());
        $menu.$("a").click();
      }
    });
  });
});
```

**Comment by christian-bromann** [comment]
Seems to be a weird issue where the refetch mechanism doesn't work properly. Any help on this investigating our [middleware](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/middlewares.ts#L12) behavior is appreciated.

**Comment by wei-y** [comment]
This issue has been fixed in v7.12.3
