### ISSUE TITLE
jasmine expects fails after wdio packages update to last version

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#7466]
### Discussed in https://github.com/webdriverio/webdriverio/discussions/7465

<div type='discussions-op-text'>

<sup>Originally posted by **NavyMint** September 22, 2021</sup>
Hi, guys
I've just updated wdio packages to latest version and all specs starts to fail on expect statements with next errors:

TypeError: expect(...).toEqual is not a function
TypeError: expect(...).toBe is not a function

test case:
```
it('test', () => {
        const test = 123;
        expect(test).toBe(123);
    });
```

Can you please suggest us what can be the problem here?

</div>

**Comment by christian-bromann** [comment]
@NavyMint can you provide a reproducible example. Running a quick smoke tests showed that this works.

**Comment by NavyMint** [comment]
For me its constantly reproducible, created repo where I checked this problem https://github.com/NavyMint/reproduce-err

**Comment by angelo-loria** [comment]
Seems to only certain matchers failing. I am getting the same 'TypeError: expect(...).toBeLessThanOrEqual error on an `expect(array.length).toBeLessThanOrEqual(3).`

Failed test run- https://github.com/angelo-loria/WebDriverIODemo/runs/3679145322?check_suite_focus=true
Spec- https://github.com/angelo-loria/WebDriverIODemo/blob/a5cdf49f049c65709110adb3f2312439d69ff369/src/specs/retirementSavingsCalc.spec.ts#L39

**Comment by christian-bromann** [comment]
fixed in #7467

**Comment by Praney** [comment]
I am still facing the issue. I am on the latest version of wdio . Please help. Below is the error 
`TypeError: expect(...).toEqual is not a function`
`wdio --version
7.16.8
`
