### ISSUE TITLE
[🐛 Bug]: shared-store-service - Unable to access the shared store key in onComplete hook

### ISSUE THREAD

**Issue by christophss** [webdriverio/webdriverio#7915]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.16.3

### Node.js Version

16.13.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  browserVersion: 'latest',
  platformName: 'Windows 10'
}
```

### What happened?

In the wdio config, 
1. I have added 'shared-store' to service list.
2. Imported getValue and setValue from @wdio/shared-store-service
3. Initialized a shared store variable as 
```js
await setValue("key", []);
```
4. From other hooks, during the test execution, I updated the array assigned to the key. All the objects inside the list is accessible.
5. Tried to access the "key" from onComplete as
```js
await getValue("key");
```

While getValue retrieves the key in other hooks, in onComplete hook, it returns undefined.
```js
2022-01-12T23:35:19.305Z WARN  @wdio/shared-store-service: undefined undefined undefined undefined
2022-01-12T23:35:19.350Z ERROR @wdio/cli:utils: Error in onCompleteHook: TypeError: Cannot read properties of undefined 
```

Any suggestions if I missed anything?

Thanks,
Chris

### What is your expected behavior?

Shared store key should also be accessible from onComplete.

### How to reproduce the bug.

1. Add a shared-store-service in onPrepare hook
```js
await setValue("key", []);
```
2. In afterFeature or afterTest hook, update the key using 
```js
const temp = await getValue("key");
temp.push("something");
await setValue("key", temp);
```
3. Print the key in onComplete
```js
console.log(`Shared Store content: ${JSON.stringify(await getValue("key"))}`);
```

### Relevant log output

```typescript
Logs attached in the issue description.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
Thanks for reporting!

This feature was initially implemented in #7519 by @Slashgear. 

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by christian-bromann** [comment]
Fixed in https://github.com/webdriverio/webdriverio/pull/8099

**Comment by mighty98** [comment]
@christian-bromann I could still see the same issue with v7.19.7

**Comment by christian-bromann** [comment]
Can you provide a reproducible example?
