### ISSUE TITLE
[🐛 Bug]: shared-store-service - Unable to access store key in onPrepare and beforeSession hooks

### ISSUE THREAD

**Issue by josserestrepo** [webdriverio/webdriverio#8116]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

^7.16.13

### Node.js Version

7.23.0

### Mode

Standalone Mode

### What happened?

1. I have set a variable inside the "onPrepare" hook 
 ` await setValue('foo', ;bar')`
3. Read that variable inside the "onPrepare" hook
 ` await getValue('foo', ;bar')`
4.  Undefined value is returned.

This is also happening on "beforeSession" hook

### What is your expected behavior?

`await getValue('foo')` should return its value in the "onPrepare" hook and specially in "beforeSession" hook

### How to reproduce the bug.

1. Set a variable inside the "onPrepare" hook 
 ` await setValue('foo', ;bar')`
3. Read that variable inside the "onPrepare" hook
 `const sharedStore = await getValue('foo', ;bar')`
4.  Print value
  `console.log(sharedStore)`

### Relevant log output

```typescript
No relevant output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by christian-bromann** [comment]
@josserestrepo can you provide a reproducible example? This was fixed in #8099 and should be resolved with the latest version of WebdriverIO.

**Comment by josserestrepo** [comment]
Hi @christian-bromann I have updated to the WDIO latest versions and the error persists included in onCompleted hook
`   onPrepare: async(config, capabilities) => {
      await setValue('foo', 'bar');
      console.log('shared-store-service in onPrepare');
      console.log(await getValue('foo'));
   }`
   
   this was the result in the output
`Execution of 1 workers started at 2022-03-16T17:34:21.032Z

shared-store-service in onPrepare
undefined`

**Comment by christian-bromann** [comment]
@josserestrepo I double checked and it appears that this change was not yet released. I just triggered a release and it should be fixed in `7.18.0` in a couple of minutes.

**Comment by christian-bromann** [comment]
It indeed doesn't work for `beforeSession`. I am not sure why you need to use `getValue` in `onPrepare`, please elaborate.

Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions. Cheers!

**Comment by josserestrepo** [comment]
Hi @christian-bromann actually I don't need to use it in `onPrepare` I just was providing info about the issue, I do need it for `beforeSession` because I am using `shared-store-service` to store login info from my system.

**Comment by Staicul** [comment]
I would like to try fixing this one, @christian-bromann .

**Comment by ceroshatdoshii** [comment]
@Staicul  was wondering about the progress of this bug....

**Comment by Staicul** [comment]
There is progress. Most probably will find time to create a PR this weekend.

**Comment by Staicul** [comment]
No, still figuring out some details...

**Comment by christian-bromann** [comment]
This has been fixed and merged/released. Thanks @Staicul for the contribution!
