### ISSUE TITLE
[🐛 Bug]: v8 @wdio/utils - safeImport finds and imports the CommonJS version of a package

### ISSUE THREAD

**Issue by RossVertizan** [webdriverio/webdriverio#9279]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

next - 8.0.0-alpha.631

### Node.js Version

v18.12.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
Not related to capabilities
```

### What happened?

In order to make the vitaqai-service work, I have a slightly modified version of mocha - ```vitaqai-mocha```.  In order to load this I have a minimally modified version of the ```@wdio/mocha-framework``` called ```wdio-vitaqai-mocha-framework```, which simply imports Mocha from ```vitaqai-mocha``` as opposed to ```mocha```.

In order to support the CommonJS (require) structure of WebdriverIO V7 (and below) and the ESM (import) structure of WebdriverIO V8 (and above), I have prepared a version of the  ```wdio-vitaqai-mocha-framework`` package which has both CJS and ESM variants and the necessary directives in the ```package.json``` file to load the correct version.

This approach works fine in V7.  However in V8, the CJS variant is loaded and this subsequently causes errors, as packages are then loaded using require and I get this message:
```Error [ERR_REQUIRE_ESM]: require() of ES Module Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\@wdio\logger\build\index.js from Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\wdio-vitaqai-mocha-framework\build\cjs\index.js not supported.```

### What is your expected behavior?

I expected that the ESM variant of the package would be loaded in preference to the CJS variant

### How to reproduce the bug.

I am not going to provide a reproducible test case at this point as I am happy to work through this and submit a pull request.  All I need from the team is guidance on what is expected behaviour in V8.  It may be that my expectations are incorrect.  If necessary I will provide a simple example later.

I will add what I have done so far in a first reply to this issue.

### Relevant log output

```typescript
[0-0] Starting VitaqAI client for connection to Vitaq API ...
[0-0] ==> Connected to Vitaq
[0-0] ==> Sending authentication request
[0-0] ==> Authenticated
[0-0] ==> Registered
[0-0] ==> Python script launched successfully!
[0-0] 2022-12-01T16:02:48.915Z INFO wdio-vitaqai-service: Successfully started Vitaq
[0-0] 2022-12-01T16:02:49.134Z ERROR @wdio/local-runner: Failed launching test session: Error: Couldn't initialise "wdio-vitaqai-mocha-framework".
[0-0] Error [ERR_REQUIRE_ESM]: require() of ES Module Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\@wdio\logger\build\index.js from Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\wdio-vitaqai-mocha-framework\build\cjs\index.js not supported.
[0-0] Instead change the require of Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\@wdio\logger\build\index.js in Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\wdio-vitaqai-mocha-framework\build\cjs\index.js to a dynamic import() which is available in all CommonJS modules.
[0-0]     at Object.<anonymous> (Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\wdio-vitaqai-mocha-framework\build\cjs\index.js:19:34)
[0-0]     at async Promise.all (index 0)
[0-0]     at async safeImport (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/utils/build/utils.js:189:21)
[0-0]     at async initialisePlugin (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/utils/build/initialisePlugin.js:32:20)
[0-0]     at async #initFramework (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/runner/build/index.js:167:32)
[0-0]     at async Runner.run (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/runner/build/index.js:72:27)
[0-0]     at safeImport (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/utils/build/utils.js:211:15)
[0-0]     at async initialisePlugin (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/utils/build/initialisePlugin.js:32:20)
[0-0]     at async #initFramework (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/runner/build/index.js:167:32)
[0-0]     at async Runner.run (file:///Y:/vitaqai_itc_testing/vitaq-example-v8/node_modules/@wdio/runner/build/index.js:72:27)
[0-0] FAILED
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by RossVertizan** [comment]
Working though the error stack above it quickly becomes apparent that the problem is occurring in the ```safeImport``` function in ```@wdio/utils```.

In the header of this file ```require``` has been defined using:
```javascript
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
```

this is then used in the safeImport function in the following manner:
```javascript
requirePath = require.resolve(name);
```
as detailed [in this SO answer](https://stackoverflow.com/a/62499498/4945676)

However, if we look [in the Node JS documentation](https://nodejs.org/api/module.html#modulecreaterequirefilename) it seems to suggest that this is used for finding a CommonJS package and that is exactly what I see, we can see on this line of the output:
```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\@wdio\logger\build\index.js from Y:\vitaqai_itc_testing\vitaq-example-v8\node_modules\wdio-vitaqai-mocha-framework\build\cjs\index.js not supported.
```
that we are referencing the index.js in the ```cjs``` directory and not the ```esm``` directory as I expected, because this is the version found by ```require.resolve```.

As an alternate solution I have implemented the following code:
```javascript
import { createRequire } from 'node:module';
import {resolve} from 'import-meta-resolve'
const require = createRequire(import.meta.url);
```
which imports the ```resolve``` function from ```import-meta-resolve```.

And then inside ```safeImport``` I use this to get the ESM variant:
```javascript
try {
    esmImportPath = await resolve(name, pathToFileURL(localNodeModules));
    console.debug(`*** safeImport: esmImportPath: ${esmImportPath}`);
} catch (e) {
    console.debug(`*** safeImport: esmImportPath: ${e}`);
}
```
and finally if I have found an ```esmImportPath``` I preferentially use this over the ```requirePath``` :
```javascript
let pkg;
if (esmImportPath) { 
    pkg = await import(esmImportPath);
} else {
    pkg = await import(requirePath);
}
```

When I do this it now works as expected.

Are there any comments from the team before I work this up into a PR?

Am I missing something?

**Comment by christian-bromann** [comment]
@RossVertizan thanks for filing the issue.

Can you check with the current released v8 version? We actually added `import-meta-resolve` to mitigate this problem. Cab you double check you are using the latest version?

**Comment by RossVertizan** [comment]
@christian-bromann  - I have looked and this is what I have found:

1. I looked on GitHub in webdriverio/webdriverio repo on the ```main``` branch in the file ```packages/wdio-utils/src/utils.ts``` and searched for ```import-meta-resolve``` and it is not imported into that file.

2. So, I did the following:
```shell
    mkdir wdio_v8
    cd wdio_v8
    npm init -y
    npm init wdio .
```
then I opened that folder in VS Code and used the 'Find In Folder' feature and searched for ```import-meta-resolve```, which I did find in a number of places, such as:

```node_modules\@wdio\cli\build\utils.js```
```node_modules\@wdio\config\build\utils.js```
```node_modules\devtools\build\commands\status.js```
```node_modules\devtools\build\commands\utils.js```
```node_modules\webdriverio\build\commands\browser\react$.js```
```node_modules\webdriverio\build\commands\browser\react$$.js```
```node_modules\webdriverio\build\commands\element\react$.js```
```node_modules\webdriverio\build\commands\element\react$$.js```
and of course the associated ```package.json``` and ```package-lock.json``` files, but not in ```@wdio/utils```.

Out of interest I did a search for ```createRequire``` which may indicate which other files need attention and found it in:

 ```node_modules\@wdio\cli\build\constants.js```
 ```node_modules\@wdio\protocols\build\index.js```
 ```node_modules\@wdio\utils\build\utils.js```
 ```node_modules\es-get-iterator\test\node.mjs```
 ```node_modules\webdriver\build\request\index.js```
```node_modules\webdriverio\build\constants.js```

So it would seem that ```import-meta-resolve``` was implemented, but a couple of locations may have been missed.

I'll await your confirmation and guidance.

**Comment by danielhjacobs** [comment]
Can confirm that this seems to be causing CI test failures in https://github.com/ruffle-rs/ruffle/actions/runs/3600306295/jobs/6064826852 (bump @wdio/mocha-framework from 7.20.7 to 8.0.2), https://github.com/ruffle-rs/ruffle/actions/runs/3600305848/jobs/6064826290 (bump @wdio/static-server-service from 7.25.4 to 8.0.0) and https://github.com/ruffle-rs/ruffle/actions/runs/3600305701/jobs/6064824246 (bump @wdio/spec-reporter from 7.25.4 to 8.0.0).

**Comment by RossVertizan** [comment]
OK, just to be clear, you mean we should implement ```import-meta-resolve``` in ```node_modules\@wdio\utils\build\utils.js```

Do we want to leave a fallback to CJS if the ESM module is not found, I hardly see the point in that, it's what I implemented an outlined above as a quick POC?

I'm happy to pick this up as it's stopping me from updating and publishing my Vitaq Service for V8

**Comment by christian-bromann** [comment]
Yeah I think the reason why I kept the old require there is to ensure support for CJS plugins, which still exist and we should not break support for them. But in order to fix this issue I suggest to use `import-meta-resolve` as like a first import attempt and have `require` as fallback.

**Comment by RossVertizan** [comment]
OK - will do.

**Comment by christian-bromann** [comment]
This got merged and released. Thanks @RossVertizan for the fix 🎉
